import test,{after} from 'node:test'
import assert from 'node:assert/strict'
import {build} from 'esbuild'
import {randomUUID,createHash} from 'node:crypto'
import {admin,assertFixture,pool,close} from './local-pg.mjs'
assertFixture();after(close)
const bundle=await build({stdin:{contents:"export * from './lib/identity/customer-final-reconciliation-repository.ts';export * from './lib/identity/customer-token-vault.ts'",resolveDir:process.cwd()},bundle:true,format:'esm',platform:'node',write:false,logLevel:'silent'})
const {createCustomerFinalReconciliationRepository:createRepo,createAesGcmEnvelopeVault}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'))
const q=s=>"'"+String(s).replaceAll("'","''")+"'",j=x=>q(JSON.stringify(x))+'::jsonb',hash=x=>createHash('sha256').update(x).digest('hex')
const CONFIG='4'.repeat(64),INTENT='5'.repeat(64),OUTER='6'.repeat(64),VERIFIER=Buffer.alloc(32,1).toString('base64url'),CHALLENGE=createHash('sha256').update(VERIFIER).digest('base64url'),SUB='tllb_'+Buffer.alloc(32,2).toString('base64url')
const pVault=createAesGcmEnvelopeVault({activeKeyId:'p',keys:new Map([['p',Buffer.alloc(32,1)]])}),fVault=createAesGcmEnvelopeVault({activeKeyId:'f',keys:new Map([['f',Buffer.alloc(32,2)]])})
const envelope=()=>fVault.seal({synthetic:'ciphertext-only'},['fixture','final'])
function reset(){admin(`TRUNCATE tll_bridge_private.final_operations,tll_bridge_private.finalizations,tll_bridge_private.operations,tll_bridge_private.grants,tll_broker_private.operations,tll_broker_private.flows,tll_broker_private.subjects,tll_provisional_private.operations,tll_provisional_private.intents,tll_customer_private.shopify_proofs CASCADE; UPDATE tll_bridge_private.control SET enabled=false,epoch=1; UPDATE tll_broker_private.control SET enabled=false; UPDATE tll_provisional_private.control SET enabled=false; UPDATE tll_customer_private.control SET enabled=false;`)}
function seed({mode='sign_in',user='a0000000-0000-4000-8000-000000000001'}={}){reset();const tx=randomUUID(),receipt=randomUUID(),identity=randomUUID(),admission=randomUUID(),registration=randomUUID(),state=randomUUID(),now=Date.now(),browser=hash(randomUUID()),subject='shopify-'+randomUUID()
 const callback=`https://the-lifting-preview-my-lifting-lab-s-projects.vercel.app/auth/customer/callback?code=${randomUUID()}`,callbackHash=hash(callback)
 const original=mode==='migration'?{userId:user,sessionId:randomUUID(),accessTokenHash:hash('original')}:null,target=mode==='migration'?{userId:user,sessionId:original.sessionId}:null
 const metadata={transactionId:tx,browserHash:browser,configHash:CONFIG,intentHash:INTENT,applicationOrigin:'https://the-lifting-preview-my-lifting-lab-s-projects.vercel.app',mode,original,applicationPkceChallenge:CHALLENGE,createdAt:now,expiresAt:now+240000}
 const provisional=pVault.seal({verifier:VERIFIER},['tll-provisional-admission/1','qdmvngjwkcsilzmqksme','application-pkce',tx,CONFIG,browser,INTENT,'0'])
 const proof={transactionId:tx,receiptId:receipt,shopId:'107532616020',issuer:'https://shopify.com/authentication/107532616020',subject,innerPkceChallenge:Buffer.alloc(32,3).toString('base64url'),verifiedAt:now,expiresAt:now+180000}
 const registrationRecord={id:tx,configHash:'7c54b659cf0e2ecdf07ce2b34ea10d7fc0a7c6ef3c9f59f38ca8f5cd79e86780',browserHash:browser,outerHash:OUTER,outer:{clientId:'tll-staging-subject-broker-v1',redirectUri:'https://qdmvngjwkcsilzmqksme.supabase.co/auth/v1/callback',state,scope:'subject',challenge:Buffer.alloc(32,4).toString('base64url'),method:'S256'},applicationPkceChallenge:CHALLENGE,mode,target,createdAt:now,expiresAt:now+240000}
 admin(`INSERT INTO tll_provisional_private.intents(id,browser_hash,config_hash,intent_hash,application_challenge,metadata,material,created_at,expires_at,state,generation,fence,outer_request,outer_hash,outer_state,bridge_epoch) VALUES(${q(tx)},${q(browser)},${q(CONFIG)},${q(INTENT)},${q(CHALLENGE)},${j(metadata)},${j(provisional)},clock_timestamp(),clock_timestamp()+interval '4 minutes','admitted',0,1,${j(registrationRecord.outer)},${q(OUTER)},${q(state)},1);
 INSERT INTO tll_provisional_private.operations VALUES(${q(admission)},${q(tx)},'admission',0,1,true,clock_timestamp());
 INSERT INTO tll_broker_private.subjects(sub,shop_id,issuer,subject,reservation,pending_user_id,bound_user_id,created_at) VALUES(${q(SUB)},'107532616020','https://shopify.com/authentication/107532616020',${q(subject)},${q(mode==='migration'?'pending_migration':'provisional')},${mode==='migration'?q(user):'NULL'},NULL,clock_timestamp());
 INSERT INTO tll_broker_private.flows(id,config_hash,browser_hash,outer_hash,outer_state,registration,created_at,expires_at,status,generation,fence,sub,proof_receipt_id,shopify_proof,migration_proof,hard_deadline,code_hash,bearer_hash,bearer_expires_at) VALUES(${q(tx)},'7c54b659cf0e2ecdf07ce2b34ea10d7fc0a7c6ef3c9f59f38ca8f5cd79e86780',${q(browser)},${q(OUTER)},${q(state)},${j(registrationRecord)},clock_timestamp(),clock_timestamp()+interval '4 minutes','consumed',0,1,${q(SUB)},${q(receipt)},${j(proof)},NULL,clock_timestamp()+interval '3 minutes',${q(hash('code'+tx))},${q(hash('bearer'+tx))},clock_timestamp()+interval '2 minutes');
 INSERT INTO tll_customer_private.shopify_proofs(transaction_id,state_hash,config_hash,callback_url,inner_challenge,created_at,expires_at,state,fence,claim_operation,receipt_id,shop_id,issuer,subject,verified_at,proof_expires_at,access_expires_at,tokens) VALUES(${q(tx)},${q(hash('state'+tx))},${q(CONFIG)},'https://the-lifting-preview-my-lifting-lab-s-projects.vercel.app/auth/customer/shopify/callback',${q(proof.innerPkceChallenge)},clock_timestamp(),clock_timestamp()+interval '4 minutes','verified',1,${q(randomUUID())},${q(receipt)},'107532616020','https://shopify.com/authentication/107532616020',${q(subject)},clock_timestamp(),clock_timestamp()+interval '3 minutes',clock_timestamp()+interval '4 minutes',${j(envelope())});
 INSERT INTO tll_bridge_private.grants(id,binding,source_snapshot,admission_operation,admission_fence,source_generation,registration_operation,outer_hash,epoch,expires_at,state) VALUES(${q(tx)},${j({transactionId:tx,browserHash:browser,configHash:CONFIG,intentHash:INTENT,applicationPkceChallenge:CHALLENGE,admissionOperationId:admission,admissionFence:'1',generation:'0'})},'{}',${q(admission)},1,0,${q(registration)},${q(OUTER)},1,clock_timestamp()+interval '4 minutes','browser_admitted');
 UPDATE tll_bridge_private.control SET enabled=true; UPDATE tll_broker_private.control SET enabled=true; UPDATE tll_provisional_private.control SET enabled=true; UPDATE tll_customer_private.control SET enabled=true;`)
 return{tx,receipt,identity,user,browser,callback,callbackHash,mode}}
const repo=fault=>createRepo({pool:pool(fault),provisionalVault:pVault,finalVault:fVault,syntheticExecution:true})
const finish=(x,c,user=x.user)=>({transactionId:x.tx,operationId:randomUUID(),fence:c.fence,generation:c.generation,callbackHash:x.callbackHash,shopifyProofReceiptId:x.receipt,result:{kind:'private_provisional',session:{accessToken:'private-access',refreshToken:'private-refresh',tokenType:'Bearer',expiresAt:Date.now()+3600000},proof:{userId:user,authenticatedAt:Date.now()-1000,checkedAt:Date.now(),expiresAt:Date.now()+3600000},identity:{identityId:x.identity,userId:user,subject:SUB}}})

test('actual PG sign-in claim, promotion and exact release are one-use and encrypted',async()=>{const x=seed(),r=repo(),c=await r.claim({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID()});assert.equal(c.status,'claimed');assert.equal(c.exchange.applicationVerifier,VERIFIER);assert.equal(await r.finish(finish(x,c)),true);const out=await r.release({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback});assert.equal(out.status,'reconciled');assert.equal(out.userId,x.user);assert.equal(out.session.accessToken,'private-access');assert.equal(admin(`SELECT reservation||':'||bound_user_id FROM tll_broker_private.subjects WHERE sub=${q(SUB)}`),'bound:'+x.user);assert.equal((await r.claim({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID()})).status,'rejected');assert.equal((await r.release({transactionId:x.tx,browserHash:'0'.repeat(64),callbackUrl:x.callback})).status,'rejected')})
test('migration rejects a switched authoritative UUID and retains pending ownership',async()=>{const x=seed({mode:'migration'}),r=repo(),c=await r.claim({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID()});assert.equal(c.status,'claimed');assert.equal(c.originalUserId,x.user);assert.equal(await r.finish(finish(x,c,'a0000000-0000-4000-8000-000000000002')),false);assert.equal(admin(`SELECT reservation||':'||pending_user_id FROM tll_broker_private.subjects WHERE sub=${q(SUB)}`),'pending_migration:'+x.user)})
test('lost finish acknowledgement is quarantined with no releasable session',async()=>{const x=seed(),base=repo(),c=await base.claim({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID()});assert.equal(c.status,'claimed');const lost=repo(({sql,op})=>sql==='COMMIT'&&op==='finish');await assert.rejects(()=>lost.finish(finish(x,c)),/unavailable/);await base.hold({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID(),fence:c.fence,generation:c.generation});assert.equal((await base.release({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback})).status,'rejected');assert.equal(admin(`SELECT state||':'||(session_material IS NULL) FROM tll_bridge_private.finalizations WHERE transaction_id=${q(x.tx)}`),'held:true')})
test('concurrent claims admit exactly one database winner',async()=>{const x=seed(),a=repo(),b=repo();const values=await Promise.all([a.claim({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID()}),b.claim({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID()})]);assert.deepEqual(values.map(v=>v.status).sort(),['claimed','rejected'])})
test('migration promotes only its retained original UUID',async()=>{const x=seed({mode:'migration'}),r=repo(),c=await r.claim({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID()});assert.equal(c.status,'claimed');assert.equal(await r.finish(finish(x,c)),true);assert.equal(admin(`SELECT reservation||':'||bound_user_id||':'||(pending_user_id IS NULL) FROM tll_broker_private.subjects WHERE sub=${q(SUB)}`),'bound:'+x.user+':true')})
test('lost claim acknowledgement can only be quarantined and cannot exchange or release',async()=>{const x=seed(),lost=repo(({sql,op})=>sql==='COMMIT'&&op==='claim'),base=repo();await assert.rejects(()=>lost.claim({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID()}),/unavailable/);await base.hold({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID()});assert.equal(admin(`SELECT state FROM tll_bridge_private.finalizations WHERE transaction_id=${q(x.tx)}`),'held');assert.equal((await base.release({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback})).status,'rejected')})
test('disabled controls, missing browser grant and mismatched proof receipt fail before claim',async t=>{for(const kind of ['disabled','grant','receipt'])await t.test(kind,async()=>{const x=seed(),r=repo();if(kind==='disabled')admin('UPDATE tll_customer_private.control SET enabled=false');if(kind==='grant')admin(`DELETE FROM tll_bridge_private.grants WHERE id=${q(x.tx)}`);if(kind==='receipt')admin(`UPDATE tll_customer_private.shopify_proofs SET receipt_id=${q(randomUUID())} WHERE transaction_id=${q(x.tx)}`);assert.equal((await r.claim({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID()})).status,'rejected');assert.equal(admin('SELECT count(*) FROM tll_bridge_private.finalizations'),'0')})})
test('disabling any control after reconciliation blocks release without deleting evidence',async()=>{const x=seed(),r=repo(),c=await r.claim({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback,operationId:randomUUID()});assert.equal(c.status,'claimed');assert.equal(await r.finish(finish(x,c)),true);admin('UPDATE tll_bridge_private.control SET enabled=false');assert.equal((await r.release({transactionId:x.tx,browserHash:x.browser,callbackUrl:x.callback})).status,'rejected');assert.equal(admin(`SELECT state||':'||(session_material IS NOT NULL) FROM tll_bridge_private.finalizations WHERE transaction_id=${q(x.tx)}`),'reconciled:true')})
test('runtime and browser roles have function-only authority and cannot read ciphertext',()=>{reset();for(const role of ['anon','authenticated','service_role','tll_fr5_bridge_executor'])assert.throws(()=>admin(`SET SESSION AUTHORIZATION ${role}; SELECT * FROM tll_bridge_private.finalizations;`),/Synthetic final SQL failed/);assert.equal(admin("SELECT has_function_privilege('tll_fr5_bridge_executor','tll_bridge_private.final_repository(text,jsonb)','EXECUTE')::text||':'||has_function_privilege('service_role','tll_bridge_private.final_repository(text,jsonb)','EXECUTE')::text"),'true:false')})
