import {spawn,execFileSync} from 'node:child_process'
import {randomBytes} from 'node:crypto'
export const C='tll-stage0-postgres',D='tll_final_reconciliation_v5',M='tll_final_migrator_v5',BRIDGE='tll_fr5_bridge_executor'
const opts={encoding:'utf8',stdio:['pipe','pipe','pipe'],maxBuffer:16*1024*1024,timeout:15000},clients=new Set()
export function admin(input){try{return execFileSync('docker',['exec','-i',C,'psql','-XqAt','-U','postgres','-d',D,'-v','ON_ERROR_STOP=1'],{...opts,input}).trim()}catch{throw Error('Synthetic final SQL failed')}}
export function assertFixture(){if(admin("SELECT current_database()||':'||coalesce(shobj_description(oid,'pg_database'),'') FROM pg_database WHERE datname=current_database()")!==D+':tll-final-reconciliation-synthetic-v5')throw Error('Wrong final fixture')}
const lit=v=>typeof v==='string'?"'"+v.replaceAll("'","''")+"'":v===null?'NULL':Number.isFinite(v)?String(v):(()=>{throw Error('binding')})()
class Client{constructor(role){this.p=spawn('docker',['exec','-i',C,'psql','-XqAt','-U','postgres','-d',D,'-v','ON_ERROR_STOP=1'],{stdio:['pipe','pipe','pipe']});this.b='';this.q=null;this.dead=false;clients.add(this);this.closed=new Promise(r=>this.p.once('close',()=>{this.dead=true;clients.delete(this);this.q?.reject(Error('closed'));r()}));this.p.stderr.on('data',()=>{});this.p.stdout.on('data',x=>{this.b+=x;const q=this.q;if(!q)return;const i=this.b.indexOf(q.m+'\n');if(i<0)return;const raw=this.b.slice(0,i).trim();this.b=this.b.slice(i+q.m.length+1);this.q=null;try{q.resolve(raw?{rows:JSON.parse(raw).rows}:{rows:[]})}catch{q.reject(Error('bad result'))}});this.ready=this.query('SET ROLE '+role)}async query(sql,values=[]){if(this.dead||this.q)throw Error('busy');const text=sql.replace(/\$(\d+)/g,(_,n)=>lit(values[+n-1])),stmt=/^SELECT /i.test(text)?`SELECT json_build_object('rows',COALESCE(json_agg(x),'[]'::json)) FROM (${text.replace(/;$/,'')})x;`:text+';',m='tll_'+randomBytes(12).toString('hex');return new Promise((resolve,reject)=>{this.q={m,resolve,reject};this.p.stdin.write(stmt+'\n\\echo '+m+'\n')})}release(){if(!this.dead&&!this.released){this.released=true;this.p.stdin.end('\\q\n')}}}
export function pool(fault){return{async connect(){const c=new Client(BRIDGE);await c.ready;const q=c.query.bind(c);let op;return{async query(sql,v){if(v)op=v[0];const r=await q(sql,v);if(fault?.({sql,op,rows:r.rows}))throw Error('lost ack');return r},release:c.release.bind(c)}}}}
export async function close(){for(const c of clients)c.release();await Promise.all([...clients].map(c=>c.closed))}
