import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

test('staging account activation manifest pins reviewed sources and contains no secret values', () => {
  execFileSync(process.execPath, ['scripts/staging-account-activation-manifest.mjs', '--check'], { stdio: 'pipe' })
  const raw = readFileSync('config/staging-account-activation-manifest.json', 'utf8'), manifest = JSON.parse(raw)
  assert.equal(manifest.schema, 'tll-staging-account-activation/v1')
  assert.deepEqual(manifest.migrations.map(item => item.path.match(/2026091800(1[2-6])_/)[1]), ['12','13','14','15','16'])
  assert.deepEqual(manifest.edge.functions.map(item => item.name), ['tll-broker-token','tll-broker-userinfo'])
  assert.equal(Object.keys(manifest.runtime.databaseIdentities).length, 5)
  assert.equal(new Set(Object.values(manifest.runtime.databaseIdentities).map(item => item.login)).size, 5)
  assert.equal(manifest.target.productionProjectRefExcluded, 'wrhgscovsgsudtedbljr')
  assert.equal(manifest.runtime.reviewedPreview.stableOrigin, manifest.provider.reviewedPreviewOrigin)
  assert.equal(manifest.runtime.reviewedPreview.branch, 'codex/tll-integration')
  assert.deepEqual(manifest.runtime.reviewedPreview.originConfiguration, ['TLL_STAGING_CUSTOMER_ORIGIN', 'TLL_STAGING_CART_ORIGIN'])
  assert.deepEqual(manifest.runtime.reviewedPreview.immutableDeploymentEvidence.requiredForEachPhase, ['disabled', 'enabled'])
  assert.deepEqual(manifest.runtime.reviewedPreview.immutableDeploymentEvidence.requiredFields,
    ['deploymentId', 'immutableUrl', 'sourceCommit', 'manifestSha256'])
  assert.equal(manifest.runtime.reviewedPreview.immutableDeploymentEvidence.aliasMustResolveToRecordedDeployment, true)
  assert.equal('previewOriginPattern' in manifest.provider, false)
  assert.equal(manifest.preflight.queryId, 'tll-staging-readonly-preflight/v1')
  assert.equal(manifest.preflight.maximumRequests, 1)
  assert.equal(manifest.preflight.productionExcluded, true)
  assert.equal(manifest.preflight.actualPostgresAcceptanceRequired, true)
  assert.equal(manifest.disabledMigrationInstall.installId, 'tll-staging-disabled-migrations-012-016/v1')
  assert.match(manifest.disabledMigrationInstall.transactionSha256, /^[a-f0-9]{64}$/)
  assert.equal(manifest.disabledMigrationInstall.nativeAccessApproved, false)
  assert.equal(manifest.disabledMigrationInstall.maximumRequests, 1)
  assert.equal(manifest.disabledMigrationInstall.executionPolicy, 'HOLD_UNTIL_ALL_REVIEWED_GATES_PASS')
  assert.equal(manifest.disabledMigrationInstall.dispatchJournal.exclusiveClaimRequired, true)
  assert.equal(manifest.disabledMigrationInstall.dispatchJournal.noRetryAfterDispatch, true)
  assert.equal(manifest.disabledMigrationInstall.dispatchJournal.uncertainState, 'RECONCILIATION_REQUIRED')
  assert.equal(manifest.disabledMigrationInstall.actualPostgresAcceptanceRequired, true)
  assert.deepEqual(manifest.recovery.requiredInstalledMigrations, ['012','013','014','015','016'])
  assert.deepEqual(manifest.recovery.activationWindow, { generation: 6, windowId: '83888906-23fa-4653-a886-fe2733ed76a0' })
  assert.deepEqual(manifest.recovery.disablesControls, ['customer','cart','broker','provisional','bridge'])
  assert.equal(manifest.recovery.retiresRuntimeLogins.length, 5)
  assert.equal(manifest.recovery.preservesEvidenceRows, true)
  assert.equal(manifest.recovery.postCommitZeroSessionProof, true)
  assert.deepEqual(manifest.recovery.requiresExistingOperatorAuthority, ['CREATEROLE','pg_read_all_data','pg_read_all_stats'])
  assert.equal(manifest.recovery.requiredBeforeCredentialProvisioning, true)
  assert.equal(manifest.recovery.maximumCredentialWindowMinutes, 60)
  assert.deepEqual(manifest.recovery.activationPhases, ['deploy_edge_disabled','stage_secrets_flags_disabled','install_generation_6_once','verify_restricted_connections','verify_provider_readback','deploy_immutable_preview_disabled','enable_database_controls','enable_edge_then_server_then_public','run_one_no-purchase_journey','retire_generation_6'])
  assert.ok(manifest.recovery.recoveryTriggers.includes('uncertain_database_acknowledgement'))
  assert.ok(manifest.recovery.recoveryTriggers.includes('activation_interrupted'))
  assert.ok(manifest.gates.indexOf('verify_post_016_recovery_package_before_credentials')
    < manifest.gates.indexOf('install_distinct_runtime_credentials_and_secret_configuration'))
  assert.ok(manifest.sourceTree.fileCount > 40); assert.match(manifest.sourceTree.sha256, /^[a-f0-9]{64}$/)
  assert.ok(manifest.gates.indexOf('enable_database_controls_then_edge_then_server_feature_flags')
    > manifest.gates.indexOf('run_unavailable_route_and_cross_role_denial_checks'))
  assert.ok(manifest.runtime.vercelSecrets.every(value => /^[A-Z][A-Z0-9_]+$/.test(value)))
  assert.equal(JSON.stringify(manifest).includes('secretValue'), false)
  assert.equal(JSON.stringify(manifest).includes('passwordValue'), false)
  assert.equal(JSON.stringify(manifest).includes('keyHexValue'), false)
  for (const pin of [...manifest.migrations,...manifest.edge.sources,...manifest.runtime.sources,...manifest.preflight.sources,...manifest.disabledMigrationInstall.sources,...manifest.recovery.sources]) assert.match(pin.sha256,/^[a-f0-9]{64}$/)

  const classified = new Set([...manifest.runtime.vercelSecrets,...manifest.runtime.vercelConfiguration])
  const runtimeSource = ['lib/server/staging-customer.ts','lib/commerce/staging-cart-server.ts','app/auth/customer/logout/route.ts']
    .map(path => readFileSync(path,'utf8')).join('\n')
  const runtimeKeys = [...runtimeSource.matchAll(/(?:process\.env\.)?((?:NEXT_PUBLIC_)?TLL_STAGING_[A-Z0-9_]+|NEXT_PUBLIC_SUPABASE_[A-Z0-9_]+)/g)].map(match => match[1])
  assert.deepEqual([...new Set(runtimeKeys)].filter(key => !classified.has(key)), [])
  const edgeClassified = new Set([...manifest.edge.requiredSecrets,manifest.edge.enableLast,'SUPABASE_URL'])
  const edgeSource = readFileSync('lib/identity/customer-subject-broker-edge.ts','utf8')
  const edgeKeys = [...edgeSource.matchAll(/get\('([A-Z][A-Z0-9_]+)'\)/g)].map(match => match[1])
  assert.deepEqual([...new Set(edgeKeys)].filter(key => !edgeClassified.has(key)), [])
})
