import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import * as nativeFs from 'node:fs'
import { mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { ENDPOINT, FIXED_QUERY, INSTALL_ID, KEYCHAIN_ACCOUNT, KEYCHAIN_SERVICE, NATIVE_ACCESS_APPROVED, PROJECT_REF, PRODUCTION_PROJECT_REF, consumeNativeTokenOutput, createDispatchJournal, dispatchWithJournal, runInstallOnce, validateResult } from '../scripts/staging-disabled-migrations-012-016.mjs'
import { MIGRATIONS, buildPackage } from '../scripts/staging-disabled-migrations-012-016.prepare.mjs'

const receipt = { installId: INSTALL_ID, projectRef: PROJECT_REF, status: 'PASS', migrationCount: 5, controlsDisabled: true, objectsPresent: true }
const manifest = JSON.parse(readFileSync('config/staging-disabled-migrations-012-016.json', 'utf8'))
const temporaryJournal = () => {
  const directory = mkdtempSync(join(tmpdir(), 'tll-disabled-migrations-'))
  const path = join(directory, 'dispatch.json')
  return { directory, path, journal: createDispatchJournal({ path, makeRunId: () => 'test-run-0001' }) }
}

test('migration package is fixed to staging, disabled, and has no caller dispatch surface', () => {
  assert.equal(NATIVE_ACCESS_APPROVED, false)
  assert.equal(PROJECT_REF, 'qdmvngjwkcsilzmqksme'); assert.equal(PRODUCTION_PROJECT_REF, 'wrhgscovsgsudtedbljr')
  assert.deepEqual(ENDPOINT, { hostname: 'api.supabase.com', path: '/v1/projects/qdmvngjwkcsilzmqksme/database/query', method: 'POST' })
  assert.equal(KEYCHAIN_SERVICE, 'Supabase CLI'); assert.equal(KEYCHAIN_ACCOUNT, 'supabase')
  const source = readFileSync('scripts/staging-disabled-migrations-012-016.mjs', 'utf8')
  assert.match(source, /export const NATIVE_ACCESS_APPROVED = false/)
  assert.doesNotMatch(source, /process\.argv\[[^]]+\].*(?:query|url|header|sql)/i)
  assert.match(source, /agent:\s*false/); assert.match(source, /maxRequests/) // source is reviewed alongside manifest below
  assert.match(FIXED_QUERY, /^-- GENERATED by scripts\/staging-disabled-migrations-012-016\.prepare\.mjs/m)
  const result = execFileSync(process.execPath, ['scripts/staging-disabled-migrations-012-016.mjs'], { encoding: 'utf8' })
  assert.deepEqual(JSON.parse(result), { status: 'NATIVE_ACCESS_DISABLED', target: PROJECT_REF, installId: INSTALL_ID })
})

test('the generated transaction pins every source and only removes their outer wrappers', () => {
  execFileSync(process.execPath, ['scripts/staging-disabled-migrations-012-016.prepare.mjs'], { stdio: 'pipe' })
  const pkg = buildPackage(), artifact = readFileSync('config/staging-disabled-migrations-012-016.sql', 'utf8')
  const manifest = JSON.parse(readFileSync('config/staging-disabled-migrations-012-016.json', 'utf8'))
  assert.equal(artifact, pkg.sql); assert.equal(manifest.transactionSha256, pkg.sqlSha256)
  assert.equal(manifest.nativeAccessApproved, false); assert.equal(manifest.sourcePinsForTransport.length, 2)
  execFileSync(process.execPath, ['scripts/staging-disabled-migrations-012-016.prepare.mjs', '--check'], { stdio: 'pipe' })
  assert.equal(pkg.sources.length, 5); assert.deepEqual(pkg.sources.map(source => source.version), MIGRATIONS.map(([version]) => version))
  assert.equal((artifact.match(/^BEGIN;$/gm) || []).length, 1); assert.equal((artifact.match(/^COMMIT;$/gm) || []).length, 1)
  assert.equal((artifact.match(/INSERT INTO tll_staging_private\.applied_migrations/g) || []).length, 1)
  for (const source of pkg.sources) {
    assert.match(artifact, new RegExp(source.sha256)); assert.match(artifact, new RegExp(source.version))
  }
  assert.match(artifact, /Exact 002--011 predecessor ledger required/)
  assert.match(artifact, /All controls must remain disabled/)
  assert.match(artifact, /Expected empty migration destination required/)
  assert.match(artifact, /Exact reviewed ADMIN-only owner authority required/)
  assert.match(artifact, /production is excluded/)
  assert.match(artifact, /tll_disabled_migration_postflight/)
})

test('only the redacted postflight receipt is accepted', () => {
  const result = validateResult([{ tll_disabled_migration_postflight: receipt }])
  assert.deepEqual(Object.keys(result).sort(), ['installId', 'migrationCount', 'status', 'target', 'transactionSha256'])
  assert.equal(result.status, 'PASS')
  assert.throws(() => validateResult([{ tll_disabled_migration_postflight: { ...receipt, controlsDisabled: false } }]))
  assert.throws(() => validateResult([{ tll_disabled_migration_postflight: { ...receipt, migrationCount: 4 } }]))
  assert.throws(() => validateResult([{ tll_disabled_migration_postflight: { ...receipt, rawRows: [] } }]))
})

test('disabled run cannot read Keychain or make any management request', async () => {
  let reads = 0, requests = 0
  const result = await runInstallOnce({ readToken: () => { reads += 1; return 'unreachable' }, post: async () => { requests += 1 }, now: () => 1 })
  assert.deepEqual(result, { status: 'NATIVE_ACCESS_DISABLED', target: PROJECT_REF, installId: INSTALL_ID })
  assert.equal(reads, 0); assert.equal(requests, 0)
  const stdout = Buffer.from(`sbp_${'a'.repeat(40)}\n`), stderr = Buffer.from('')
  assert.equal(consumeNativeTokenOutput({ status: 0, stdout, stderr }), `sbp_${'a'.repeat(40)}`)
  assert.ok(stdout.every(byte => byte === 0)); assert.ok(stderr.every(byte => byte === 0))
})

test('the executable distinguishes no-dispatch from an uncertain dispatched outcome without retry', () => {
  const source = readFileSync('scripts/staging-disabled-migrations-012-016.mjs', 'utf8')
  assert.match(source, /status: 'PRE_DISPATCH_UNAVAILABLE'/)
  assert.match(source, /status: 'UNCERTAIN_POST_DISPATCH'/)
  assert.match(source, /READ_ONLY_RECONCILIATION_REQUIRED/)
  assert.match(source, /journal\.recordIntent/)
  assert.match(source, /return dispatchWithJournal\(\{ token, post, manifest, journal, now \}\)/)
})

test('the durable nonsecret intent is fsynced and renamed before the only post', async () => {
  const { directory, path } = temporaryJournal()
  const events = []
  const descriptors = new Map()
  const spyFs = {
    mkdirSync (...args) { events.push('mkdir'); return nativeFs.mkdirSync(...args) },
    openSync (file, ...args) { const fd = nativeFs.openSync(file, ...args); descriptors.set(fd, file); events.push(`open:${file === directory ? 'directory' : 'temporary'}`); return fd },
    writeSync (...args) { events.push('write'); return nativeFs.writeSync(...args) },
    fsyncSync (fd) { events.push(`fsync:${descriptors.get(fd) === directory ? 'directory' : 'temporary'}`); return nativeFs.fsyncSync(fd) },
    closeSync (fd) { events.push('close'); return nativeFs.closeSync(fd) },
    renameSync (...args) { events.push('rename'); return nativeFs.renameSync(...args) },
    readFileSync: nativeFs.readFileSync,
  }
  const journal = createDispatchJournal({ path, fileSystem: spyFs, makeRunId: () => 'test-run-0001' })
  try {
    const result = await dispatchWithJournal({ token: 'opaque', manifest, journal, now: () => 0, post: async () => { events.push('post'); return validateResult([{ tll_disabled_migration_postflight: receipt }]) } })
    assert.equal(result.status, 'PASS')
    assert.ok(events.indexOf('rename') < events.indexOf('post'))
    assert.ok(events.indexOf('fsync:temporary') < events.indexOf('rename'))
    assert.ok(events.lastIndexOf('fsync:directory') > events.lastIndexOf('rename'))
    const record = JSON.parse(readFileSync(path, 'utf8'))
    assert.equal(record.state, 'RECEIPT_VALIDATED'); assert.equal(record.target, PROJECT_REF)
    assert.equal(record.transactionSha256, manifest.transactionSha256); assert.equal(record.sourcePinSha256.length, 7)
    assert.match(record.receiptSha256, /^[a-f0-9]{64}$/)
    assert.doesNotMatch(JSON.stringify(record), /opaque|SELECT|Bearer|tll_disabled_migration_postflight/)
    assert.deepEqual(readdirSync(directory).sort(), ['dispatch.json'])
  } finally { rmSync(directory, { recursive: true, force: true }) }
})

test('lost acknowledgements, malformed receipts and timeouts preserve the intent and demand reconciliation', async () => {
  for (const post of [async () => { throw new Error('timeout') }, async () => ({ status: 'PASS' }), async () => { throw new Error('lost acknowledgement') }]) {
    const { directory, path, journal } = temporaryJournal()
    try {
      const result = await dispatchWithJournal({ token: 'opaque', manifest, journal, now: () => 0, post })
      assert.equal(result.status, 'UNCERTAIN_POST_DISPATCH')
      assert.equal(JSON.parse(readFileSync(path, 'utf8')).state, 'RECONCILIATION_REQUIRED')
    } finally { rmSync(directory, { recursive: true, force: true }) }
  }
})

test('a journal write failure proves no dispatch and a recorded uncertainty blocks every retry', async () => {
  let requests = 0
  const unavailableJournal = { refusePriorDispatch: () => null, recordIntent: () => { throw new Error('disk unavailable') } }
  const noDispatch = await dispatchWithJournal({ token: 'opaque', manifest, journal: unavailableJournal, now: () => 0, post: async () => { requests += 1; return receipt } })
  assert.equal(noDispatch.status, 'PRE_DISPATCH_UNAVAILABLE'); assert.equal(requests, 0)

  const { directory, journal } = temporaryJournal()
  try {
    const first = await dispatchWithJournal({ token: 'opaque', manifest, journal, now: () => 0, post: async () => { requests += 1; throw new Error('timeout') } })
    const second = await dispatchWithJournal({ token: 'opaque', manifest, journal, now: () => 0, post: async () => { requests += 1; return receipt } })
    assert.equal(first.status, 'UNCERTAIN_POST_DISPATCH'); assert.equal(second.status, 'RECONCILIATION_REQUIRED'); assert.equal(requests, 1)
  } finally { rmSync(directory, { recursive: true, force: true }) }
})

test('actual PostgreSQL acceptance is isolated and executes the generated package', () => {
  const source = readFileSync('tests/staging-disabled-migrations-012-016-actual.mjs', 'utf8')
  assert.match(source, /readFileSync\(new URL\('\.\.\/config\/staging-disabled-migrations-012-016\.sql'/)
  assert.match(source, /--network', 'none'/)
  assert.match(source, /Remote Docker refused/)
  assert.match(source, /all five additions committed atomically/)
  assert.match(source, /late failure rollback/)
  assert.match(source, /replay refusal/)
  assert.doesNotMatch(source, /https?:\/\//)
})
