import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { ENDPOINT, FIXED_QUERY, INSTALL_ID, KEYCHAIN_ACCOUNT, KEYCHAIN_SERVICE, NATIVE_ACCESS_APPROVED, PROJECT_REF, PRODUCTION_PROJECT_REF, consumeNativeTokenOutput, runInstallOnce, validateResult } from '../scripts/staging-disabled-migrations-012-016.mjs'
import { MIGRATIONS, buildPackage } from '../scripts/staging-disabled-migrations-012-016.prepare.mjs'

const receipt = { installId: INSTALL_ID, projectRef: PROJECT_REF, status: 'PASS', migrationCount: 5, controlsDisabled: true, objectsPresent: true }

test('migration package is fixed to staging, disabled, and has no caller dispatch surface', () => {
  assert.equal(NATIVE_ACCESS_APPROVED, false)
  assert.equal(PROJECT_REF, 'qdmvngjwkcsilzmqksme'); assert.equal(PRODUCTION_PROJECT_REF, 'wrhgscovsgsudtedbljr')
  assert.deepEqual(ENDPOINT, { hostname: 'api.supabase.com', path: '/v1/projects/qdmvngjwkcsilzmqksme/database/query', method: 'POST' })
  assert.equal(KEYCHAIN_SERVICE, 'Supabase CLI'); assert.equal(KEYCHAIN_ACCOUNT, 'supabase')
  const source = readFileSync('scripts/staging-disabled-migrations-012-016.mjs', 'utf8')
  assert.match(source, /export const NATIVE_ACCESS_APPROVED = false/)
  assert.doesNotMatch(source, /process\.argv\[[^]]+\].*(?:query|url|header|sql)/i)
  assert.match(source, /agent:\s*false/); assert.match(source, /maxRequests/) // source is reviewed alongside manifest below
  assert.match(FIXED_QUERY, /^-- GENERATED by scripts\/staging-disabled-migrations-012-016\.prepare\.mjs/m)
  const result = execFileSync(process.execPath, ['scripts/staging-disabled-migrations-012-016.mjs'], { encoding: 'utf8' })
  assert.deepEqual(JSON.parse(result), { status: 'NATIVE_ACCESS_DISABLED', target: PROJECT_REF, installId: INSTALL_ID })
})

test('the generated transaction pins every source and only removes their outer wrappers', () => {
  execFileSync(process.execPath, ['scripts/staging-disabled-migrations-012-016.prepare.mjs'], { stdio: 'pipe' })
  const pkg = buildPackage(), artifact = readFileSync('config/staging-disabled-migrations-012-016.sql', 'utf8')
  const manifest = JSON.parse(readFileSync('config/staging-disabled-migrations-012-016.json', 'utf8'))
  assert.equal(artifact, pkg.sql); assert.equal(manifest.transactionSha256, pkg.sqlSha256)
  assert.equal(manifest.nativeAccessApproved, false); assert.equal(manifest.sourcePinsForTransport.length, 2)
  execFileSync(process.execPath, ['scripts/staging-disabled-migrations-012-016.prepare.mjs', '--check'], { stdio: 'pipe' })
  assert.equal(pkg.sources.length, 5); assert.deepEqual(pkg.sources.map(source => source.version), MIGRATIONS.map(([version]) => version))
  assert.equal((artifact.match(/^BEGIN;$/gm) || []).length, 1); assert.equal((artifact.match(/^COMMIT;$/gm) || []).length, 1)
  assert.equal((artifact.match(/INSERT INTO tll_staging_private\.applied_migrations/g) || []).length, 1)
  for (const source of pkg.sources) {
    assert.match(artifact, new RegExp(source.sha256)); assert.match(artifact, new RegExp(source.version))
  }
  assert.match(artifact, /Exact 002--011 predecessor ledger required/)
  assert.match(artifact, /All controls must remain disabled/)
  assert.match(artifact, /Expected empty migration destination required/)
  assert.match(artifact, /Exact reviewed ADMIN-only owner authority required/)
  assert.match(artifact, /production is excluded/)
  assert.match(artifact, /tll_disabled_migration_postflight/)
})

test('only the redacted postflight receipt is accepted', () => {
  const result = validateResult([{ tll_disabled_migration_postflight: receipt }])
  assert.deepEqual(Object.keys(result).sort(), ['installId', 'migrationCount', 'status', 'target', 'transactionSha256'])
  assert.equal(result.status, 'PASS')
  assert.throws(() => validateResult([{ tll_disabled_migration_postflight: { ...receipt, controlsDisabled: false } }]))
  assert.throws(() => validateResult([{ tll_disabled_migration_postflight: { ...receipt, migrationCount: 4 } }]))
  assert.throws(() => validateResult([{ tll_disabled_migration_postflight: { ...receipt, rawRows: [] } }]))
})

test('disabled run cannot read Keychain or make any management request', async () => {
  let reads = 0, requests = 0
  const result = await runInstallOnce({ readToken: () => { reads += 1; return 'unreachable' }, post: async () => { requests += 1 }, now: () => 1 })
  assert.deepEqual(result, { status: 'NATIVE_ACCESS_DISABLED', target: PROJECT_REF, installId: INSTALL_ID })
  assert.equal(reads, 0); assert.equal(requests, 0)
  const stdout = Buffer.from(`sbp_${'a'.repeat(40)}\n`), stderr = Buffer.from('')
  assert.equal(consumeNativeTokenOutput({ status: 0, stdout, stderr }), `sbp_${'a'.repeat(40)}`)
  assert.ok(stdout.every(byte => byte === 0)); assert.ok(stderr.every(byte => byte === 0))
})

test('the executable distinguishes no-dispatch from an uncertain dispatched outcome without retry', () => {
  const source = readFileSync('scripts/staging-disabled-migrations-012-016.mjs', 'utf8')
  assert.match(source, /status: 'PRE_DISPATCH_UNAVAILABLE'/)
  assert.match(source, /status: 'UNCERTAIN_POST_DISPATCH'/)
  assert.match(source, /READ_ONLY_RECONCILIATION_REQUIRED/)
  assert.match(source, /try \{ return await post\(token, now\(\) \+ MAX_AGE_MS\) \} catch/)
})
