import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

test('staging account activation manifest pins reviewed sources and contains no secret values', () => {
  execFileSync(process.execPath, ['scripts/staging-account-activation-manifest.mjs', '--check'], { stdio: 'pipe' })
  const raw = readFileSync('config/staging-account-activation-manifest.json', 'utf8'), manifest = JSON.parse(raw)
  assert.equal(manifest.schema, 'tll-staging-account-activation/v1')
  assert.deepEqual(manifest.migrations.map(item => item.path.match(/2026091800(1[2-6])_/)[1]), ['12','13','14','15','16'])
  assert.deepEqual(manifest.edge.functions.map(item => item.name), ['tll-broker-token','tll-broker-userinfo'])
  assert.equal(Object.keys(manifest.runtime.databaseIdentities).length, 5)
  assert.equal(new Set(Object.values(manifest.runtime.databaseIdentities).map(item => item.login)).size, 5)
  assert.equal(manifest.target.productionProjectRefExcluded, 'wrhgscovsgsudtedbljr')
  assert.equal(manifest.stageSafety.policy, 'tll-project-stage-gate-policy/v1')
  assert.equal(manifest.stageSafety.ordinaryTestsRequireAllNativeGatesDisabled, true)
  assert.equal(manifest.stageSafety.ordinaryTestsMayInvokeNativeLaunchers, false)
  assert.equal(manifest.stageSafety.ordinaryTransportModulesMayDefineLiveLaunchers, false)
  assert.equal(manifest.stageSafety.ordinaryTestsMayRewriteGeneratedArtifacts, false)
  assert.equal(manifest.stageSafety.independentReviewRequiredBeforeArming, true)
  assert.equal(manifest.stageSafety.liveExecutionRequiresPhaseJournal, true)
  assert.equal(manifest.stageSafety.generation10ReplayPermitted, false)
  assert.equal(manifest.stageSafety.generation11Armed, false)
  assert.equal(manifest.stageSafety.successorHeldPendingBoundaryReview, true)
  assert.equal(manifest.runtime.reviewedPreview.stableOrigin, manifest.provider.reviewedPreviewOrigin)
  assert.equal(manifest.runtime.reviewedPreview.branch, 'codex/tll-integration')
  assert.deepEqual(manifest.runtime.reviewedPreview.originConfiguration, ['TLL_STAGING_CUSTOMER_ORIGIN', 'TLL_STAGING_CART_ORIGIN'])
  assert.deepEqual(manifest.runtime.reviewedPreview.immutableDeploymentEvidence.requiredForEachPhase, ['disabled', 'enabled'])
  assert.deepEqual(manifest.runtime.reviewedPreview.immutableDeploymentEvidence.requiredFields,
    ['deploymentId', 'immutableUrl', 'sourceCommit', 'manifestSha256'])
  assert.equal(manifest.runtime.reviewedPreview.immutableDeploymentEvidence.aliasMustResolveToRecordedDeployment, true)
  assert.equal('previewOriginPattern' in manifest.provider, false)
  assert.equal(manifest.preflight.queryId, 'tll-staging-readonly-preflight/v1')
  assert.equal(manifest.preflight.maximumRequests, 1)
  assert.equal(manifest.preflight.productionExcluded, true)
  assert.equal(manifest.preflight.actualPostgresAcceptanceRequired, true)
  assert.equal(manifest.disabledMigrationInstall.installId, 'tll-staging-disabled-migrations-012-016/v1')
  assert.match(manifest.disabledMigrationInstall.transactionSha256, /^[a-f0-9]{64}$/)
  assert.equal(manifest.disabledMigrationInstall.nativeAccessApproved, false)
  assert.equal(manifest.disabledMigrationInstall.maximumRequests, 1)
  assert.equal(manifest.disabledMigrationInstall.executionPolicy, 'HOLD_UNTIL_ALL_REVIEWED_GATES_PASS')
  assert.equal(manifest.disabledMigrationInstall.dispatchJournal.exclusiveClaimRequired, true)
  assert.equal(manifest.disabledMigrationInstall.dispatchJournal.noRetryAfterDispatch, true)
  assert.equal(manifest.disabledMigrationInstall.dispatchJournal.uncertainState, 'RECONCILIATION_REQUIRED')
  assert.equal(manifest.disabledMigrationInstall.actualPostgresAcceptanceRequired, true)
  assert.deepEqual(manifest.recovery.requiredInstalledMigrations, ['012','013','014','015','016'])
  assert.deepEqual(manifest.recovery.activationWindow, { generation: 6, windowId: '83888906-23fa-4653-a886-fe2733ed76a0' })
  assert.deepEqual(manifest.recovery.disablesControls, ['customer','cart','broker','provisional','bridge'])
  assert.equal(manifest.recovery.retiresRuntimeLogins.length, 5)
  assert.equal(manifest.recovery.preservesEvidenceRows, true)
  assert.equal(manifest.recovery.postCommitZeroSessionProof, true)
  assert.deepEqual(manifest.recovery.requiresExistingOperatorAuthority, ['CREATEROLE','pg_read_all_data','pg_read_all_stats'])
  assert.equal(manifest.recovery.requiredBeforeCredentialProvisioning, true)
  assert.equal(manifest.recovery.maximumCredentialWindowMinutes, 60)
  assert.deepEqual(manifest.recovery.activationPhases, ['deploy_edge_disabled','stage_secrets_flags_disabled','install_generation_6_once','verify_restricted_connections','verify_provider_readback','deploy_immutable_preview_disabled','enable_database_controls','enable_edge_then_server_then_public','run_one_no-purchase_journey','retire_generation_6'])
  assert.ok(manifest.recovery.recoveryTriggers.includes('uncertain_database_acknowledgement'))
  assert.ok(manifest.recovery.recoveryTriggers.includes('activation_interrupted'))
  assert.equal(manifest.generation6Credentials.packageId, 'tll-staging-generation-6-credentials/v1')
  assert.equal(manifest.generation6Credentials.target, 'qdmvngjwkcsilzmqksme')
  assert.deepEqual(manifest.generation6Credentials.predecessor, { generation: 5, windowId: 'e8aeb142-d2f8-4a58-b0a5-8931d90a6952', expiresAt: '2026-09-18T14:24:02.000Z' })
  assert.equal(manifest.generation6Credentials.maximumWindowMinutes, 60)
  assert.equal(manifest.generation6Credentials.secretBearingSqlMustRemainInMemory, true)
  assert.equal(manifest.generation6Credentials.exclusiveNonsecretJournal, true)
  assert.equal(manifest.generation6Credentials.nativeTransportEnabled, false)
  assert.equal(manifest.generation7Successor.packageId, 'tll-staging-generation-7-credentials/v1')
  assert.equal(manifest.generation7Successor.generation, 7)
  assert.equal(manifest.generation7Successor.predecessor.generation, 6)
  assert.equal(manifest.generation7Successor.predecessor.journalState, 'RECONCILIATION_REQUIRED')
  assert.equal(manifest.generation7Successor.predecessor.recoveryVerified, true)
  assert.equal(manifest.generation7Successor.poolerConvergenceWaitMs, 16000)
  assert.equal(manifest.generation7Successor.freshPoolRetryAttempts, 1)
  assert.equal(manifest.generation7Successor.thirdAttemptPermitted, false)
  assert.equal(manifest.generation7Successor.nativeTransportEnabled, false)
  assert.equal(manifest.generation7Successor.status, 'ENTRY_BASELINE_RECONCILIATION_REQUIRED')
  assert.equal(manifest.generation8Successor.packageId, 'tll-staging-generation-8-credentials/v1')
  assert.equal(manifest.generation8Successor.generation, 8)
  assert.equal(manifest.generation8Successor.predecessor.generation, 6)
  assert.equal(manifest.generation8Successor.supersedesAttempt.generation, 7)
  assert.equal(manifest.generation8Successor.supersedesAttempt.journalExists, false)
  assert.equal(manifest.generation8Successor.predecessorMarkerComparison, 'PARSED_JSON_SEMANTICS')
  assert.equal(manifest.generation8Successor.freshPoolRetryAttempts, 1)
  assert.equal(manifest.generation8Successor.thirdAttemptPermitted, false)
  assert.equal(manifest.generation8Successor.nativeTransportEnabled, false)
  assert.equal(manifest.generation8Successor.status, 'ENTRY_BASELINE_RECONCILIATION_REQUIRED')
  assert.equal(manifest.generation9Successor.packageId, 'tll-staging-generation-9-credentials/v1')
  assert.equal(manifest.generation9Successor.generation, 9)
  assert.equal(manifest.generation9Successor.predecessor.validUntil, manifest.generation9Successor.predecessor.expiresAt)
  assert.deepEqual(manifest.generation9Successor.supersedesAttempts.map(item=>item.generation), [7,8])
  assert.ok(manifest.generation9Successor.supersedesAttempts.every(item=>item.journalExists===false))
  assert.equal(manifest.generation9Successor.predecessorMarkerComparison, 'PARSED_JSON_SEMANTICS')
  assert.equal(manifest.generation9Successor.predecessorValidUntilComparison, 'EXACT_PREDECESSOR_EXPIRY')
  assert.equal(manifest.generation9Successor.freshPoolRetryAttempts, 1)
  assert.equal(manifest.generation9Successor.thirdAttemptPermitted, false)
  assert.equal(manifest.generation9Successor.nativeTransportEnabled, false)
  assert.equal(manifest.generation9Successor.status, 'CONNECTION_RECOVERED_RECONCILIATION_REQUIRED')
  assert.equal(manifest.generation10Successor.packageId, 'tll-staging-generation-10-credentials/v1')
  assert.equal(manifest.generation10Successor.generation, 10)
  assert.equal(manifest.generation10Successor.predecessor.generation, 9)
  assert.equal(manifest.generation10Successor.predecessor.windowId, '08ceb448-c1e2-4641-85ff-bee536774466')
  assert.equal(manifest.generation10Successor.predecessor.validUntil, manifest.generation10Successor.predecessor.expiresAt)
  assert.equal(manifest.generation10Successor.predecessor.liveReadOnlyConfirmed, true)
  assert.deepEqual(manifest.generation10Successor.supersedesAttempts.map(item=>item.generation), [7,8])
  assert.equal(manifest.generation10Successor.predecessorMarkerComparison, 'PARSED_JSON_SEMANTICS')
  assert.equal(manifest.generation10Successor.predecessorValidUntilComparison, 'EXACT_PREDECESSOR_EXPIRY')
  assert.equal(manifest.generation10Successor.connectionVerifier.usesPinnedSupabaseCa, true)
  assert.equal(manifest.generation10Successor.connectionVerifier.source, 'scripts/staging-supabase-ca.mjs')
  assert.equal(manifest.generation10Successor.recoveryPostcondition.independentProviderZeroReadbackRequired, true)
  assert.equal(manifest.generation10Successor.recoveryPostcondition.verified, true)
  assert.equal(manifest.generation10Successor.recoveryPostcondition.generatedVercelValuesPresent, 0)
  assert.equal(manifest.generation10Successor.recoveryPostcondition.generatedSupabaseSecretsPresent, 0)
  assert.equal(manifest.generation10Successor.execution.outcome, 'RECOVERY_VERIFIED_AFTER_INTERRUPTED_NATIVE_TEST')
  assert.equal(manifest.generation10Successor.execution.journalState, 'INTENT_RECORDED')
  assert.equal(manifest.generation10Successor.execution.journalLocksReplay, true)
  assert.equal(manifest.generation10Successor.execution.replayPermitted, false)
  assert.equal(manifest.generation10Successor.execution.connectionJourneyCompleted, false)
  assert.equal(manifest.generation10Successor.nativeTransportEnabled, false)
  assert.equal(manifest.generation10Successor.status, 'INTERRUPTED_RECOVERED_INTENT_LOCKED_NO_REPLAY')
  assert.equal(manifest.generation11Successor.packageId, 'tll-staging-generation-11-credentials/v1')
  assert.equal(manifest.generation11Successor.generation, 11)
  assert.equal(manifest.generation11Successor.windowId, '56ff2757-3e34-4cf0-a1dc-40999a713874')
  assert.equal(manifest.generation11Successor.predecessor.generation, 10)
  assert.equal(manifest.generation11Successor.predecessor.windowId, '04e1b5da-b3e1-430b-8247-caf1d46faa5a')
  assert.equal(manifest.generation11Successor.predecessor.expiresAt, '2026-09-20T21:08:17.000Z')
  assert.equal(manifest.generation11Successor.predecessor.validUntil, manifest.generation11Successor.predecessor.expiresAt)
  assert.equal(manifest.generation11Successor.predecessor.journalState, 'INTENT_RECORDED')
  assert.equal(manifest.generation11Successor.predecessor.replayPermitted, false)
  assert.equal(manifest.generation11Successor.liveLauncher.path, 'scripts/staging-generation-11-live-launcher.mjs')
  assert.equal(manifest.generation11Successor.liveLauncher.phaseJournal, 'scripts/staging-window-phase-journal.mjs')
  assert.equal(manifest.generation11Successor.liveLauncher.ordinaryTestsMayImportOrInvoke, false)
  assert.equal(manifest.generation11Successor.nativeTransportEnabled, false)
  assert.equal(manifest.generation11Successor.status, 'DISABLED_SUCCESSOR_PENDING_ARMING_REVIEW')
  assert.ok(manifest.generation11Successor.sources.some(item => item.path === 'scripts/staging-generation-11-live-launcher.mjs'))
  assert.ok(manifest.gates.indexOf('verify_post_016_recovery_package_before_credentials')
    < manifest.gates.indexOf('install_distinct_runtime_credentials_and_secret_configuration'))
  assert.ok(manifest.sourceTree.fileCount > 40); assert.match(manifest.sourceTree.sha256, /^[a-f0-9]{64}$/)
  assert.ok(manifest.gates.indexOf('enable_database_controls_then_edge_then_server_feature_flags')
    > manifest.gates.indexOf('run_unavailable_route_and_cross_role_denial_checks'))
  assert.ok(manifest.runtime.vercelSecrets.every(value => /^[A-Z][A-Z0-9_]+$/.test(value)))
  assert.equal(JSON.stringify(manifest).includes('secretValue'), false)
  assert.equal(JSON.stringify(manifest).includes('passwordValue'), false)
  assert.equal(JSON.stringify(manifest).includes('keyHexValue'), false)
  for (const pin of [...manifest.migrations,...manifest.stageSafety.sources,...manifest.edge.sources,...manifest.runtime.sources,...manifest.preflight.sources,...manifest.disabledMigrationInstall.sources,...manifest.recovery.sources,...manifest.generation6Credentials.sources,...manifest.generation7Successor.sources,...manifest.generation8Successor.sources,...manifest.generation9Successor.sources,...manifest.generation10Successor.sources,...manifest.generation11Successor.sources]) assert.match(pin.sha256,/^[a-f0-9]{64}$/)

  const classified = new Set([...manifest.runtime.vercelSecrets,...manifest.runtime.vercelConfiguration])
  const runtimeSource = ['lib/server/staging-customer.ts','lib/commerce/staging-cart-server.ts','app/auth/customer/logout/route.ts']
    .map(path => readFileSync(path,'utf8')).join('\n')
  const runtimeKeys = [...runtimeSource.matchAll(/(?:process\.env\.)?((?:NEXT_PUBLIC_)?TLL_STAGING_[A-Z0-9_]+|NEXT_PUBLIC_SUPABASE_[A-Z0-9_]+)/g)].map(match => match[1])
  assert.deepEqual([...new Set(runtimeKeys)].filter(key => !classified.has(key)), [])
  const edgeClassified = new Set([...manifest.edge.requiredSecrets,manifest.edge.enableLast,'SUPABASE_URL'])
  const edgeSource = readFileSync('lib/identity/customer-subject-broker-edge.ts','utf8')
  const edgeKeys = [...edgeSource.matchAll(/get\('([A-Z][A-Z0-9_]+)'\)/g)].map(match => match[1])
  assert.deepEqual([...new Set(edgeKeys)].filter(key => !edgeClassified.has(key)), [])
})
