import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

test('generation 19 recovery is derived from exact pinned generation 6 recovery and checks clean',()=>{
  execFileSync(process.execPath,['scripts/staging-generation-19-recovery.mjs','--check'],{stdio:'pipe'})
  for(const path of ['config/staging-generation-19-recovery.sql','config/staging-generation-19-recovery-postcommit.sql']){
    const sql=readFileSync(path,'utf8')
    assert.match(sql,/GENERATED by scripts\/staging-generation-19-recovery\.mjs/)
    assert.match(sql,/generation' IS DISTINCT FROM '19'/);assert.match(sql,/51809dd4-bd4b-44c7-8609-7dd8ca063679/)
    assert.doesNotMatch(sql,/83888906-23fa-4653-a886-fe2733ed76a0/);assert.doesNotMatch(sql,/generation' IS DISTINCT FROM '6'/)
    assert.match(sql,/operator_project_ref='wrhgscovsgsudtedbljr'/)
  }
  const recovery=readFileSync('config/staging-generation-19-recovery.sql','utf8')
  assert.match(recovery,/'generation',19/);assert.match(recovery,/state','retired'/);assert.match(recovery,/NOLOGIN PASSWORD NULL/)
  assert.match(recovery,/rolpassword IS NOT NULL/)
  assert.match(recovery,/Runtime credential survives retirement/)
  assert.match(recovery,/pg_authid WHERE rolname=r AND rolpassword IS NOT NULL/)
  assert.doesNotMatch(recovery,/pg_roles WHERE rolname=r AND \(rolcanlogin OR rolpassword/)
  assert.doesNotMatch(recovery,/Missing retired runtime ADMIN-only operator edge/)
  assert.match(recovery,/Direct private authority survives retirement/)
  assert.match(recovery,/Active Gen19 credential drift shape mismatch/)
  assert.match(recovery,/rolvaliduntil='infinity'::timestamptz/)
  assert.match(recovery,/expiresAt' IS DISTINCT FROM '2026-09-21T11:08:34\.000Z'/)
  const postcommit=readFileSync('config/staging-generation-19-recovery-postcommit.sql','utf8')
  assert.match(postcommit,/rolpassword IS NOT NULL/)
  assert.match(postcommit,/Runtime credential survives retirement/)
  assert.match(postcommit,/pg_authid WHERE rolname=r AND rolpassword IS NOT NULL/)
  assert.doesNotMatch(postcommit,/pg_roles WHERE rolname=r AND \(rolcanlogin OR rolpassword/)
  assert.doesNotMatch(postcommit,/Missing retired runtime ADMIN-only operator edge/)
  assert.match(postcommit,/'operatorEdges',0/)
  assert.match(postcommit,/Direct private authority survives retirement/)
  assert.match(postcommit,/tll_gen19_retirement_postcommit/)
  assert.match(postcommit,/Post-commit controls are not exact-singleton disabled/)
})
