import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

test('post-016 recovery artifact is deterministic, secret-free and retirement-only', () => {
  execFileSync(process.execPath, ['scripts/staging-account-activation-recovery.mjs'], { stdio: 'pipe' })
  execFileSync(process.execPath, ['scripts/staging-account-activation-recovery.mjs', '--check'], { stdio: 'pipe' })
  const sql = readFileSync('config/staging-account-activation-recovery.sql', 'utf8')
  const postCommit = readFileSync('config/staging-account-activation-recovery-postcommit.sql', 'utf8')
  assert.match(sql, /^-- GENERATED by scripts\/staging-account-activation-recovery\.mjs/m)
  assert.match(sql, /after migrations 012--016/)
  assert.match(sql, /qdmvngjwkcsilzmqksme/)
  assert.match(sql, /wrhgscovsgsudtedbljr is excluded/)
  for (const control of ['customer','cart','broker','provisional','bridge']) assert.match(sql, new RegExp(`UPDATE tll_${control}_private\\.control`))
  for (const role of ['customer','cart','broker','provisional','bridge']) {
    assert.match(sql, new RegExp(`tll_${role}_runtime`))
    assert.match(sql, new RegExp(`ALTER ROLE %I NOLOGIN PASSWORD NULL`))
  }
  assert.match(sql, /WHERE state<>'held'/)
  assert.match(sql, /WHERE status NOT IN \('held','cancelled'\)/)
  assert.match(sql, /WHERE phase='working'/)
  assert.match(sql, /WHERE state='claimed'/)
  assert.match(sql, /REVOKE %I FROM %I/)
  assert.match(sql, /GRANT %I TO %I WITH INHERIT TRUE, SET TRUE/)
  assert.match(sql, /REVOKE %I FROM %I GRANTED BY %I/)
  assert.match(sql, /SET LOCAL ROLE tll_customer_owner/)
  assert.match(sql, /Cart recovery requires the original recorded cart table owner/)
  assert.match(postCommit, /pg_read_all_stats/)
  assert.match(postCommit, /20 seconds/)
  assert.match(postCommit, /pg_stat_activity/)
  assert.doesNotMatch(postCommit, /pg_signal_backend|pg_terminate_backend/i)
  assert.doesNotMatch(sql, /\bDROP\s+(ROLE|TABLE|SCHEMA|DATABASE)\b/i)
  assert.doesNotMatch(sql, /\bDELETE\s+FROM\b/i)
  assert.doesNotMatch(sql, /PASSWORD\s+'|secretValue|passwordValue|keyHexValue/i)
})
