import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

test('generation 17 recovery is derived from exact pinned generation 6 recovery and checks clean',()=>{
  execFileSync(process.execPath,['scripts/staging-generation-17-recovery.mjs','--check'],{stdio:'pipe'})
  for(const path of ['config/staging-generation-17-recovery.sql','config/staging-generation-17-recovery-postcommit.sql']){
    const sql=readFileSync(path,'utf8')
    assert.match(sql,/GENERATED by scripts\/staging-generation-17-recovery\.mjs/)
    assert.match(sql,/generation' IS DISTINCT FROM '17'/);assert.match(sql,/5728d807-701a-486b-a8c5-34bf89238275/)
    assert.doesNotMatch(sql,/83888906-23fa-4653-a886-fe2733ed76a0/);assert.doesNotMatch(sql,/generation' IS DISTINCT FROM '6'/)
    assert.doesNotMatch(sql,/313afec9-46d0-41bb-af47-0be277c6fa4f/);assert.doesNotMatch(sql,/generation' IS DISTINCT FROM '16'/)
    assert.match(sql,/operator_project_ref='wrhgscovsgsudtedbljr'/)
  }
  const recovery=readFileSync('config/staging-generation-17-recovery.sql','utf8')
  assert.match(recovery,/'generation',17/);assert.match(recovery,/state','retired'/);assert.match(recovery,/NOLOGIN PASSWORD NULL/)
  assert.doesNotMatch(recovery,/'generation',16/)
})
