import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

test('generation 13 recovery is derived from exact pinned generation 6 recovery and checks clean',()=>{
  execFileSync(process.execPath,['scripts/staging-generation-13-recovery.mjs','--check'],{stdio:'pipe'})
  for(const path of ['config/staging-generation-13-recovery.sql','config/staging-generation-13-recovery-postcommit.sql']){
    const sql=readFileSync(path,'utf8')
    assert.match(sql,/GENERATED by scripts\/staging-generation-13-recovery\.mjs/)
    assert.match(sql,/generation' IS DISTINCT FROM '13'/);assert.match(sql,/866b0e78-7530-493a-8963-e8cf24cf3067/)
    assert.doesNotMatch(sql,/83888906-23fa-4653-a886-fe2733ed76a0/);assert.doesNotMatch(sql,/generation' IS DISTINCT FROM '6'/)
    assert.match(sql,/operator_project_ref='wrhgscovsgsudtedbljr'/)
  }
  const recovery=readFileSync('config/staging-generation-13-recovery.sql','utf8')
  assert.match(recovery,/'generation',13/);assert.match(recovery,/state','retired'/);assert.match(recovery,/NOLOGIN PASSWORD NULL/)
})
