import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

test('generation 15 recovery is derived from exact pinned generation 6 recovery and checks clean',()=>{
  execFileSync(process.execPath,['scripts/staging-generation-15-recovery.mjs','--check'],{stdio:'pipe'})
  for(const path of ['config/staging-generation-15-recovery.sql','config/staging-generation-15-recovery-postcommit.sql']){
    const sql=readFileSync(path,'utf8')
    assert.match(sql,/GENERATED by scripts\/staging-generation-15-recovery\.mjs/)
    assert.match(sql,/generation' IS DISTINCT FROM '15'/);assert.match(sql,/2ec1dcbb-dd43-4a45-893b-3b4dc4140188/)
    assert.doesNotMatch(sql,/83888906-23fa-4653-a886-fe2733ed76a0/);assert.doesNotMatch(sql,/generation' IS DISTINCT FROM '6'/)
    assert.match(sql,/operator_project_ref='wrhgscovsgsudtedbljr'/)
  }
  const recovery=readFileSync('config/staging-generation-15-recovery.sql','utf8')
  assert.match(recovery,/'generation',15/);assert.match(recovery,/state','retired'/);assert.match(recovery,/NOLOGIN PASSWORD NULL/)
})
