import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

test('generation 21 recovery is derived from exact pinned generation 6 recovery and checks clean',()=>{
  execFileSync(process.execPath,['scripts/staging-generation-21-recovery.mjs','--check'],{stdio:'pipe'})
  for(const path of ['config/staging-generation-21-recovery.sql','config/staging-generation-21-recovery-postcommit.sql']){
    const sql=readFileSync(path,'utf8')
    assert.match(sql,/GENERATED by scripts\/staging-generation-21-recovery\.mjs/)
    assert.match(sql,/generation' IS DISTINCT FROM '21'/);assert.match(sql,/a5511645-77af-4fc9-9e4c-f5c8a474d5fa/)
    assert.doesNotMatch(sql,/83888906-23fa-4653-a886-fe2733ed76a0/);assert.doesNotMatch(sql,/generation' IS DISTINCT FROM '6'/)
    assert.match(sql,/operator_project_ref='wrhgscovsgsudtedbljr'/)
  }
  const recovery=readFileSync('config/staging-generation-21-recovery.sql','utf8')
  assert.match(recovery,/'generation',21/);assert.match(recovery,/state','retired'/);assert.match(recovery,/NOLOGIN PASSWORD NULL VALID UNTIL %L',r,'infinity'/)
  assert.match(recovery,/rolpassword IS NOT NULL/)
  assert.match(recovery,/Runtime credential survives retirement/)
  assert.match(recovery,/Missing retired runtime ADMIN-only operator edge/)
  assert.match(recovery,/pg_authid WHERE rolname=r AND rolpassword IS NOT NULL/)
  assert.doesNotMatch(recovery,/pg_roles WHERE rolname=r AND \(rolcanlogin OR rolpassword/)
  assert.match(recovery,/Direct private authority survives retirement/)
  assert.match(recovery,/Active Gen21 credential drift shape mismatch/)
  assert.match(recovery,/'UNSET_REQUIRES_REVIEWED_ARMING_DIFF'='UNSET_REQUIRES_REVIEWED_ARMING_DIFF'/)
  assert.match(recovery,/rolvaliduntil=expires_at/)
  assert.match(recovery,/rolvaliduntil IS DISTINCT FROM 'infinity'::timestamptz/)
  const postcommit=readFileSync('config/staging-generation-21-recovery-postcommit.sql','utf8')
  assert.match(postcommit,/rolpassword IS NOT NULL/)
  assert.match(postcommit,/Runtime credential survives retirement/)
  assert.match(postcommit,/Missing retired runtime ADMIN-only operator edge/)
  assert.match(postcommit,/pg_authid WHERE rolname=r AND rolpassword IS NOT NULL/)
  assert.doesNotMatch(postcommit,/pg_roles WHERE rolname=r AND \(rolcanlogin OR rolpassword/)
  assert.match(postcommit,/'operatorEdges',5/)
  assert.match(postcommit,/'validUntilInfinity',5/)
  assert.match(postcommit,/rolvaliduntil IS DISTINCT FROM 'infinity'::timestamptz/)
  assert.match(postcommit,/Direct private authority survives retirement/)
  assert.match(postcommit,/tll_gen21_retirement_postcommit/)
  assert.match(postcommit,/'generation',21/)
  assert.match(postcommit,/Post-commit controls are not exact-singleton disabled/)
})

test('retirement preflight requires exact active expiry and recovery restores canonical infinity', () => {
  const recovery = readFileSync('config/staging-generation-21-recovery.sql', 'utf8')
  const preflight = readFileSync('config/staging-generation-21-retirement-preflight.sql', 'utf8')
  // Before retirement, recovery and preflight both require the exact finite
  // active expiry. Recovery then resets VALID UNTIL to canonical infinity and
  // both postflight and fresh-session postcommit certify it.
  assert.match(recovery, /rolvaliduntil=expires_at/)
  assert.match(preflight, /rolvaliduntil FROM pg_roles WHERE rolname=r\) IS DISTINCT FROM marker_expiry/)
  assert.match(recovery, /NOLOGIN PASSWORD NULL VALID UNTIL %L',r,'infinity'/)
  assert.match(recovery, /rolvaliduntil IS DISTINCT FROM 'infinity'::timestamptz/)
  assert.doesNotMatch(preflight, /rolvaliduntil.*infinity/s)
  // Neither gate compares the bounded marker expiry to clock time, so cleanup
  // accepts an exact finite matching window both before and just after expiry.
  assert.doesNotMatch(recovery, /expires_at[<>=]+clock_timestamp\(\)/)
  assert.doesNotMatch(preflight, /marker_expiry[<>=]+clock_timestamp\(\)/)
})

test('all Gen21 runtime SQL generators consume the single reviewed Phase-1 expiry source', () => {
  for (const path of [
    'scripts/staging-generation-21-transport.mjs',
    'scripts/staging-generation-21-recovery.mjs',
    'scripts/staging-generation-21-retirement-preflight.mjs',
  ]) assert.match(readFileSync(path, 'utf8'), /ACTIVE_WINDOW_EXPIRES_AT/)
})
