import test from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

test('generation 20 recovery is derived from exact pinned generation 6 recovery and checks clean',()=>{
  execFileSync(process.execPath,['scripts/staging-generation-20-recovery.mjs','--check'],{stdio:'pipe'})
  for(const path of ['config/staging-generation-20-recovery.sql','config/staging-generation-20-recovery-postcommit.sql']){
    const sql=readFileSync(path,'utf8')
    assert.match(sql,/GENERATED by scripts\/staging-generation-20-recovery\.mjs/)
    assert.match(sql,/generation' IS DISTINCT FROM '20'/);assert.match(sql,/a009f2b4-86df-4701-a8bc-1112597e3c42/)
    assert.doesNotMatch(sql,/83888906-23fa-4653-a886-fe2733ed76a0/);assert.doesNotMatch(sql,/generation' IS DISTINCT FROM '6'/)
    assert.match(sql,/operator_project_ref='wrhgscovsgsudtedbljr'/)
  }
  const recovery=readFileSync('config/staging-generation-20-recovery.sql','utf8')
  assert.match(recovery,/'generation',20/);assert.match(recovery,/state','retired'/);assert.match(recovery,/NOLOGIN PASSWORD NULL/)
  assert.match(recovery,/rolpassword IS NOT NULL/)
  assert.match(recovery,/Runtime credential survives retirement/)
  assert.match(recovery,/Missing retired runtime ADMIN-only operator edge/)
  assert.match(recovery,/pg_authid WHERE rolname=r AND rolpassword IS NOT NULL/)
  assert.doesNotMatch(recovery,/pg_roles WHERE rolname=r AND \(rolcanlogin OR rolpassword/)
  assert.match(recovery,/Direct private authority survives retirement/)
  assert.match(recovery,/Active Gen20 credential drift shape mismatch/)
  assert.match(recovery,/'UNSET_REQUIRES_REVIEWED_ARMING_DIFF'='UNSET_REQUIRES_REVIEWED_ARMING_DIFF'/)
  assert.match(recovery,/rolvaliduntil=expires_at/)
  assert.doesNotMatch(recovery,/rolvaliduntil='infinity'::timestamptz/)
  const postcommit=readFileSync('config/staging-generation-20-recovery-postcommit.sql','utf8')
  assert.match(postcommit,/rolpassword IS NOT NULL/)
  assert.match(postcommit,/Runtime credential survives retirement/)
  assert.match(postcommit,/Missing retired runtime ADMIN-only operator edge/)
  assert.match(postcommit,/pg_authid WHERE rolname=r AND rolpassword IS NOT NULL/)
  assert.doesNotMatch(postcommit,/pg_roles WHERE rolname=r AND \(rolcanlogin OR rolpassword/)
  assert.match(postcommit,/'operatorEdges',5/)
  assert.match(postcommit,/Direct private authority survives retirement/)
  assert.match(postcommit,/tll_gen20_retirement_postcommit/)
  assert.match(postcommit,/'generation',20/)
  assert.match(postcommit,/Post-commit controls are not exact-singleton disabled/)
})

test('generated recovery and retirement preflight share exact-active bounded semantics for future or just-expired windows', () => {
  const recovery = readFileSync('config/staging-generation-20-recovery.sql', 'utf8')
  const preflight = readFileSync('config/staging-generation-20-retirement-preflight.sql', 'utf8')
  // Recovery checks role expiry against the parsed marker; preflight expresses
  // the same equality as a fail-closed IS DISTINCT FROM check. Neither permits infinity.
  assert.match(recovery, /rolvaliduntil=expires_at/)
  assert.match(preflight, /rolvaliduntil FROM pg_roles WHERE rolname=r\) IS DISTINCT FROM marker_expiry/)
  for (const sql of [recovery, preflight]) {
    assert.doesNotMatch(sql, /rolvaliduntil='infinity'::timestamptz/)
  }
  // Neither gate compares the bounded marker expiry to clock time, so cleanup
  // accepts an exact finite matching window both before and just after expiry.
  assert.doesNotMatch(recovery, /expires_at[<>=]+clock_timestamp\(\)/)
  assert.doesNotMatch(preflight, /marker_expiry[<>=]+clock_timestamp\(\)/)
})

test('all Gen20 runtime SQL generators consume the single reviewed Phase-1 expiry source', () => {
  for (const path of [
    'scripts/staging-generation-20-transport.mjs',
    'scripts/staging-generation-20-recovery.mjs',
    'scripts/staging-generation-20-retirement-preflight.mjs',
  ]) assert.match(readFileSync(path, 'utf8'), /ACTIVE_WINDOW_EXPIRES_AT/)
})
