-- GENERATED by scripts/staging-generation-21-retirement-preflight.mjs; do not edit.
-- Secret-free, read-only, exact-active gate for one Generation 21 retirement.
BEGIN READ ONLY;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='20s';
DO $preflight$
DECLARE
  r text; marker text; parsed jsonb; first_marker text; marker_expiry timestamptz;
  operator_name name:=session_user; expected_edges integer; expected_operator_edges integer;
BEGIN
  IF current_database()<>'postgres' OR current_user<>'postgres' OR session_user<>'postgres'
    OR current_user<>session_user OR current_setting('server_version_num')::int<170000
    OR (SELECT rolsuper OR NOT rolcreaterole FROM pg_roles WHERE rolname=operator_name)
    OR NOT pg_has_role(operator_name,'pg_read_all_stats','MEMBER') THEN
    RAISE EXCEPTION 'Gen21 retirement preflight requires exact reviewed staging operator';
  END IF;
  IF to_regclass('tll_staging_private.environment') IS NULL
    OR (SELECT count(*) FROM tll_staging_private.environment)<>1
    OR NOT EXISTS(SELECT 1 FROM tll_staging_private.environment WHERE singleton
      AND environment='tll-hosted-staging-v1' AND operator_project_ref='qdmvngjwkcsilzmqksme'
      AND operator_context='supabase-dashboard:qdmvngjwkcsilzmqksme:staging-bootstrap:reviewed'
      AND identity_basis='explicit-operator-dashboard-binding' AND bootstrap_version='2026-09-15-v2'
      AND source_commit='a50e37ff05d8e731dc8ffceea1e96492079e5ff3'
      AND integrity_sha256='2d5175eb47a891ca626d635281fbb28237b16bec0d89eebe168455935117922c')
    OR EXISTS(SELECT 1 FROM tll_staging_private.environment WHERE operator_project_ref='wrhgscovsgsudtedbljr') THEN
    RAISE EXCEPTION 'Gen21 retirement preflight staging binding mismatch';
  END IF;
  IF (SELECT count(*) FROM tll_staging_private.applied_migrations)<>15
    OR (SELECT count(*) FROM (VALUES ('202609150002_public_submission_gateway','c82f9afb10c7ee7e46549033d4076046568557226a7864f8c2b8c8117ecd4bca'),('202609150003_active_stack_integrity','05cac500b24262975a773b2db284bc3fb95b62dc25fc6d47670eefbc86f15a60'),('202609150004_inventory_operation_ledger','030ccb26228aca6665147eced447815f8a290abd74b8003b0f32bfb2a05e5a76'),('202609150005_customer_connection_repository','f0f49edca9a0938b8e40b4d87ba7ee1eaee02dbc5082fc019a58ca949b263d0b'),('202609150006_staging_cart_sessions','17d039a6d1f343f35d1551c259a3f8c0e8643fe669b8230170a235bbc941155c'),('202609150007_customer_subject_broker_repository','85a118335d91d896b707dcdff1570f6c2df22a9b2037e9a569b587b89ad41c21'),('202609170008_customer_provisional_admission_repository','038b2bfc9d236f39c0cb5ae9b657a5a54b572fc304e6da318b00a07cf0d201e2'),('202609170009_inventory_maintenance_authority','4f054b145466a6ef2136ec79a0e1c17e8aa252e5bc02fa8c27deb23664eb153f'),('202609170010_customer_admission_bridge','711b92ef8a6e5760a126e340396f68cc372e361ee3e6bf66f3e6f3370be5f7aa'),('202609170011_customer_browser_admission_once','12bf5b5916d2f266f218bcd39c38098aea3225acef1cb0f67b47fe76bc29f58f'),('202609180012_customer_shopify_proof_repository','c0b105293f01b79329c050a16702ad98123b744b63c85a63dbce8c1a2b7b6e61'),('202609180013_customer_final_reconciliation','4dc438d016fbe2f4e1a5cac7c76aa9f48f0bde369488702661f516fdd88841a6'),('202609180014_staging_cart_account_transition','99b3737bcffe7957e5eeb64d46566953ad2a9e8b4d045fdaf9e995a223a29061'),('202609180015_customer_account_operations','dfaafaa6ee121c5f33e7f1aff6a83f14d972455ef5fdd0ed2a49411f8b15c0ee'),('202609180016_customer_account_logout','b512d9d18599b60a18ea20d94b3502d94c5735c1ac20bbb76321efd46dea8349')) AS expected(version,source_sha256)
      JOIN tll_staging_private.applied_migrations actual USING(version,source_sha256))<>15 THEN
    RAISE EXCEPTION 'Gen21 retirement preflight migration ledger mismatch';
  END IF;
  IF (SELECT count(*) FROM pg_roles WHERE rolname IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'))<>5 THEN
    RAISE EXCEPTION 'Gen21 retirement preflight runtime role set mismatch';
  END IF;
  FOREACH r IN ARRAY ARRAY['tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
    SELECT shobj_description(oid,'pg_authid') INTO marker FROM pg_roles WHERE rolname=r;
    IF marker IS NULL OR marker !~ '^tll-runtime-window/v1 [{].*[}]$' THEN
      RAISE EXCEPTION 'Gen21 retirement preflight runtime marker malformed: %',r;
    END IF;
    BEGIN parsed:=substring(marker FROM '^tll-runtime-window/v1 ([{].*[}])$')::jsonb;
    EXCEPTION WHEN others THEN RAISE EXCEPTION 'Gen21 retirement preflight runtime marker invalid: %',r; END;
    IF jsonb_typeof(parsed) IS DISTINCT FROM 'object' OR (SELECT count(*) FROM jsonb_object_keys(parsed))<>5
      OR NOT (parsed ?& ARRAY['projectRef','generation','windowId','expiresAt','state'])
      OR jsonb_typeof(parsed->'projectRef') IS DISTINCT FROM 'string' OR parsed->>'projectRef' IS DISTINCT FROM 'qdmvngjwkcsilzmqksme'
      OR jsonb_typeof(parsed->'generation') IS DISTINCT FROM 'number' OR parsed->>'generation' IS DISTINCT FROM '21'
      OR jsonb_typeof(parsed->'windowId') IS DISTINCT FROM 'string' OR parsed->>'windowId' IS DISTINCT FROM 'a5511645-77af-4fc9-9e4c-f5c8a474d5fa'
      OR jsonb_typeof(parsed->'expiresAt') IS DISTINCT FROM 'string' OR parsed->>'expiresAt' IS DISTINCT FROM '2026-09-22T14:00:00.000Z'
      OR jsonb_typeof(parsed->'state') IS DISTINCT FROM 'string' OR parsed->>'state' IS DISTINCT FROM 'active' THEN
      RAISE EXCEPTION 'Gen21 retirement preflight runtime marker target mismatch: %',r;
    END IF;
    BEGIN marker_expiry:=(parsed->>'expiresAt')::timestamptz;
    EXCEPTION WHEN others THEN RAISE EXCEPTION 'Gen21 retirement preflight runtime expiry invalid: %',r; END;
    IF (SELECT rolvaliduntil FROM pg_roles WHERE rolname=r) IS DISTINCT FROM marker_expiry
      OR NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r AND rolcanlogin)
      OR NOT EXISTS(SELECT 1 FROM pg_authid WHERE rolname=r AND rolpassword IS NOT NULL) THEN
      RAISE EXCEPTION 'Gen21 retirement preflight runtime credential state mismatch: %',r;
    END IF;
    IF first_marker IS NULL THEN first_marker:=marker;
    ELSIF marker IS DISTINCT FROM first_marker THEN RAISE EXCEPTION 'Gen21 retirement preflight runtime markers mixed'; END IF;
  END LOOP;
  SELECT count(*) INTO expected_edges FROM pg_auth_members e
    JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member
    WHERE (granted.rolname,member.rolname) IN (
      ('tll_customer_executor','tll_customer_runtime'),('tll_cart_gateway','tll_cart_runtime'),
      ('tll_broker_executor','tll_broker_runtime'),('tll_provisional_executor','tll_provisional_runtime'),
      ('tll_bridge_executor','tll_bridge_runtime'))
      AND e.grantor=operator_name::regrole AND NOT e.admin_option AND e.inherit_option AND NOT e.set_option;
  SELECT count(*) INTO expected_operator_edges FROM pg_auth_members e
    JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member
    WHERE granted.rolname IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime') AND member.rolname=operator_name
      AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option;
  IF expected_edges<>5 OR expected_operator_edges<>5
    OR (SELECT count(*) FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid
      JOIN pg_roles member ON member.oid=e.member
      WHERE granted.rolname IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime') OR member.rolname IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'))<>10 THEN
    RAISE EXCEPTION 'Gen21 retirement preflight runtime membership graph mismatch';
  END IF;
  IF EXISTS(SELECT 1 FROM pg_stat_activity WHERE backend_type='client backend' AND usename IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime')) THEN
    RAISE EXCEPTION 'Gen21 retirement preflight runtime sessions remain';
  END IF;
  IF (SELECT count(*) FROM tll_customer_private.control)<>1 OR (SELECT count(*) FROM tll_customer_private.control WHERE singleton AND enabled)<>1
    OR (SELECT count(*) FROM tll_cart_private.control)<>1 OR (SELECT count(*) FROM tll_cart_private.control WHERE singleton AND enabled)<>1
    OR (SELECT count(*) FROM tll_broker_private.control)<>1 OR (SELECT count(*) FROM tll_broker_private.control WHERE singleton AND enabled)<>1
    OR (SELECT count(*) FROM tll_provisional_private.control)<>1 OR (SELECT count(*) FROM tll_provisional_private.control WHERE singleton AND enabled)<>1
    OR (SELECT count(*) FROM tll_bridge_private.control)<>1 OR (SELECT count(*) FROM tll_bridge_private.control WHERE singleton AND enabled)<>1 THEN
    RAISE EXCEPTION 'Gen21 retirement preflight exact-active controls mismatch';
  END IF;
  IF EXISTS(SELECT 1 FROM tll_customer_private.shopify_proofs WHERE state NOT IN ('pending','exchanging','verified','held'))
    OR EXISTS(SELECT 1 FROM tll_cart_private.sessions WHERE phase NOT IN ('ready','working','held'))
    OR EXISTS(SELECT 1 FROM tll_cart_private.operations WHERE state NOT IN ('working','ready','held'))
    OR EXISTS(SELECT 1 FROM tll_cart_private.transitions WHERE state NOT IN ('claimed','reconciled','held'))
    OR EXISTS(SELECT 1 FROM tll_broker_private.flows WHERE status NOT IN ('registered','admitted','verifying','ready','token_issued','consumed','held','cancelled'))
    OR EXISTS(SELECT 1 FROM tll_provisional_private.intents WHERE state NOT IN ('prepared','admission_inflight','admitted','held','cancelled'))
    OR EXISTS(SELECT 1 FROM tll_bridge_private.grants WHERE state NOT IN ('pending_browser','browser_admitted','held','cancelled'))
    OR EXISTS(SELECT 1 FROM tll_bridge_private.finalizations WHERE state NOT IN ('exchanging','reconciled','held'))
    OR EXISTS(SELECT 1 FROM tll_bridge_private.account_operations WHERE state NOT IN ('claimed','completed','held')) THEN
    RAISE EXCEPTION 'Gen21 retirement preflight unexpected private work state';
  END IF;
  IF EXISTS(
    SELECT 1 FROM pg_namespace n CROSS JOIN LATERAL aclexplode(n.nspacl) a
      WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND a.grantee=0 AND a.privilege_type='USAGE'
    UNION ALL
    SELECT 1 FROM pg_namespace n CROSS JOIN LATERAL aclexplode(n.nspacl) a JOIN pg_roles g ON g.oid=a.grantee
      WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND g.rolname IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime')
    UNION ALL
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL aclexplode(c.relacl) a JOIN pg_roles g ON g.oid=a.grantee
      WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND g.rolname IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime')
    UNION ALL
    SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace CROSS JOIN LATERAL aclexplode(p.proacl) a JOIN pg_roles g ON g.oid=a.grantee
      WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND g.rolname IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime')) THEN
    RAISE EXCEPTION 'Gen21 retirement preflight direct or PUBLIC private authority detected';
  END IF;
END $preflight$;
SELECT jsonb_build_object(
  'queryId','tll-staging-generation-21-retirement-preflight/v2','projectRef','qdmvngjwkcsilzmqksme','generation',21,'windowId','a5511645-77af-4fc9-9e4c-f5c8a474d5fa',
  'status','PASS_EXACT_ACTIVE_BOUNDED','credentialState','ACTIVE_BOUNDED_FINITE','migrations',15,'runtimeRoles',5,'runtimeSessions',0,
  'controlsEnabled',5,'executionEdges',5,'operatorEdges',5,
  'workCounts',jsonb_build_object(
    'shopifyProofs',(SELECT coalesce(jsonb_object_agg(state,n),'{}'::jsonb) FROM (SELECT state,count(*) n FROM tll_customer_private.shopify_proofs GROUP BY state) s),
    'cartSessions',(SELECT coalesce(jsonb_object_agg(phase,n),'{}'::jsonb) FROM (SELECT phase,count(*) n FROM tll_cart_private.sessions GROUP BY phase) s),
    'cartOperations',(SELECT coalesce(jsonb_object_agg(state,n),'{}'::jsonb) FROM (SELECT state,count(*) n FROM tll_cart_private.operations GROUP BY state) s),
    'cartTransitions',(SELECT coalesce(jsonb_object_agg(state,n),'{}'::jsonb) FROM (SELECT state,count(*) n FROM tll_cart_private.transitions GROUP BY state) s),
    'brokerFlows',(SELECT coalesce(jsonb_object_agg(status,n),'{}'::jsonb) FROM (SELECT status,count(*) n FROM tll_broker_private.flows GROUP BY status) s),
    'provisionalIntents',(SELECT coalesce(jsonb_object_agg(state,n),'{}'::jsonb) FROM (SELECT state,count(*) n FROM tll_provisional_private.intents GROUP BY state) s),
    'bridgeGrants',(SELECT coalesce(jsonb_object_agg(state,n),'{}'::jsonb) FROM (SELECT state,count(*) n FROM tll_bridge_private.grants GROUP BY state) s),
    'bridgeFinalizations',(SELECT coalesce(jsonb_object_agg(state,n),'{}'::jsonb) FROM (SELECT state,count(*) n FROM tll_bridge_private.finalizations GROUP BY state) s),
    'accountOperations',(SELECT coalesce(jsonb_object_agg(state,n),'{}'::jsonb) FROM (SELECT state,count(*) n FROM tll_bridge_private.account_operations GROUP BY state) s),
    'accountLogouts',(SELECT count(*) FROM tll_bridge_private.account_logouts))) AS tll_gen21_retirement_preflight;
COMMIT;
