-- GENERATED by scripts/staging-disabled-migrations-012-016.prepare.mjs; do not edit.
-- The only generated transformation removes each canonical migration's outer
-- BEGIN/COMMIT wrapper so all five sources commit or roll back together.
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='60s';
DO $tll_install_guard$
DECLARE expected_count integer:=10; actual_count integer; matched_count integer; r text;
BEGIN
 IF current_database()<>'postgres' OR current_user<>'postgres' OR session_user<>'postgres' OR current_user<>session_user
   OR coalesce((SELECT rolsuper FROM pg_roles WHERE rolname=current_user),true)
   OR NOT coalesce((SELECT rolcreaterole FROM pg_roles WHERE rolname=current_user),false)
   OR NOT pg_has_role(current_user,'pg_read_all_data','USAGE') OR pg_has_role(current_user,'pg_write_all_data','USAGE')
   OR NOT pg_has_role(current_user,'pg_read_all_stats','USAGE') THEN RAISE EXCEPTION 'Exact managed non-superuser staging postgres operator authority required'; END IF;
 IF to_regclass('tll_staging_private.environment') IS NULL OR (SELECT count(*) FROM tll_staging_private.environment)<>1
   OR NOT EXISTS(SELECT 1 FROM tll_staging_private.environment WHERE singleton AND environment='tll-hosted-staging-v1' AND operator_project_ref='qdmvngjwkcsilzmqksme' AND operator_context='supabase-dashboard:qdmvngjwkcsilzmqksme:staging-bootstrap:reviewed' AND identity_basis='explicit-operator-dashboard-binding' AND bootstrap_version='2026-09-15-v2')
   OR EXISTS(SELECT 1 FROM tll_staging_private.environment WHERE operator_project_ref='wrhgscovsgsudtedbljr') THEN RAISE EXCEPTION 'Exact staging environment binding required; production is excluded'; END IF;
 SELECT count(*),count(*) FILTER (WHERE (version,source_sha256) IN (VALUES ('202609150002_public_submission_gateway','c82f9afb10c7ee7e46549033d4076046568557226a7864f8c2b8c8117ecd4bca'),('202609150003_active_stack_integrity','05cac500b24262975a773b2db284bc3fb95b62dc25fc6d47670eefbc86f15a60'),('202609150004_inventory_operation_ledger','030ccb26228aca6665147eced447815f8a290abd74b8003b0f32bfb2a05e5a76'),('202609150005_customer_connection_repository','f0f49edca9a0938b8e40b4d87ba7ee1eaee02dbc5082fc019a58ca949b263d0b'),('202609150006_staging_cart_sessions','17d039a6d1f343f35d1551c259a3f8c0e8643fe669b8230170a235bbc941155c'),('202609150007_customer_subject_broker_repository','85a118335d91d896b707dcdff1570f6c2df22a9b2037e9a569b587b89ad41c21'),('202609170008_customer_provisional_admission_repository','038b2bfc9d236f39c0cb5ae9b657a5a54b572fc304e6da318b00a07cf0d201e2'),('202609170009_inventory_maintenance_authority','4f054b145466a6ef2136ec79a0e1c17e8aa252e5bc02fa8c27deb23664eb153f'),('202609170010_customer_admission_bridge','711b92ef8a6e5760a126e340396f68cc372e361ee3e6bf66f3e6f3370be5f7aa'),('202609170011_customer_browser_admission_once','12bf5b5916d2f266f218bcd39c38098aea3225acef1cb0f67b47fe76bc29f58f'))) INTO actual_count,matched_count FROM tll_staging_private.applied_migrations;
 IF actual_count<>expected_count OR matched_count<>expected_count OR EXISTS(SELECT 1 FROM tll_staging_private.applied_migrations WHERE version IN ('202609180012_customer_shopify_proof_repository','202609180013_customer_final_reconciliation','202609180014_staging_cart_account_transition','202609180015_customer_account_operations','202609180016_customer_account_logout')) THEN RAISE EXCEPTION 'Exact 002--011 predecessor ledger required'; END IF;
 IF tll_customer_private.operator_status()->'enabled'<>'false'::jsonb OR coalesce((SELECT enabled FROM tll_cart_private.control WHERE singleton),true)
   OR tll_broker_private.operator_status()->'enabled'<>'false'::jsonb OR tll_provisional_private.operator_status()->'enabled'<>'false'::jsonb OR tll_bridge_private.operator_status()->'enabled'<>'false'::jsonb THEN RAISE EXCEPTION 'All controls must remain disabled'; END IF;
 IF to_regclass('tll_customer_private.shopify_proofs') IS NOT NULL OR to_regclass('tll_bridge_private.finalizations') IS NOT NULL OR to_regclass('tll_cart_private.transitions') IS NOT NULL OR to_regclass('tll_bridge_private.account_generations') IS NOT NULL OR to_regclass('tll_bridge_private.account_logouts') IS NOT NULL THEN RAISE EXCEPTION 'Expected empty migration destination required'; END IF;
 FOREACH r IN ARRAY ARRAY['tll_customer_owner','tll_cart_owner','tll_broker_owner','tll_provisional_owner','tll_bridge_owner'] LOOP
   IF NOT EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member WHERE granted.rolname=r AND member.rolname=current_user AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option) THEN RAISE EXCEPTION 'Exact reviewed ADMIN-only owner authority required: %',r; END IF;
 END LOOP;
END $tll_install_guard$;
-- Disabled additive Shopify proof custody for the customer executor. This adds
-- no LOGIN, credential, route, provider configuration or activation.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
DO $preflight$
DECLARE installer name:=current_user;
BEGIN
 IF current_user<>session_user OR current_setting('server_version_num')::int<170000
   OR to_regnamespace('tll_customer_private') IS NULL
   OR to_regprocedure('tll_customer_private.repository(text,jsonb)') IS NULL
   OR to_regclass('tll_customer_private.shopify_proofs') IS NOT NULL
   OR to_regprocedure('tll_customer_private.shopify_proof_repository(text,jsonb)') IS NOT NULL
   OR tll_customer_private.operator_status()->'enabled'<>'false'::jsonb THEN
   RAISE EXCEPTION 'Shopify proof repository installation unavailable'; END IF;
 IF NOT (SELECT rolsuper FROM pg_roles WHERE rolname=current_user) AND NOT EXISTS(
   SELECT FROM pg_auth_members WHERE roleid='tll_customer_owner'::regrole AND member=current_user::regrole
     AND admin_option AND NOT inherit_option AND NOT set_option) THEN
   RAISE EXCEPTION 'Reviewed customer owner upgrade authority required'; END IF;
 EXECUTE format('GRANT tll_customer_owner TO %I WITH INHERIT TRUE, SET TRUE',installer);
END $preflight$;

CREATE SEQUENCE tll_customer_private.shopify_proof_fences AS bigint NO CYCLE;
CREATE TABLE tll_customer_private.shopify_proofs(
 transaction_id uuid PRIMARY KEY,
 state_hash text NOT NULL CHECK(state_hash ~ '^[a-f0-9]{64}$'),
 config_hash text CHECK(config_hash ~ '^[a-f0-9]{64}$'),
 callback_url text,
 inner_challenge text CHECK(inner_challenge ~ '^[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$'),
 attempt_material jsonb,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 expires_at timestamptz,
 state text NOT NULL CHECK(state IN ('pending','exchanging','verified','held')),
 fence bigint NOT NULL CHECK(fence>0),
 claim_operation uuid UNIQUE,
 receipt_id uuid UNIQUE,
 shop_id text,
 issuer text,
 subject text,
 verified_at timestamptz,
 proof_expires_at timestamptz,
 access_expires_at timestamptz,
 tokens jsonb,
 CHECK((state='held') OR (config_hash IS NOT NULL AND callback_url IS NOT NULL AND inner_challenge IS NOT NULL
   AND expires_at>created_at AND expires_at<=created_at+interval '5 minutes')),
 CHECK(state NOT IN ('pending','exchanging') OR attempt_material IS NOT NULL),
 CHECK(state<>'exchanging' OR claim_operation IS NOT NULL),
 CHECK(state<>'verified' OR (attempt_material IS NULL AND receipt_id IS NOT NULL AND shop_id='107532616020'
   AND issuer='https://shopify.com/authentication/107532616020' AND subject IS NOT NULL
   AND verified_at IS NOT NULL AND proof_expires_at>verified_at AND access_expires_at>=proof_expires_at AND tokens IS NOT NULL)),
 CHECK(state='verified' OR (receipt_id IS NULL AND shop_id IS NULL AND issuer IS NULL AND subject IS NULL
   AND verified_at IS NULL AND proof_expires_at IS NULL AND access_expires_at IS NULL AND tokens IS NULL)),
 CHECK(attempt_material IS NULL OR tll_customer_private.envelope_valid(attempt_material)),
 CHECK(tokens IS NULL OR tll_customer_private.envelope_valid(tokens))
);
CREATE UNIQUE INDEX shopify_proof_state_hash ON tll_customer_private.shopify_proofs(state_hash) WHERE state<>'held';

CREATE FUNCTION tll_customer_private.shopify_proof_repository(op text,p jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $repository$
DECLARE ctl tll_customer_private.control%ROWTYPE; r tll_customer_private.shopify_proofs%ROWTYPE;
 ts timestamptz:=clock_timestamp(); rid uuid; f bigint; created timestamptz; expiry timestamptz;
 verified timestamptz; proof_expiry timestamptz; access_expiry timestamptz; proof jsonb;
BEGIN
 IF op IS NULL OR op NOT IN ('create','claim','finish','read','hold')
   OR jsonb_typeof(p) IS DISTINCT FROM 'object' OR octet_length(p::text)>65536
   OR COALESCE(p->>'transactionId','') !~ '^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' THEN
   RAISE EXCEPTION 'Invalid Shopify proof request' USING ERRCODE='22023'; END IF;
 rid:=(p->>'transactionId')::uuid;
 SELECT * INTO STRICT ctl FROM tll_customer_private.control WHERE singleton FOR UPDATE;
 IF NOT ctl.enabled AND op<>'hold' THEN RETURN jsonb_build_object('status','rejected'); END IF;

 IF op='hold' THEN
   IF p-ARRAY['transactionId','stateHash','fence']<>'{}'::jsonb OR COALESCE(p->>'stateHash','') !~ '^[a-f0-9]{64}$'
     OR (p ? 'fence' AND COALESCE(p->>'fence','') !~ '^[1-9][0-9]{0,18}$') THEN
     RAISE EXCEPTION 'Invalid Shopify proof hold' USING ERRCODE='22023'; END IF;
   SELECT * INTO r FROM tll_customer_private.shopify_proofs WHERE transaction_id=rid FOR UPDATE;
   IF NOT FOUND THEN
     INSERT INTO tll_customer_private.shopify_proofs(transaction_id,state_hash,state,fence)
       VALUES(rid,p->>'stateHash','held',nextval('tll_customer_private.shopify_proof_fences'));
     RETURN jsonb_build_object('status','held');
   END IF;
   IF r.state_hash IS DISTINCT FROM p->>'stateHash' OR (p ? 'fence' AND r.fence::text IS DISTINCT FROM p->>'fence') THEN
     RETURN jsonb_build_object('status','rejected'); END IF;
   UPDATE tll_customer_private.shopify_proofs SET state='held',fence=nextval('tll_customer_private.shopify_proof_fences'),
     attempt_material=NULL,receipt_id=NULL,shop_id=NULL,issuer=NULL,subject=NULL,verified_at=NULL,
     proof_expires_at=NULL,access_expires_at=NULL,tokens=NULL WHERE transaction_id=rid;
   RETURN jsonb_build_object('status','held');
 END IF;

 IF op='create' THEN
   IF p-ARRAY['transactionId','stateHash','configHash','callbackUrl','innerPkceChallenge','createdAt','expiresAt','material']<>'{}'::jsonb
     OR COALESCE(p->>'stateHash','') !~ '^[a-f0-9]{64}$' OR COALESCE(p->>'configHash','') !~ '^[a-f0-9]{64}$'
     OR COALESCE(p->>'callbackUrl','') !~ '^https://the-lifting-[a-z0-9-]+-my-lifting-lab-s-projects[.]vercel[.]app/auth/customer/shopify/callback$'
     OR COALESCE(p->>'innerPkceChallenge','') !~ '^[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$'
     OR jsonb_typeof(p->'createdAt') IS DISTINCT FROM 'number' OR (p->>'createdAt') !~ '^[1-9][0-9]{0,14}$'
     OR jsonb_typeof(p->'expiresAt') IS DISTINCT FROM 'number' OR (p->>'expiresAt') !~ '^[1-9][0-9]{0,14}$'
     OR NOT tll_customer_private.envelope_valid(p->'material') THEN RETURN jsonb_build_object('status','rejected'); END IF;
   created:=to_timestamp((p->>'createdAt')::numeric/1000); expiry:=to_timestamp((p->>'expiresAt')::numeric/1000);
   IF created>ts OR created<ts-interval '5 seconds' OR expiry<=ts OR expiry>created+interval '5 minutes'
     OR EXISTS(SELECT FROM tll_customer_private.shopify_proofs WHERE transaction_id=rid OR (state_hash=p->>'stateHash' AND state<>'held'))
     OR (SELECT count(*) FROM tll_customer_private.shopify_proofs)>=10000 THEN RETURN jsonb_build_object('status','rejected'); END IF;
   f:=nextval('tll_customer_private.shopify_proof_fences');
   INSERT INTO tll_customer_private.shopify_proofs(transaction_id,state_hash,config_hash,callback_url,inner_challenge,
     attempt_material,created_at,expires_at,state,fence) VALUES(rid,p->>'stateHash',p->>'configHash',p->>'callbackUrl',
     p->>'innerPkceChallenge',p->'material',created,expiry,'pending',f);
   RETURN jsonb_build_object('status','created');
 END IF;

 SELECT * INTO r FROM tll_customer_private.shopify_proofs WHERE transaction_id=rid FOR UPDATE;
 IF NOT FOUND THEN RETURN jsonb_build_object('status','rejected'); END IF;
 IF op='read' THEN
   IF p-ARRAY['transactionId']<>'{}'::jsonb OR r.state<>'verified' OR r.proof_expires_at<=ts OR r.tokens IS NULL THEN
     RETURN jsonb_build_object('status','rejected'); END IF;
   RETURN jsonb_build_object('status','verified','proof',jsonb_build_object('transactionId',r.transaction_id,
     'receiptId',r.receipt_id,'shopId',r.shop_id,'issuer',r.issuer,'subject',r.subject,
     'innerPkceChallenge',r.inner_challenge,'verifiedAt',floor(extract(epoch FROM r.verified_at)*1000)::bigint,
     'expiresAt',floor(extract(epoch FROM r.proof_expires_at)*1000)::bigint));
 END IF;

 IF op='claim' THEN
   IF p-ARRAY['operationId','transactionId','stateHash','configHash']<>'{}'::jsonb
     OR COALESCE(p->>'operationId','') !~ '^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$'
     OR r.state<>'pending' OR r.expires_at<=ts OR r.state_hash IS DISTINCT FROM p->>'stateHash'
     OR r.config_hash IS DISTINCT FROM p->>'configHash'
     OR EXISTS(SELECT FROM tll_customer_private.shopify_proofs WHERE claim_operation=(p->>'operationId')::uuid) THEN
     RETURN jsonb_build_object('status','rejected'); END IF;
   f:=nextval('tll_customer_private.shopify_proof_fences');
   UPDATE tll_customer_private.shopify_proofs SET state='exchanging',fence=f,claim_operation=(p->>'operationId')::uuid
     WHERE transaction_id=rid RETURNING * INTO r;
   RETURN jsonb_build_object('status','claimed','transactionId',r.transaction_id,'stateHash',r.state_hash,
     'configHash',r.config_hash,'callbackUrl',r.callback_url,'innerPkceChallenge',r.inner_challenge,
     'createdAt',floor(extract(epoch FROM r.created_at)*1000)::bigint,'expiresAt',floor(extract(epoch FROM r.expires_at)*1000)::bigint,
     'fence',r.fence::text,'material',r.attempt_material);
 END IF;

 IF p-ARRAY['transactionId','stateHash','fence','proof','accessExpiresAt','tokens']<>'{}'::jsonb
   OR r.state<>'exchanging' OR r.state_hash IS DISTINCT FROM p->>'stateHash' OR r.fence::text IS DISTINCT FROM p->>'fence'
   OR r.expires_at<=ts OR jsonb_typeof(p->'proof') IS DISTINCT FROM 'object'
   OR NOT tll_customer_private.envelope_valid(p->'tokens') THEN RETURN jsonb_build_object('status','rejected'); END IF;
 proof:=p->'proof';
 IF proof-ARRAY['transactionId','receiptId','shopId','issuer','subject','innerPkceChallenge','verifiedAt','expiresAt']<>'{}'::jsonb
   OR proof->>'transactionId' IS DISTINCT FROM rid::text
   OR COALESCE(proof->>'receiptId','') !~ '^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$'
   OR proof->>'shopId' IS DISTINCT FROM '107532616020'
   OR proof->>'issuer' IS DISTINCT FROM 'https://shopify.com/authentication/107532616020'
   OR length(COALESCE(proof->>'subject','')) NOT BETWEEN 1 AND 256
   OR COALESCE(proof->>'subject','') ~ '[[:cntrl:][:space:]]'
   OR proof->>'innerPkceChallenge' IS DISTINCT FROM r.inner_challenge
   OR jsonb_typeof(proof->'verifiedAt') IS DISTINCT FROM 'number' OR (proof->>'verifiedAt') !~ '^[1-9][0-9]{0,14}$'
   OR jsonb_typeof(proof->'expiresAt') IS DISTINCT FROM 'number' OR (proof->>'expiresAt') !~ '^[1-9][0-9]{0,14}$'
   OR jsonb_typeof(p->'accessExpiresAt') IS DISTINCT FROM 'number' OR (p->>'accessExpiresAt') !~ '^[1-9][0-9]{0,14}$' THEN
   RETURN jsonb_build_object('status','rejected'); END IF;
 verified:=to_timestamp((proof->>'verifiedAt')::numeric/1000); proof_expiry:=to_timestamp((proof->>'expiresAt')::numeric/1000);
 access_expiry:=to_timestamp((p->>'accessExpiresAt')::numeric/1000);
 IF verified>ts OR verified<ts-interval '10 seconds' OR proof_expiry<=ts OR proof_expiry>r.expires_at
   OR access_expiry<proof_expiry OR EXISTS(SELECT FROM tll_customer_private.shopify_proofs WHERE receipt_id=(proof->>'receiptId')::uuid) THEN
   RETURN jsonb_build_object('status','rejected'); END IF;
 UPDATE tll_customer_private.shopify_proofs SET state='verified',attempt_material=NULL,receipt_id=(proof->>'receiptId')::uuid,
   shop_id=proof->>'shopId',issuer=proof->>'issuer',subject=proof->>'subject',verified_at=verified,
   proof_expires_at=proof_expiry,access_expires_at=access_expiry,tokens=p->'tokens' WHERE transaction_id=rid;
 RETURN jsonb_build_object('status','verified');
END $repository$;

DO $secure$
DECLARE installer name:=current_user; r record; g record;
BEGIN
 ALTER SEQUENCE tll_customer_private.shopify_proof_fences OWNER TO tll_customer_owner;
 ALTER TABLE tll_customer_private.shopify_proofs OWNER TO tll_customer_owner;
 ALTER TABLE tll_customer_private.shopify_proofs ENABLE ROW LEVEL SECURITY;
 ALTER FUNCTION tll_customer_private.shopify_proof_repository(text,jsonb) OWNER TO tll_customer_owner;
 FOR r IN SELECT c.oid,c.relkind,c.relname FROM pg_class c WHERE c.relnamespace='tll_customer_private'::regnamespace
   AND c.relname IN ('shopify_proofs','shopify_proof_fences') LOOP
   FOR g IN SELECT DISTINCT x.grantee FROM pg_class c CROSS JOIN LATERAL aclexplode(COALESCE(c.relacl,
     acldefault(CASE WHEN c.relkind='S' THEN 'S'::"char" ELSE 'r'::"char" END,c.relowner))) x
     WHERE c.oid=r.oid AND x.grantee<>c.relowner LOOP
     EXECUTE format('REVOKE ALL ON %s tll_customer_private.%I FROM %s',CASE WHEN r.relkind='S' THEN 'SEQUENCE' ELSE 'TABLE' END,
       r.relname,CASE WHEN g.grantee=0 THEN 'PUBLIC' ELSE quote_ident(pg_get_userbyid(g.grantee)) END);
   END LOOP;
 END LOOP;
 REVOKE ALL ON FUNCTION tll_customer_private.shopify_proof_repository(text,jsonb) FROM PUBLIC;
 GRANT EXECUTE ON FUNCTION tll_customer_private.shopify_proof_repository(text,jsonb) TO tll_customer_executor;
 IF (SELECT rolsuper FROM pg_roles WHERE rolname=current_user) THEN
   EXECUTE format('GRANT tll_customer_owner TO %I WITH ADMIN TRUE, INHERIT FALSE, SET FALSE',installer);
 ELSE EXECUTE format('REVOKE tll_customer_owner FROM %I GRANTED BY %I',installer,installer); END IF;
END $secure$;

DO $postflight$
DECLARE role_name text; r record; expected_read boolean;
BEGIN
 IF tll_customer_private.operator_status()->'enabled'<>'false'::jsonb THEN RAISE EXCEPTION 'Unexpected proof activation'; END IF;
 IF (SELECT count(*) FROM pg_auth_members WHERE roleid='tll_customer_owner'::regrole AND member=current_user::regrole
   AND admin_option AND NOT inherit_option AND NOT set_option)<>1 THEN RAISE EXCEPTION 'Unexpected repository membership'; END IF;
 IF EXISTS(SELECT FROM pg_class c WHERE c.relnamespace='tll_customer_private'::regnamespace AND c.relkind IN ('r','S')
     AND (c.relowner<>'tll_customer_owner'::regrole
       OR EXISTS(SELECT FROM aclexplode(COALESCE(c.relacl,acldefault(CASE WHEN c.relkind='S' THEN 'S'::"char" ELSE 'r'::"char" END,c.relowner))) x WHERE x.grantee<>c.relowner)
       OR EXISTS(SELECT FROM pg_attribute a CROSS JOIN LATERAL aclexplode(a.attacl) x WHERE a.attrelid=c.oid AND x.grantee<>c.relowner))) THEN
   RAISE EXCEPTION 'Unexpected private relation or column ACL'; END IF;
 FOREACH role_name IN ARRAY ARRAY['anon','authenticated','service_role','tll_customer_executor',current_user::text] LOOP
   IF role_name<>current_user::text AND (SELECT rolsuper FROM pg_roles WHERE rolname=role_name) THEN
     RAISE EXCEPTION 'Unexpected protected role superuser'; END IF;
   IF has_schema_privilege(role_name,'tll_customer_private','CREATE') THEN RAISE EXCEPTION 'Unexpected private schema CREATE'; END IF;
   expected_read:=role_name=current_user::text AND pg_has_role(role_name,'pg_read_all_data','USAGE');
   FOR r IN SELECT oid,relkind FROM pg_class WHERE relnamespace='tll_customer_private'::regnamespace AND relkind IN ('r','S') LOOP
     IF r.relkind='r' AND ((has_table_privilege(role_name,r.oid,'SELECT') IS DISTINCT FROM expected_read)
       OR (has_any_column_privilege(role_name,r.oid,'SELECT') IS DISTINCT FROM expected_read)
       OR has_table_privilege(role_name,r.oid,'INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN')
       OR has_any_column_privilege(role_name,r.oid,'INSERT,UPDATE,REFERENCES')) THEN
       RAISE EXCEPTION 'Unexpected effective private data access'; END IF;
     IF r.relkind='S' AND ((has_sequence_privilege(role_name,r.oid,'SELECT') IS DISTINCT FROM expected_read)
       OR has_sequence_privilege(role_name,r.oid,'USAGE,UPDATE')) THEN RAISE EXCEPTION 'Unexpected effective sequence access'; END IF;
   END LOOP;
   IF has_function_privilege(role_name,'tll_customer_private.shopify_proof_repository(text,jsonb)','EXECUTE')
     IS DISTINCT FROM (role_name='tll_customer_executor') THEN RAISE EXCEPTION 'Unexpected effective function authority'; END IF;
 END LOOP;
END $postflight$;

-- Disabled additive final reconciliation store. No LOGIN, credential, route,
-- provider configuration, auth-table write or activation is created.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
DO $preflight$
DECLARE installer name:=current_user; r text;
BEGIN
 IF current_user<>session_user OR current_setting('server_version_num')::int<170000
   OR to_regprocedure('tll_bridge_private.repository(text,jsonb)') IS NULL
   OR to_regprocedure('tll_customer_private.shopify_proof_repository(text,jsonb)') IS NULL
   OR to_regclass('tll_bridge_private.finalizations') IS NOT NULL
   OR to_regprocedure('tll_bridge_private.final_repository(text,jsonb)') IS NOT NULL THEN
   RAISE EXCEPTION 'Final reconciliation installation unavailable'; END IF;
 IF (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_bridge_private.repository(text,jsonb)'::regprocedure)<>'5ab7163c673663e76a6b2e071faecd8c'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_broker_private.repository(text,jsonb)'::regprocedure)<>'3a73033597ae0b514f29c66b6b5f6bf8'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_provisional_private.repository(text,jsonb)'::regprocedure)<>'c81cd90f775d744f0f7b0b466359a7d6'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_customer_private.shopify_proof_repository(text,jsonb)'::regprocedure)<>'7d95dcb1616833d24d52b380667ab1ce'
   OR NOT EXISTS(SELECT FROM pg_constraint WHERE conrelid='tll_provisional_private.intents'::regclass
     AND conname='provisional_browser_once' AND contype='u' AND convalidated AND NOT condeferrable) THEN
   RAISE EXCEPTION 'Reviewed final prerequisite source required'; END IF;
 FOREACH r IN ARRAY ARRAY['tll_bridge_owner','tll_broker_owner','tll_provisional_owner','tll_customer_owner'] LOOP
   IF NOT (SELECT rolsuper FROM pg_roles WHERE rolname=current_user) AND NOT EXISTS(SELECT FROM pg_auth_members
     WHERE roleid=r::regrole AND member=current_user::regrole AND admin_option AND NOT inherit_option AND NOT set_option) THEN
     RAISE EXCEPTION 'Reviewed owner upgrade authority required'; END IF;
   EXECUTE format('GRANT %I TO %I WITH INHERIT TRUE, SET TRUE',r,installer);
 END LOOP;
 PERFORM tll_bridge_private.gate();
 IF tll_bridge_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_broker_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_provisional_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_customer_private.operator_status()->'enabled'<>'false'::jsonb THEN
   RAISE EXCEPTION 'Disable all customer repositories before final upgrade'; END IF;
END $preflight$;

ALTER TABLE tll_broker_private.subjects DROP CONSTRAINT subjects_reservation_check;
ALTER TABLE tll_broker_private.subjects DROP CONSTRAINT subjects_check;
ALTER TABLE tll_broker_private.subjects ADD COLUMN bound_user_id uuid REFERENCES auth.users(id);
ALTER TABLE tll_broker_private.subjects ADD CONSTRAINT subjects_reservation_check CHECK(reservation IN ('provisional','pending_migration','bound'));
ALTER TABLE tll_broker_private.subjects ADD CONSTRAINT subjects_owner_state CHECK(
 (reservation='provisional' AND pending_user_id IS NULL AND bound_user_id IS NULL)
 OR(reservation='pending_migration' AND pending_user_id IS NOT NULL AND bound_user_id IS NULL)
 OR(reservation='bound' AND pending_user_id IS NULL AND bound_user_id IS NOT NULL));
ALTER TABLE tll_broker_private.subjects ADD CONSTRAINT subjects_shop_bound_unique UNIQUE(shop_id,bound_user_id);

CREATE SEQUENCE tll_bridge_private.final_fences AS bigint NO CYCLE;
CREATE TABLE tll_bridge_private.finalizations(
 transaction_id uuid PRIMARY KEY,
 browser_hash text NOT NULL CHECK(browser_hash ~ '^[a-f0-9]{64}$'),
 callback_hash text NOT NULL UNIQUE CHECK(callback_hash ~ '^[a-f0-9]{64}$'),
 state text NOT NULL CHECK(state IN ('exchanging','reconciled','held')),
 fence bigint NOT NULL CHECK(fence>0), generation bigint NOT NULL DEFAULT 0 CHECK(generation>=0),
 claim_operation uuid UNIQUE, finish_operation uuid UNIQUE,
 mode text CHECK(mode IN ('sign_in','migration')), original_user_id uuid,
 config_hash text CHECK(config_hash ~ '^[a-f0-9]{64}$'), intent_hash text CHECK(intent_hash ~ '^[a-f0-9]{64}$'),
 application_challenge text CHECK(application_challenge ~ '^[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$'),
 callback_material jsonb, provisional_material jsonb,
 proof_receipt_id uuid, reserved_subject text CHECK(reserved_subject ~ '^tllb_[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$'),
 expires_at timestamptz, user_id uuid REFERENCES auth.users(id), identity_id uuid,
 authenticated_at timestamptz, checked_at timestamptz, session_expires_at timestamptz, session_material jsonb,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(), reconciled_at timestamptz,
 CHECK(state='held' OR (claim_operation IS NOT NULL AND mode IS NOT NULL AND config_hash IS NOT NULL AND intent_hash IS NOT NULL
   AND application_challenge IS NOT NULL AND callback_material IS NOT NULL AND provisional_material IS NOT NULL
   AND proof_receipt_id IS NOT NULL AND reserved_subject IS NOT NULL AND expires_at>created_at)),
 CHECK((mode='migration')=(original_user_id IS NOT NULL)),
 CHECK(state<>'reconciled' OR (finish_operation IS NOT NULL AND user_id IS NOT NULL AND identity_id IS NOT NULL
   AND authenticated_at IS NOT NULL AND checked_at IS NOT NULL AND session_expires_at>checked_at
   AND session_material IS NOT NULL AND reconciled_at IS NOT NULL)),
 CHECK(state='reconciled' OR (user_id IS NULL AND identity_id IS NULL AND authenticated_at IS NULL AND checked_at IS NULL
   AND session_expires_at IS NULL AND session_material IS NULL AND reconciled_at IS NULL)),
 CHECK(callback_material IS NULL OR tll_customer_private.envelope_valid(callback_material)),
 CHECK(provisional_material IS NULL OR tll_customer_private.envelope_valid(provisional_material)),
 CHECK(session_material IS NULL OR tll_customer_private.envelope_valid(session_material))
);
CREATE TABLE tll_bridge_private.final_operations(
 id uuid PRIMARY KEY, transaction_id uuid NOT NULL REFERENCES tll_bridge_private.finalizations(transaction_id),
 phase text NOT NULL CHECK(phase IN ('claim','finish','hold')), generation bigint NOT NULL,
 claim_fence bigint NOT NULL, completed boolean NOT NULL, created_at timestamptz NOT NULL
);

-- Owner-held cross-store snapshots. The bridge owner receives EXECUTE only;
-- it never receives table authority or membership in another owner role.
CREATE FUNCTION tll_customer_private.final_lock() RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $f$
DECLARE enabled boolean; BEGIN SELECT c.enabled INTO STRICT enabled FROM tll_customer_private.control c WHERE singleton FOR UPDATE; RETURN enabled; END $f$;
CREATE FUNCTION tll_customer_private.final_source(rid uuid) RETURNS jsonb
LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $f$
 SELECT jsonb_build_object('receiptId',receipt_id,'shopId',shop_id,'issuer',issuer,'subject',subject,
   'proofExpiresAt',floor(extract(epoch FROM proof_expires_at)*1000)::bigint)
 FROM tll_customer_private.shopify_proofs WHERE transaction_id=rid AND state='verified' AND proof_expires_at>clock_timestamp()
$f$;
CREATE FUNCTION tll_provisional_private.final_source(rid uuid,browser text) RETURNS jsonb
LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $f$
 SELECT jsonb_build_object('browserHash',browser_hash,'configHash',config_hash,'intentHash',intent_hash,
   'applicationPkceChallenge',application_challenge,'metadata',metadata,'material',material,
   'expiresAt',floor(extract(epoch FROM expires_at)*1000)::bigint)
 FROM tll_provisional_private.intents WHERE id=rid AND browser_hash=browser AND state='admitted' AND expires_at>clock_timestamp()
$f$;
CREATE FUNCTION tll_broker_private.final_source(rid uuid) RETURNS jsonb
LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $f$
 SELECT jsonb_build_object('status',f.status,'sub',f.sub,'receiptId',f.proof_receipt_id,'shopifyProof',f.shopify_proof,
   'registration',f.registration,'hardDeadline',floor(extract(epoch FROM f.hard_deadline)*1000)::bigint,
   'reservation',s.reservation,'pendingUserId',s.pending_user_id,'boundUserId',s.bound_user_id)
 FROM tll_broker_private.flows f JOIN tll_broker_private.subjects s ON s.sub=f.sub
 WHERE f.id=rid AND f.status='consumed' AND f.hard_deadline>clock_timestamp()
$f$;
CREATE FUNCTION tll_broker_private.final_promote(rid uuid,stable_sub text,final_user uuid) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $f$
DECLARE f tll_broker_private.flows%ROWTYPE; s tll_broker_private.subjects%ROWTYPE; mode text; target uuid;
BEGIN
 SELECT * INTO f FROM tll_broker_private.flows WHERE id=rid AND status='consumed' AND sub=stable_sub AND hard_deadline>clock_timestamp() FOR UPDATE;
 IF NOT FOUND THEN RETURN false; END IF;
 SELECT * INTO s FROM tll_broker_private.subjects WHERE sub=stable_sub FOR UPDATE; mode:=f.registration->>'mode';
 target:=NULLIF(f.registration->'target'->>'userId','')::uuid;
 IF s.reservation='bound' THEN RETURN s.bound_user_id=final_user; END IF;
 IF (mode='sign_in' AND (target IS NOT NULL OR s.reservation<>'provisional'))
   OR(mode='migration' AND (target IS DISTINCT FROM final_user OR s.reservation<>'pending_migration' OR s.pending_user_id IS DISTINCT FROM final_user)) THEN RETURN false; END IF;
 IF EXISTS(SELECT FROM tll_broker_private.subjects x WHERE x.shop_id=s.shop_id AND x.bound_user_id=final_user AND x.sub<>stable_sub) THEN RETURN false; END IF;
 UPDATE tll_broker_private.subjects SET reservation='bound',pending_user_id=NULL,bound_user_id=final_user WHERE sub=stable_sub;
 RETURN true;
END $f$;

CREATE FUNCTION tll_bridge_private.final_repository(op text,p jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $repository$
DECLARE gate jsonb; enabled_customer boolean; r tll_bridge_private.finalizations%ROWTYPE; previous tll_bridge_private.final_operations%ROWTYPE; g tll_bridge_private.grants%ROWTYPE;
 ps jsonb; bs jsonb; cs jsonb; meta jsonb; proof jsonb; reg jsonb; rid uuid; oid uuid; ts timestamptz:=clock_timestamp(); f bigint;
 expiry timestamptz; authenticated timestamptz; checked timestamptz; session_expiry timestamptz; final_user uuid; final_identity uuid;
BEGIN
 IF op IS NULL OR op NOT IN ('claim','finish','release','hold') OR jsonb_typeof(p) IS DISTINCT FROM 'object' OR octet_length(p::text)>65536
   OR NOT tll_provisional_private.uuid_valid(p->>'transactionId') OR (op<>'finish' AND NOT tll_provisional_private.hash_valid(p->>'browserHash'))
   OR NOT tll_provisional_private.hash_valid(p->>'callbackHash') OR (op<>'release' AND NOT tll_provisional_private.uuid_valid(p->>'operationId')) THEN
   RAISE EXCEPTION 'Invalid final reconciliation request' USING ERRCODE='22023'; END IF;
 gate:=tll_bridge_private.gate(); enabled_customer:=tll_customer_private.final_lock(); rid:=(p->>'transactionId')::uuid;
 SELECT * INTO r FROM tll_bridge_private.finalizations WHERE transaction_id=rid FOR UPDATE;
 IF op='release' THEN
   IF gate->'enabled'<>'true'::jsonb OR NOT enabled_customer OR p-ARRAY['transactionId','browserHash','callbackHash']<>'{}'::jsonb OR r.state<>'reconciled' OR r.browser_hash<>p->>'browserHash'
     OR r.callback_hash<>p->>'callbackHash' OR r.session_expires_at<=ts THEN RETURN jsonb_build_object('status','rejected'); END IF;
   RETURN jsonb_build_object('status','reconciled','transactionId',r.transaction_id,'callbackHash',r.callback_hash,
     'userId',r.user_id,'identityId',r.identity_id,'reservedSubject',r.reserved_subject,'generation',r.generation::text,'sessionMaterial',r.session_material);
 END IF;
 oid:=(p->>'operationId')::uuid; SELECT * INTO previous FROM tll_bridge_private.final_operations WHERE id=oid;
 IF op='hold' THEN
   IF p-ARRAY['operationId','transactionId','browserHash','callbackHash','fence','generation']<>'{}'::jsonb
     OR (p ? 'fence')<>(p ? 'generation') OR (p ? 'fence' AND (COALESCE(p->>'fence','')!~'^[1-9][0-9]{0,18}$' OR COALESCE(p->>'generation','')!~'^(0|[1-9][0-9]{0,18})$'))
     OR previous.id IS NOT NULL OR (r.transaction_id IS NOT NULL AND (r.browser_hash<>p->>'browserHash' OR r.callback_hash<>p->>'callbackHash'))
     OR (p ? 'fence' AND (r.transaction_id IS NULL OR r.fence::text<>p->>'fence' OR r.generation::text<>p->>'generation')) THEN RETURN jsonb_build_object('status','rejected'); END IF;
   IF r.transaction_id IS NULL THEN
     f:=nextval('tll_bridge_private.final_fences');
     INSERT INTO tll_bridge_private.finalizations(transaction_id,browser_hash,callback_hash,state,fence) VALUES(rid,p->>'browserHash',p->>'callbackHash','held',f);
     INSERT INTO tll_bridge_private.final_operations VALUES(oid,rid,'hold',0,f,true,ts);
   ELSIF r.state<>'held' THEN
     INSERT INTO tll_bridge_private.final_operations VALUES(oid,rid,'hold',r.generation,r.fence,true,ts);
     UPDATE tll_bridge_private.finalizations SET state='held',generation=generation+1,fence=nextval('tll_bridge_private.final_fences'),
       callback_material=NULL,provisional_material=NULL,user_id=NULL,identity_id=NULL,authenticated_at=NULL,checked_at=NULL,
       session_expires_at=NULL,session_material=NULL,reconciled_at=NULL WHERE transaction_id=rid;
   ELSE RETURN jsonb_build_object('status','rejected'); END IF;
   PERFORM tll_bridge_private.terminal(rid,'held'); RETURN jsonb_build_object('status','held');
 END IF;
 IF gate->'enabled'<>'true'::jsonb OR NOT enabled_customer THEN RETURN jsonb_build_object('status','rejected'); END IF;
 IF op='claim' THEN
   IF p-ARRAY['operationId','transactionId','browserHash','callbackHash','callbackMaterial']<>'{}'::jsonb OR previous.id IS NOT NULL OR r.transaction_id IS NOT NULL
     OR NOT tll_customer_private.envelope_valid(p->'callbackMaterial') THEN RETURN jsonb_build_object('status','rejected'); END IF;
   SELECT * INTO g FROM tll_bridge_private.grants WHERE id=rid;
   ps:=tll_provisional_private.final_source(rid,p->>'browserHash'); bs:=tll_broker_private.final_source(rid); cs:=tll_customer_private.final_source(rid);
   IF g.id IS NULL OR g.state<>'browser_admitted' OR g.expires_at<=ts OR g.binding->>'browserHash' IS DISTINCT FROM p->>'browserHash'
     OR ps IS NULL OR bs IS NULL OR cs IS NULL THEN RETURN jsonb_build_object('status','rejected'); END IF;
   meta:=ps->'metadata'; reg:=bs->'registration'; proof:=bs->'shopifyProof';
   IF reg->>'mode' IS DISTINCT FROM meta->>'mode' OR reg->>'applicationPkceChallenge' IS DISTINCT FROM ps->>'applicationPkceChallenge'
     OR bs->>'sub' IS NULL OR bs->>'receiptId' IS DISTINCT FROM cs->>'receiptId' OR proof->>'receiptId' IS DISTINCT FROM cs->>'receiptId'
     OR proof->>'shopId' IS DISTINCT FROM cs->>'shopId' OR proof->>'issuer' IS DISTINCT FROM cs->>'issuer' OR proof->>'subject' IS DISTINCT FROM cs->>'subject'
     OR (meta->>'mode'='migration' AND (meta->'original'->>'userId' IS DISTINCT FROM reg->'target'->>'userId' OR bs->>'reservation'<>'pending_migration'))
     OR (meta->>'mode'='sign_in' AND (meta->'original' IS DISTINCT FROM 'null'::jsonb OR reg->'target' IS DISTINCT FROM 'null'::jsonb OR bs->>'reservation' NOT IN ('provisional','bound'))) THEN
     RETURN jsonb_build_object('status','rejected'); END IF;
   expiry:=LEAST(tll_provisional_private.ms(ps->'expiresAt'),tll_provisional_private.ms(bs->'hardDeadline'),tll_provisional_private.ms(cs->'proofExpiresAt'));
   IF expiry<=ts THEN RETURN jsonb_build_object('status','rejected'); END IF;
   f:=nextval('tll_bridge_private.final_fences');
   INSERT INTO tll_bridge_private.finalizations(transaction_id,browser_hash,callback_hash,state,fence,claim_operation,mode,original_user_id,
     config_hash,intent_hash,application_challenge,callback_material,provisional_material,proof_receipt_id,reserved_subject,expires_at)
   VALUES(rid,p->>'browserHash',p->>'callbackHash','exchanging',f,oid,meta->>'mode',NULLIF(meta->'original'->>'userId','')::uuid,
     ps->>'configHash',ps->>'intentHash',ps->>'applicationPkceChallenge',p->'callbackMaterial',ps->'material',(cs->>'receiptId')::uuid,bs->>'sub',expiry);
   INSERT INTO tll_bridge_private.final_operations VALUES(oid,rid,'claim',0,f,true,ts);
   RETURN jsonb_build_object('status','claimed','transactionId',rid,'browserHash',p->>'browserHash','callbackHash',p->>'callbackHash',
     'mode',meta->>'mode','originalUserId',NULLIF(meta->'original'->>'userId','')::uuid,'shopifyProofReceiptId',cs->>'receiptId',
     'fence',f::text,'generation','0','expiresAt',floor(extract(epoch FROM expiry)*1000)::bigint,
     'applicationPkceChallenge',ps->>'applicationPkceChallenge','reservedSubject',bs->>'sub','configHash',ps->>'configHash',
     'intentHash',ps->>'intentHash','provisionalMaterial',ps->'material','callbackMaterial',p->'callbackMaterial');
 END IF;
 IF p-ARRAY['transactionId','operationId','fence','generation','callbackHash','shopifyProofReceiptId','userId','identityId','reservedSubject','authenticatedAt','checkedAt','expiresAt','sessionMaterial']<>'{}'::jsonb
   OR previous.id IS NOT NULL OR r.state<>'exchanging' OR r.fence::text<>p->>'fence' OR r.generation::text<>p->>'generation'
   OR r.callback_hash<>p->>'callbackHash' OR r.proof_receipt_id::text<>p->>'shopifyProofReceiptId' OR r.reserved_subject<>p->>'reservedSubject'
   OR NOT tll_provisional_private.uuid_valid(p->>'userId') OR NOT tll_provisional_private.uuid_valid(p->>'identityId')
   OR NOT tll_customer_private.envelope_valid(p->'sessionMaterial') THEN RETURN jsonb_build_object('status','rejected'); END IF;
 final_user:=(p->>'userId')::uuid; final_identity:=(p->>'identityId')::uuid;
 IF r.mode='migration' AND final_user<>r.original_user_id THEN RETURN jsonb_build_object('status','rejected'); END IF;
 authenticated:=tll_provisional_private.ms(p->'authenticatedAt'); checked:=tll_provisional_private.ms(p->'checkedAt'); session_expiry:=tll_provisional_private.ms(p->'expiresAt');
 IF authenticated>ts OR authenticated<=ts-interval '5 minutes' OR checked>ts OR checked<=ts-interval '10 seconds' OR session_expiry<=ts
   OR NOT tll_broker_private.final_promote(rid,r.reserved_subject,final_user) THEN RETURN jsonb_build_object('status','rejected'); END IF;
 UPDATE tll_bridge_private.finalizations SET state='reconciled',finish_operation=oid,user_id=final_user,identity_id=final_identity,
   authenticated_at=authenticated,checked_at=checked,session_expires_at=session_expiry,session_material=p->'sessionMaterial',reconciled_at=ts WHERE transaction_id=rid;
 INSERT INTO tll_bridge_private.final_operations VALUES(oid,rid,'finish',r.generation,r.fence,true,ts);
 RETURN jsonb_build_object('status','reconciled');
END $repository$;

DO $secure$
DECLARE installer name:=current_user; r record; g record; role_name text;
BEGIN
 ALTER SEQUENCE tll_bridge_private.final_fences OWNER TO tll_bridge_owner;
 ALTER TABLE tll_bridge_private.finalizations OWNER TO tll_bridge_owner; ALTER TABLE tll_bridge_private.finalizations ENABLE ROW LEVEL SECURITY;
 ALTER TABLE tll_bridge_private.final_operations OWNER TO tll_bridge_owner; ALTER TABLE tll_bridge_private.final_operations ENABLE ROW LEVEL SECURITY;
 FOR r IN SELECT oid,oid::regprocedure signature,pronamespace FROM pg_proc WHERE oid IN (
   'tll_customer_private.final_lock()'::regprocedure,'tll_customer_private.final_source(uuid)'::regprocedure,
   'tll_provisional_private.final_source(uuid,text)'::regprocedure,'tll_broker_private.final_source(uuid)'::regprocedure,
   'tll_broker_private.final_promote(uuid,text,uuid)'::regprocedure,'tll_bridge_private.final_repository(text,jsonb)'::regprocedure) LOOP
   role_name:=CASE r.pronamespace WHEN 'tll_customer_private'::regnamespace THEN 'tll_customer_owner' WHEN 'tll_provisional_private'::regnamespace THEN 'tll_provisional_owner'
     WHEN 'tll_broker_private'::regnamespace THEN 'tll_broker_owner' ELSE 'tll_bridge_owner' END;
   EXECUTE format('ALTER FUNCTION %s OWNER TO %I',r.signature,role_name); EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',r.signature);
 END LOOP;
 REVOKE ALL ON TABLE tll_bridge_private.finalizations,tll_bridge_private.final_operations FROM PUBLIC;
 REVOKE ALL ON SEQUENCE tll_bridge_private.final_fences FROM PUBLIC;
 GRANT USAGE ON SCHEMA tll_customer_private TO tll_bridge_owner;
 GRANT EXECUTE ON FUNCTION tll_customer_private.final_lock(),tll_customer_private.final_source(uuid),tll_customer_private.envelope_valid(jsonb) TO tll_bridge_owner;
 GRANT EXECUTE ON FUNCTION tll_provisional_private.final_source(uuid,text) TO tll_bridge_owner;
 GRANT EXECUTE ON FUNCTION tll_broker_private.final_source(uuid),tll_broker_private.final_promote(uuid,text,uuid) TO tll_bridge_owner;
 GRANT EXECUTE ON FUNCTION tll_bridge_private.final_repository(text,jsonb) TO tll_bridge_executor;
 FOREACH role_name IN ARRAY ARRAY['tll_bridge_owner','tll_broker_owner','tll_provisional_owner','tll_customer_owner'] LOOP
   IF (SELECT rolsuper FROM pg_roles WHERE rolname=current_user) THEN
     EXECUTE format('GRANT %I TO %I WITH ADMIN TRUE, INHERIT FALSE, SET FALSE',role_name,installer);
   ELSE EXECUTE format('REVOKE %I FROM %I GRANTED BY %I',role_name,installer,installer); END IF;
 END LOOP;
END $secure$;
DO $postflight$
DECLARE role_name text;
BEGIN
 IF tll_bridge_private.operator_status()->'enabled'<>'false'::jsonb OR tll_broker_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_provisional_private.operator_status()->'enabled'<>'false'::jsonb OR tll_customer_private.operator_status()->'enabled'<>'false'::jsonb THEN
   RAISE EXCEPTION 'Unexpected final activation'; END IF;
 FOREACH role_name IN ARRAY ARRAY['anon','authenticated','service_role','tll_customer_executor','tll_broker_executor','tll_provisional_executor','tll_bridge_executor'] LOOP
   IF has_table_privilege(role_name,'tll_bridge_private.finalizations','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN')
     OR has_any_column_privilege(role_name,'tll_bridge_private.finalizations','SELECT,INSERT,UPDATE,REFERENCES')
     OR has_table_privilege(role_name,'tll_bridge_private.final_operations','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN') THEN
     RAISE EXCEPTION 'Unexpected final data authority'; END IF;
 END LOOP;
 IF NOT has_function_privilege('tll_bridge_executor','tll_bridge_private.final_repository(text,jsonb)','EXECUTE')
   OR has_function_privilege('anon','tll_bridge_private.final_repository(text,jsonb)','EXECUTE')
   OR has_function_privilege('service_role','tll_bridge_private.final_repository(text,jsonb)','EXECUTE') THEN
   RAISE EXCEPTION 'Unexpected final function authority'; END IF;
END $postflight$;

-- Disabled additive guest-to-account cart custody transition. No provider call,
-- LOGIN, credential, route or activation is created.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
DO $preflight$
DECLARE installer name:=current_user;
BEGIN
 IF current_user<>session_user OR current_setting('server_version_num')::int<170000
   OR to_regclass('tll_cart_private.sessions') IS NULL OR to_regclass('tll_cart_private.transitions') IS NOT NULL
   OR to_regprocedure('public.tll_cart_transition_claim(text,text,text,text,uuid,bigint)') IS NOT NULL
   OR (SELECT operator_oid FROM tll_cart_private.control WHERE singleton)<>current_user::regrole
   OR (SELECT enabled FROM tll_cart_private.control WHERE singleton) THEN
   RAISE EXCEPTION 'Disabled reviewed cart repository required'; END IF;
 IF (SELECT md5(prosrc) FROM pg_proc WHERE oid='public.tll_cart_open(text,text)'::regprocedure)<>'b40e7148f3fea1e658263fc6292b1ef1'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='public.tll_cart_read(text,text)'::regprocedure)<>'4ff1b6edceeb59d708c57a52042c7661'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='public.tll_cart_claim(text,text,uuid,text,bigint,integer)'::regprocedure)<>'3e817c44f5dd9a5c88bd038b2774f567'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='public.tll_cart_finish(text,text,uuid,text,jsonb,integer,integer,integer)'::regprocedure)<>'660c727005e044e69352676928bbb0ac'
   OR NOT EXISTS(SELECT FROM pg_auth_members WHERE roleid='tll_cart_owner'::regrole AND member=current_user::regrole
     AND admin_option AND NOT inherit_option AND NOT set_option) THEN RAISE EXCEPTION 'Reviewed cart source and upgrade authority required'; END IF;
 EXECUTE format('GRANT tll_cart_owner TO %I WITH INHERIT TRUE, SET TRUE',installer);
 GRANT CREATE ON SCHEMA public TO tll_cart_owner;
END $preflight$;

CREATE TABLE tll_cart_private.transitions(
 source_session text PRIMARY KEY REFERENCES tll_cart_private.sessions(session_hash),
 source_actor text NOT NULL CHECK(source_actor ~ '^[a-f0-9]{64}$'),
 target_session text NOT NULL UNIQUE CHECK(target_session ~ '^[a-f0-9]{64}$'),
 target_actor text NOT NULL CHECK(target_actor ~ '^[a-f0-9]{64}$'),
 request_id uuid NOT NULL UNIQUE, expected_revision bigint NOT NULL CHECK(expected_revision>=0),
 state text NOT NULL CHECK(state IN ('claimed','reconciled','held')),
 lease_until timestamptz, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), finished_at timestamptz,
 CHECK(source_session<>target_session AND source_actor<>target_actor),
 CHECK((state='claimed')=(lease_until IS NOT NULL)),
 CHECK((state='reconciled')=(finished_at IS NOT NULL))
);
REVOKE ALL ON TABLE tll_cart_private.transitions FROM PUBLIC,anon,authenticated,service_role,tll_cart_gateway;
ALTER TABLE tll_cart_private.transitions ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE ON tll_cart_private.transitions TO tll_cart_owner;
CREATE POLICY cart_transitions_owner ON tll_cart_private.transitions TO tll_cart_owner USING(true) WITH CHECK(true);

CREATE FUNCTION public.tll_cart_transition_read(p_source text,p_source_actor text,p_target text,p_target_actor text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $f$
DECLARE t tll_cart_private.transitions%ROWTYPE; s tll_cart_private.sessions%ROWTYPE; target tll_cart_private.sessions%ROWTYPE;
BEGIN
 IF p_source IS NULL OR p_source!~'^[a-f0-9]{64}$' OR p_source_actor IS NULL OR p_source_actor!~'^[a-f0-9]{64}$'
   OR p_target IS NULL OR p_target!~'^[a-f0-9]{64}$' OR p_target_actor IS NULL OR p_target_actor!~'^[a-f0-9]{64}$'
   OR p_source=p_target OR p_source_actor=p_target_actor THEN RAISE EXCEPTION 'Invalid cart transition context'; END IF;
 PERFORM 1 FROM tll_cart_private.sessions WHERE session_hash IN(p_source,p_target) ORDER BY session_hash FOR UPDATE;
 IF NOT coalesce((SELECT enabled FROM tll_cart_private.control WHERE singleton FOR SHARE),false) THEN RAISE EXCEPTION 'Staging cart repository unavailable' USING ERRCODE='55000'; END IF;
 SELECT * INTO t FROM tll_cart_private.transitions WHERE source_session=p_source;
 SELECT * INTO s FROM tll_cart_private.sessions WHERE session_hash=p_source AND actor_hash=p_source_actor;
 SELECT * INTO target FROM tll_cart_private.sessions WHERE session_hash=p_target AND actor_hash=p_target_actor;
 IF t.source_session IS NULL THEN RETURN jsonb_build_object('status','absent','source',CASE WHEN s.session_hash IS NULL THEN NULL ELSE tll_cart_private.snapshot(s) END,
   'target',CASE WHEN target.session_hash IS NULL THEN NULL ELSE tll_cart_private.snapshot(target) END); END IF;
 IF t.source_actor<>p_source_actor OR t.target_session<>p_target OR t.target_actor<>p_target_actor THEN RETURN jsonb_build_object('status','conflict'); END IF;
 IF t.state='claimed' AND t.lease_until<=clock_timestamp() THEN
   UPDATE tll_cart_private.transitions SET state='held',lease_until=NULL WHERE source_session=p_source RETURNING * INTO t;
   UPDATE tll_cart_private.sessions SET phase='held',lease_until=NULL WHERE session_hash=p_source AND operation_id=t.request_id RETURNING * INTO s;
 END IF;
 RETURN jsonb_build_object('status',t.state,'source',CASE WHEN s.session_hash IS NULL THEN NULL ELSE tll_cart_private.snapshot(s) END,
   'target',CASE WHEN target.session_hash IS NULL THEN NULL ELSE tll_cart_private.snapshot(target) END);
END $f$;

CREATE FUNCTION public.tll_cart_transition_claim(p_source text,p_source_actor text,p_target text,p_target_actor text,p_request uuid,p_revision bigint) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $f$
DECLARE t tll_cart_private.transitions%ROWTYPE; s tll_cart_private.sessions%ROWTYPE; target tll_cart_private.sessions%ROWTYPE;
BEGIN
 IF p_request IS NULL OR p_revision IS NULL OR p_revision<0 OR p_source IS NULL OR p_source!~'^[a-f0-9]{64}$'
   OR p_source_actor IS NULL OR p_source_actor!~'^[a-f0-9]{64}$' OR p_target IS NULL OR p_target!~'^[a-f0-9]{64}$'
   OR p_target_actor IS NULL OR p_target_actor!~'^[a-f0-9]{64}$' OR p_source=p_target OR p_source_actor=p_target_actor THEN RAISE EXCEPTION 'Invalid cart transition'; END IF;
 PERFORM 1 FROM tll_cart_private.sessions WHERE session_hash IN(p_source,p_target) ORDER BY session_hash FOR UPDATE;
 IF NOT coalesce((SELECT enabled FROM tll_cart_private.control WHERE singleton FOR SHARE),false) THEN RAISE EXCEPTION 'Staging cart repository unavailable' USING ERRCODE='55000'; END IF;
 SELECT * INTO t FROM tll_cart_private.transitions WHERE source_session=p_source;
 IF t.source_session IS NOT NULL THEN
   IF t.source_actor=p_source_actor AND t.target_session=p_target AND t.target_actor=p_target_actor AND t.request_id=p_request AND t.expected_revision=p_revision THEN
     SELECT * INTO s FROM tll_cart_private.sessions WHERE session_hash=p_source;
     SELECT * INTO target FROM tll_cart_private.sessions WHERE session_hash=p_target;
     RETURN jsonb_build_object('status',CASE WHEN t.state='claimed' THEN 'replay' ELSE t.state END,
       'source',tll_cart_private.snapshot(s),'target',CASE WHEN target.session_hash IS NULL THEN NULL ELSE tll_cart_private.snapshot(target) END);
   END IF;
   RETURN jsonb_build_object('status','conflict');
 END IF;
 SELECT * INTO s FROM tll_cart_private.sessions WHERE session_hash=p_source AND actor_hash=p_source_actor;
 SELECT * INTO target FROM tll_cart_private.sessions WHERE session_hash=p_target;
 IF s.session_hash IS NULL OR s.expires_at<=clock_timestamp() OR s.phase<>'ready' OR s.revision<>p_revision OR target.session_hash IS NOT NULL THEN RETURN jsonb_build_object('status','conflict'); END IF;
 INSERT INTO tll_cart_private.transitions(source_session,source_actor,target_session,target_actor,request_id,expected_revision,state,lease_until)
 VALUES(p_source,p_source_actor,p_target,p_target_actor,p_request,p_revision,'claimed',clock_timestamp()+interval '45 seconds');
 UPDATE tll_cart_private.sessions SET phase='working',operation_id=p_request,lease_until=clock_timestamp()+interval '45 seconds' WHERE session_hash=p_source RETURNING * INTO s;
 RETURN jsonb_build_object('status','claimed','source',tll_cart_private.snapshot(s),'target',NULL);
END $f$;

CREATE FUNCTION public.tll_cart_transition_finish(p_source text,p_source_actor text,p_target text,p_target_actor text,p_request uuid,p_envelope jsonb,p_quantity integer,p_unit integer,p_subtotal integer) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $f$
DECLARE t tll_cart_private.transitions%ROWTYPE; s tll_cart_private.sessions%ROWTYPE; target tll_cart_private.sessions%ROWTYPE;
BEGIN
 PERFORM 1 FROM tll_cart_private.sessions WHERE session_hash IN(p_source,p_target) ORDER BY session_hash FOR UPDATE;
 IF NOT coalesce((SELECT enabled FROM tll_cart_private.control WHERE singleton FOR SHARE),false) THEN RAISE EXCEPTION 'Staging cart repository unavailable' USING ERRCODE='55000'; END IF;
 SELECT * INTO t FROM tll_cart_private.transitions WHERE source_session=p_source FOR UPDATE;
 SELECT * INTO s FROM tll_cart_private.sessions WHERE session_hash=p_source AND actor_hash=p_source_actor FOR UPDATE;
 SELECT * INTO target FROM tll_cart_private.sessions WHERE session_hash=p_target;
 IF t.source_session IS NULL OR t.source_actor<>p_source_actor OR t.target_session<>p_target OR t.target_actor<>p_target_actor OR t.request_id<>p_request
   OR t.state<>'claimed' OR s.session_hash IS NULL OR s.phase<>'working' OR s.operation_id<>p_request OR target.session_hash IS NOT NULL THEN RETURN jsonb_build_object('status','rejected'); END IF;
 IF t.lease_until<=clock_timestamp() THEN
   UPDATE tll_cart_private.transitions SET state='held',lease_until=NULL WHERE source_session=p_source;
   UPDATE tll_cart_private.sessions SET phase='held',lease_until=NULL WHERE session_hash=p_source;
   RETURN jsonb_build_object('status','held');
 END IF;
 IF p_quantity IS DISTINCT FROM s.quantity OR p_unit IS DISTINCT FROM s.unit_price_pence OR p_subtotal IS DISTINCT FROM s.subtotal_pence
   OR (s.envelope IS NULL)<>(p_envelope IS NULL) OR (p_envelope IS NOT NULL AND tll_cart_private.valid_envelope(p_envelope) IS NOT TRUE) THEN RAISE EXCEPTION 'Invalid cart transition projection'; END IF;
 INSERT INTO tll_cart_private.sessions(session_hash,actor_hash,revision,phase,envelope,quantity,unit_price_pence,subtotal_pence,expires_at)
 VALUES(p_target,p_target_actor,s.revision,'ready',p_envelope,s.quantity,s.unit_price_pence,s.subtotal_pence,clock_timestamp()+interval '24 hours') RETURNING * INTO target;
 UPDATE tll_cart_private.sessions SET revision=revision+1,phase='held',envelope=NULL,quantity=0,unit_price_pence=NULL,subtotal_pence=0,lease_until=NULL WHERE session_hash=p_source;
 UPDATE tll_cart_private.transitions SET state='reconciled',lease_until=NULL,finished_at=clock_timestamp() WHERE source_session=p_source;
 RETURN jsonb_build_object('status','reconciled','target',tll_cart_private.snapshot(target));
END $f$;

DO $secure$
DECLARE installer name:=current_user; signature regprocedure;
BEGIN
 FOREACH signature IN ARRAY ARRAY['public.tll_cart_transition_read(text,text,text,text)'::regprocedure,
   'public.tll_cart_transition_claim(text,text,text,text,uuid,bigint)'::regprocedure,
   'public.tll_cart_transition_finish(text,text,text,text,uuid,jsonb,integer,integer,integer)'::regprocedure] LOOP
   EXECUTE format('ALTER FUNCTION %s OWNER TO tll_cart_owner',signature);
   EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated,service_role,tll_cart_gateway',signature);
   EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO tll_cart_gateway',signature);
 END LOOP;
 REVOKE CREATE ON SCHEMA public FROM tll_cart_owner;
 IF (SELECT rolsuper FROM pg_roles WHERE rolname=current_user) THEN
   EXECUTE format('GRANT tll_cart_owner TO %I WITH ADMIN TRUE, INHERIT FALSE, SET FALSE',installer);
 ELSE EXECUTE format('REVOKE tll_cart_owner FROM %I GRANTED BY %I',installer,installer); END IF;
END $secure$;
DO $postflight$
DECLARE r text; signature regprocedure;
BEGIN
 IF (SELECT enabled FROM tll_cart_private.control WHERE singleton) OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tll_cart_private.transitions'::regclass) THEN RAISE EXCEPTION 'Unexpected cart transition activation'; END IF;
 FOREACH r IN ARRAY ARRAY['anon','authenticated','service_role'] LOOP
   IF has_table_privilege(r,'tll_cart_private.transitions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN') THEN RAISE EXCEPTION 'Transition data authority leak'; END IF;
 END LOOP;
 FOREACH signature IN ARRAY ARRAY['public.tll_cart_transition_read(text,text,text,text)'::regprocedure,
   'public.tll_cart_transition_claim(text,text,text,text,uuid,bigint)'::regprocedure,
   'public.tll_cart_transition_finish(text,text,text,text,uuid,jsonb,integer,integer,integer)'::regprocedure] LOOP
   IF NOT has_function_privilege('tll_cart_gateway',signature,'EXECUTE') OR has_function_privilege('authenticated',signature,'EXECUTE') THEN RAISE EXCEPTION 'Transition function authority mismatch'; END IF;
 END LOOP;
END $postflight$;

-- Disabled additive account-operation custody. This creates no LOGIN,
-- credential, route, provider configuration or activation.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';

DO $preflight$
DECLARE installer name:=current_user; r text;
BEGIN
 IF current_user<>session_user OR current_setting('server_version_num')::int<170000
   OR to_regprocedure('tll_bridge_private.final_repository(text,jsonb)') IS NULL
   OR to_regprocedure('tll_customer_private.shopify_proof_repository(text,jsonb)') IS NULL
   OR to_regprocedure('tll_customer_private.final_lock()') IS NULL
   OR to_regprocedure('tll_bridge_private.gate()') IS NULL
   OR to_regclass('tll_bridge_private.account_generations') IS NOT NULL
   OR to_regclass('tll_bridge_private.account_operations') IS NOT NULL
   OR to_regprocedure('tll_bridge_private.account_lock()') IS NOT NULL
   OR to_regprocedure('tll_customer_private.account_token_source(uuid,uuid)') IS NOT NULL
   OR to_regprocedure('tll_bridge_private.account_repository(text,jsonb)') IS NOT NULL THEN
   RAISE EXCEPTION 'Account operations installation unavailable'; END IF;
 IF (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_bridge_private.final_repository(text,jsonb)'::regprocedure)<>'6fdac5149231a4055ced04a1048ce43f'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_customer_private.shopify_proof_repository(text,jsonb)'::regprocedure)<>'7d95dcb1616833d24d52b380667ab1ce'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_customer_private.final_lock()'::regprocedure)<>'eb89fa4722b67e0cb54712cd232c1e2a'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_bridge_private.gate()'::regprocedure)<>'507ab740339ae86b72918cf43596472b' THEN
   RAISE EXCEPTION 'Reviewed account prerequisite source required'; END IF;
 FOREACH r IN ARRAY ARRAY['tll_bridge_owner','tll_customer_owner'] LOOP
   IF NOT (SELECT rolsuper FROM pg_roles WHERE rolname=current_user) AND NOT EXISTS(SELECT FROM pg_auth_members
     WHERE roleid=r::regrole AND member=current_user::regrole AND admin_option AND NOT inherit_option AND NOT set_option) THEN
     RAISE EXCEPTION 'Reviewed owner upgrade authority required'; END IF;
   EXECUTE format('GRANT %I TO %I WITH INHERIT TRUE, SET TRUE',r,installer);
 END LOOP;
 PERFORM tll_bridge_private.gate();
 IF tll_bridge_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_broker_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_provisional_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_customer_private.operator_status()->'enabled'<>'false'::jsonb THEN
   RAISE EXCEPTION 'Disable account repositories before upgrade'; END IF;
END $preflight$;

CREATE SEQUENCE tll_bridge_private.account_fences AS bigint NO CYCLE;
CREATE TABLE tll_bridge_private.account_generations(
 user_id uuid PRIMARY KEY REFERENCES auth.users(id),
 generation bigint NOT NULL DEFAULT 0 CHECK(generation>=0),
 updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE tll_bridge_private.account_operations(
 operation_id uuid PRIMARY KEY,
 kind text NOT NULL CHECK(kind='orders'),
 user_id uuid NOT NULL REFERENCES auth.users(id),
 session_id uuid NOT NULL,
 transaction_id uuid NOT NULL REFERENCES tll_bridge_private.finalizations(transaction_id),
 receipt_id uuid NOT NULL,
 generation bigint NOT NULL CHECK(generation>=0),
 fence bigint NOT NULL CHECK(fence>0),
 state text NOT NULL CHECK(state IN ('claimed','completed','held')),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 lease_until timestamptz NOT NULL,
 completed_at timestamptz,
 CHECK(lease_until>created_at),
 CHECK((state='claimed')=(completed_at IS NULL))
);
CREATE UNIQUE INDEX account_one_active_orders_per_user
 ON tll_bridge_private.account_operations(user_id) WHERE state='claimed';

CREATE FUNCTION tll_bridge_private.account_lock() RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $lock$
DECLARE enabled boolean; BEGIN SELECT c.enabled INTO STRICT enabled FROM tll_bridge_private.control c WHERE singleton FOR UPDATE; RETURN enabled; END $lock$;

-- The customer owner exposes one exact encrypted bundle. The bridge owner can
-- pass it to the server adapter but cannot decrypt it or read the proof table.
CREATE FUNCTION tll_customer_private.account_token_source(rid uuid,expected_receipt uuid) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $source$
DECLARE enabled boolean; r tll_customer_private.shopify_proofs%ROWTYPE;
BEGIN
 SELECT c.enabled INTO STRICT enabled FROM tll_customer_private.control c WHERE singleton FOR UPDATE;
 IF NOT enabled THEN RETURN NULL; END IF;
 SELECT * INTO r FROM tll_customer_private.shopify_proofs
  WHERE transaction_id=rid AND receipt_id=expected_receipt AND state='verified'
    AND access_expires_at>clock_timestamp() AND tokens IS NOT NULL;
 IF NOT FOUND THEN RETURN NULL; END IF;
 RETURN jsonb_build_object('transactionId',r.transaction_id,'receiptId',r.receipt_id,
   'shopId',r.shop_id,'issuer',r.issuer,'subject',r.subject,
   'innerPkceChallenge',r.inner_challenge,
   'verifiedAt',floor(extract(epoch FROM r.verified_at)*1000)::bigint,
   'proofExpiresAt',floor(extract(epoch FROM r.proof_expires_at)*1000)::bigint,
   'proofFence',r.fence::text,
   'accessExpiresAt',floor(extract(epoch FROM r.access_expires_at)*1000)::bigint,
   'tokens',r.tokens);
END $source$;

CREATE FUNCTION tll_bridge_private.account_repository(op text,p jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $repository$
DECLARE enabled_bridge boolean; enabled_customer boolean; ts timestamptz:=clock_timestamp(); oid uuid; uid uuid; sid uuid;
 r tll_bridge_private.account_operations%ROWTYPE; final tll_bridge_private.finalizations%ROWTYPE;
 gen tll_bridge_private.account_generations%ROWTYPE; source jsonb; f bigint;
BEGIN
 IF op IS NULL OR op NOT IN ('claim_orders','finish_orders','hold_orders')
   OR jsonb_typeof(p) IS DISTINCT FROM 'object' OR octet_length(p::text)>65536
   OR COALESCE(p->>'operationId','') !~ '^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$'
   OR COALESCE(p->>'userId','') !~ '^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$'
   OR COALESCE(p->>'sessionId','') !~ '^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' THEN
   RAISE EXCEPTION 'Invalid account operation request' USING ERRCODE='22023'; END IF;
 oid:=(p->>'operationId')::uuid; uid:=(p->>'userId')::uuid; sid:=(p->>'sessionId')::uuid;
 enabled_bridge:=tll_bridge_private.account_lock(); enabled_customer:=tll_customer_private.final_lock();

 IF op='hold_orders' THEN
   IF p-ARRAY['operationId','userId','sessionId','fence']<>'{}'::jsonb
     OR (p ? 'fence' AND COALESCE(p->>'fence','') !~ '^[1-9][0-9]{0,18}$') THEN
     RAISE EXCEPTION 'Invalid account operation hold' USING ERRCODE='22023'; END IF;
   SELECT * INTO r FROM tll_bridge_private.account_operations WHERE operation_id=oid FOR UPDATE;
   IF NOT FOUND OR r.user_id<>uid OR r.session_id<>sid OR r.state NOT IN ('claimed','completed')
     OR (p ? 'fence' AND r.fence::text<>p->>'fence') THEN RETURN jsonb_build_object('status','rejected'); END IF;
   UPDATE tll_bridge_private.account_operations SET state='held',completed_at=ts WHERE operation_id=oid;
   RETURN jsonb_build_object('status','held');
 END IF;

 IF NOT enabled_bridge OR NOT enabled_customer THEN RETURN jsonb_build_object('status','rejected'); END IF;
 IF p-ARRAY['operationId','userId','sessionId','fence']<>'{}'::jsonb
   OR (op='claim_orders' AND p ? 'fence')
   OR (op='finish_orders' AND COALESCE(p->>'fence','') !~ '^[1-9][0-9]{0,18}$') THEN
   RAISE EXCEPTION 'Invalid account operation payload' USING ERRCODE='22023'; END IF;

 INSERT INTO tll_bridge_private.account_generations(user_id) VALUES(uid) ON CONFLICT DO NOTHING;
 SELECT * INTO STRICT gen FROM tll_bridge_private.account_generations WHERE user_id=uid FOR UPDATE;
 UPDATE tll_bridge_private.account_operations SET state='held',completed_at=ts
  WHERE user_id=uid AND state='claimed' AND lease_until<=ts;

 IF op='finish_orders' THEN
   SELECT * INTO r FROM tll_bridge_private.account_operations WHERE operation_id=oid FOR UPDATE;
   IF NOT FOUND OR r.kind<>'orders' OR r.user_id<>uid OR r.session_id<>sid OR r.state<>'claimed'
     OR r.fence::text<>p->>'fence' OR r.generation<>gen.generation OR r.lease_until<=ts THEN
     RETURN jsonb_build_object('status','rejected'); END IF;
   UPDATE tll_bridge_private.account_operations SET state='completed',completed_at=ts WHERE operation_id=oid;
   RETURN jsonb_build_object('status','completed');
 END IF;

 IF EXISTS(SELECT FROM tll_bridge_private.account_operations WHERE operation_id=oid)
   OR EXISTS(SELECT FROM tll_bridge_private.account_operations WHERE user_id=uid AND state='claimed')
   OR (SELECT count(*) FROM tll_bridge_private.account_operations)>=100000
   OR (SELECT count(*) FROM tll_bridge_private.account_operations WHERE user_id=uid)>=1000 THEN
   RETURN jsonb_build_object('status','rejected'); END IF;
 SELECT * INTO final FROM tll_bridge_private.finalizations
  WHERE user_id=uid AND state='reconciled' AND proof_receipt_id IS NOT NULL
  ORDER BY reconciled_at DESC,transaction_id DESC LIMIT 1 FOR UPDATE;
 IF NOT FOUND THEN RETURN jsonb_build_object('status','rejected'); END IF;
 source:=tll_customer_private.account_token_source(final.transaction_id,final.proof_receipt_id);
 IF source IS NULL OR source->>'transactionId' IS DISTINCT FROM final.transaction_id::text
   OR source->>'receiptId' IS DISTINCT FROM final.proof_receipt_id::text THEN RETURN jsonb_build_object('status','rejected'); END IF;
 f:=nextval('tll_bridge_private.account_fences');
 INSERT INTO tll_bridge_private.account_operations(operation_id,kind,user_id,session_id,transaction_id,receipt_id,generation,fence,state,created_at,lease_until)
  VALUES(oid,'orders',uid,sid,final.transaction_id,final.proof_receipt_id,gen.generation,f,'claimed',ts,ts+interval '30 seconds');
 RETURN jsonb_build_object('status','claimed','operationId',oid,'userId',uid,'sessionId',sid,
   'transactionId',final.transaction_id,'receiptId',final.proof_receipt_id,'generation',gen.generation::text,
   'fence',f::text,'leaseExpiresAt',floor(extract(epoch FROM (ts+interval '30 seconds'))*1000)::bigint,
   'tokenSource',source);
END $repository$;

DO $secure$
DECLARE installer name:=current_user; role_name text;
BEGIN
 ALTER SEQUENCE tll_bridge_private.account_fences OWNER TO tll_bridge_owner;
 ALTER TABLE tll_bridge_private.account_generations OWNER TO tll_bridge_owner;
 ALTER TABLE tll_bridge_private.account_operations OWNER TO tll_bridge_owner;
 ALTER TABLE tll_bridge_private.account_generations ENABLE ROW LEVEL SECURITY;
 ALTER TABLE tll_bridge_private.account_operations ENABLE ROW LEVEL SECURITY;
 ALTER FUNCTION tll_bridge_private.account_lock() OWNER TO tll_bridge_owner;
 ALTER FUNCTION tll_customer_private.account_token_source(uuid,uuid) OWNER TO tll_customer_owner;
 ALTER FUNCTION tll_bridge_private.account_repository(text,jsonb) OWNER TO tll_bridge_owner;
 REVOKE ALL ON TABLE tll_bridge_private.account_generations,tll_bridge_private.account_operations FROM PUBLIC;
 REVOKE ALL ON SEQUENCE tll_bridge_private.account_fences FROM PUBLIC;
 REVOKE ALL ON FUNCTION tll_bridge_private.account_lock() FROM PUBLIC;
 REVOKE ALL ON FUNCTION tll_customer_private.account_token_source(uuid,uuid) FROM PUBLIC;
 REVOKE ALL ON FUNCTION tll_bridge_private.account_repository(text,jsonb) FROM PUBLIC;
 GRANT EXECUTE ON FUNCTION tll_customer_private.account_token_source(uuid,uuid) TO tll_bridge_owner;
 GRANT EXECUTE ON FUNCTION tll_bridge_private.account_repository(text,jsonb) TO tll_bridge_executor;
 FOREACH role_name IN ARRAY ARRAY['tll_bridge_owner','tll_customer_owner'] LOOP
   IF (SELECT rolsuper FROM pg_roles WHERE rolname=current_user) THEN
     EXECUTE format('GRANT %I TO %I WITH ADMIN TRUE, INHERIT FALSE, SET FALSE',role_name,installer);
   ELSE EXECUTE format('REVOKE %I FROM %I GRANTED BY %I',role_name,installer,installer); END IF;
 END LOOP;
END $secure$;

DO $postflight$
DECLARE role_name text;
BEGIN
 IF tll_bridge_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_broker_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_provisional_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_customer_private.operator_status()->'enabled'<>'false'::jsonb THEN
   RAISE EXCEPTION 'Unexpected account operation activation'; END IF;
 FOREACH role_name IN ARRAY ARRAY['anon','authenticated','service_role','tll_customer_executor','tll_bridge_executor'] LOOP
   IF has_table_privilege(role_name,'tll_bridge_private.account_generations','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN')
     OR has_any_column_privilege(role_name,'tll_bridge_private.account_generations','SELECT,INSERT,UPDATE,REFERENCES')
     OR has_table_privilege(role_name,'tll_bridge_private.account_operations','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN')
     OR has_any_column_privilege(role_name,'tll_bridge_private.account_operations','SELECT,INSERT,UPDATE,REFERENCES') THEN
     RAISE EXCEPTION 'Unexpected account operation data authority'; END IF;
 END LOOP;
 IF NOT has_function_privilege('tll_bridge_executor','tll_bridge_private.account_repository(text,jsonb)','EXECUTE')
   OR has_function_privilege('anon','tll_bridge_private.account_repository(text,jsonb)','EXECUTE')
   OR has_function_privilege('service_role','tll_bridge_private.account_repository(text,jsonb)','EXECUTE')
   OR NOT has_function_privilege('tll_bridge_owner','tll_customer_private.account_token_source(uuid,uuid)','EXECUTE')
   OR has_function_privilege('tll_bridge_executor','tll_customer_private.account_token_source(uuid,uuid)','EXECUTE')
   OR has_function_privilege('tll_bridge_executor','tll_bridge_private.account_lock()','EXECUTE') THEN
   RAISE EXCEPTION 'Unexpected account operation function authority'; END IF;
END $postflight$;

-- Disabled additive owner-wide account revocation. This creates no LOGIN,
-- credential, route, provider call, redirect or activation.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';

DO $preflight$
DECLARE installer name:=current_user; r text;
BEGIN
 IF current_user<>session_user OR current_setting('server_version_num')::int<170000
   OR to_regprocedure('tll_bridge_private.account_repository(text,jsonb)') IS NULL
   OR to_regprocedure('tll_bridge_private.terminal(uuid,text)') IS NULL
   OR to_regprocedure('tll_customer_private.account_token_source(uuid,uuid)') IS NULL
   OR to_regclass('tll_bridge_private.account_logouts') IS NOT NULL
   OR EXISTS(SELECT FROM pg_attribute WHERE attrelid='tll_bridge_private.account_generations'::regclass
     AND attname='logout_session_id' AND NOT attisdropped)
   OR to_regprocedure('tll_customer_private.account_logout_token_source(uuid,uuid)') IS NOT NULL
   OR to_regprocedure('tll_broker_private.account_logout(uuid)') IS NOT NULL
   OR to_regprocedure('tll_provisional_private.account_logout(uuid)') IS NOT NULL
   OR to_regprocedure('tll_bridge_private.account_logout_repository(text,jsonb)') IS NOT NULL THEN
   RAISE EXCEPTION 'Account logout installation unavailable'; END IF;
 IF (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_bridge_private.account_repository(text,jsonb)'::regprocedure)<>'19b5b2d29289eaf3026454443418063d'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_bridge_private.account_lock()'::regprocedure)<>'1a1387ee95f4560c6888d238926cffcf'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_customer_private.account_token_source(uuid,uuid)'::regprocedure)<>'c56884908bf561fdad2eeb6169b94f44'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_bridge_private.terminal(uuid,text)'::regprocedure)<>'26be94ca67bcf38d9d4ba815707e407e'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_broker_private.bridge_terminal(jsonb,text)'::regprocedure)<>'30090d51de7a26db5740eeeb5f44e947'
   OR (SELECT md5(prosrc) FROM pg_proc WHERE oid='tll_provisional_private.bridge_terminal(jsonb,text)'::regprocedure)<>'c3402aeaa075c957da839b82769e256a' THEN
   RAISE EXCEPTION 'Reviewed logout prerequisite source required'; END IF;
 FOREACH r IN ARRAY ARRAY['tll_bridge_owner','tll_customer_owner','tll_broker_owner','tll_provisional_owner'] LOOP
   IF NOT (SELECT rolsuper FROM pg_roles WHERE rolname=current_user) AND NOT EXISTS(SELECT FROM pg_auth_members
     WHERE roleid=r::regrole AND member=current_user::regrole AND admin_option AND NOT inherit_option AND NOT set_option) THEN
     RAISE EXCEPTION 'Reviewed owner upgrade authority required'; END IF;
   EXECUTE format('GRANT %I TO %I WITH INHERIT TRUE, SET TRUE',r,installer);
 END LOOP;
 PERFORM tll_bridge_private.gate();
 IF tll_bridge_private.operator_status()->'enabled'<>'false'::jsonb OR tll_customer_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_broker_private.operator_status()->'enabled'<>'false'::jsonb OR tll_provisional_private.operator_status()->'enabled'<>'false'::jsonb THEN
   RAISE EXCEPTION 'Disable all account repositories before logout upgrade'; END IF;
END $preflight$;

ALTER TABLE tll_bridge_private.account_generations ADD COLUMN logout_session_id uuid;
CREATE TABLE tll_bridge_private.account_logouts(
 operation_id uuid PRIMARY KEY,
 user_id uuid NOT NULL REFERENCES auth.users(id),
 session_id uuid NOT NULL,
 generation bigint NOT NULL CHECK(generation>0),
 transaction_id uuid,
 receipt_id uuid,
 upstream_hint boolean NOT NULL,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 CHECK((transaction_id IS NULL)=(receipt_id IS NULL))
);

-- Logout may need an ID-token hint after the access token has expired. The
-- server adapter still receives only the original authenticated envelope.
CREATE FUNCTION tll_customer_private.account_logout_token_source(rid uuid,expected_receipt uuid) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $source$
DECLARE r tll_customer_private.shopify_proofs%ROWTYPE;
BEGIN
 PERFORM 1 FROM tll_customer_private.control WHERE singleton FOR UPDATE;
 SELECT * INTO r FROM tll_customer_private.shopify_proofs
  WHERE transaction_id=rid AND receipt_id=expected_receipt AND state='verified' AND tokens IS NOT NULL;
 IF NOT FOUND THEN RETURN NULL; END IF;
 RETURN jsonb_build_object('transactionId',r.transaction_id,'receiptId',r.receipt_id,
   'shopId',r.shop_id,'issuer',r.issuer,'subject',r.subject,'innerPkceChallenge',r.inner_challenge,
   'verifiedAt',floor(extract(epoch FROM r.verified_at)*1000)::bigint,
   'proofExpiresAt',floor(extract(epoch FROM r.proof_expires_at)*1000)::bigint,'proofFence',r.fence::text,
   'accessExpiresAt',floor(extract(epoch FROM r.access_expires_at)*1000)::bigint,'tokens',r.tokens);
END $source$;

CREATE FUNCTION tll_broker_private.account_logout(uid uuid) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $logout$
DECLARE changed bigint;
BEGIN
 PERFORM 1 FROM tll_broker_private.control WHERE singleton FOR UPDATE;
 PERFORM 1 FROM tll_broker_private.subjects WHERE bound_user_id=uid OR pending_user_id=uid FOR UPDATE;
 UPDATE tll_broker_private.flows SET status='cancelled',generation=generation+1,
   fence=nextval('tll_broker_private.fences')
  WHERE status NOT IN ('held','cancelled') AND (
    sub IN (SELECT sub FROM tll_broker_private.subjects WHERE bound_user_id=uid OR pending_user_id=uid)
    OR registration->'target'->>'userId'=uid::text);
 GET DIAGNOSTICS changed=ROW_COUNT; RETURN changed;
END $logout$;

CREATE FUNCTION tll_provisional_private.account_logout(uid uuid) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $logout$
DECLARE changed bigint;
BEGIN
 PERFORM 1 FROM tll_provisional_private.control WHERE singleton FOR UPDATE;
 UPDATE tll_provisional_private.intents SET state='cancelled',material=NULL,generation=generation+1,
   fence=nextval('tll_provisional_private.fences')
  WHERE state NOT IN ('held','cancelled') AND metadata->'original'->>'userId'=uid::text;
 GET DIAGNOSTICS changed=ROW_COUNT; RETURN changed;
END $logout$;

CREATE FUNCTION tll_bridge_private.account_logout_repository(op text,p jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $repository$
DECLARE oid uuid; uid uuid; sid uuid; ts timestamptz:=clock_timestamp(); source jsonb;
 prior tll_bridge_private.account_logouts%ROWTYPE; gen tll_bridge_private.account_generations%ROWTYPE;
 final tll_bridge_private.finalizations%ROWTYPE; rid uuid; next_generation bigint;
BEGIN
 IF op IS DISTINCT FROM 'logout' OR jsonb_typeof(p) IS DISTINCT FROM 'object' OR octet_length(p::text)>65536
   OR p-ARRAY['operationId','userId','sessionId']<>'{}'::jsonb
   OR COALESCE(p->>'operationId','') !~ '^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$'
   OR COALESCE(p->>'userId','') !~ '^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$'
   OR COALESCE(p->>'sessionId','') !~ '^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' THEN
   RAISE EXCEPTION 'Invalid account logout request' USING ERRCODE='22023'; END IF;
 oid:=(p->>'operationId')::uuid; uid:=(p->>'userId')::uuid; sid:=(p->>'sessionId')::uuid;
 PERFORM tll_bridge_private.account_lock(); PERFORM tll_customer_private.final_lock();
 SELECT * INTO prior FROM tll_bridge_private.account_logouts WHERE operation_id=oid;
 IF FOUND THEN
   IF prior.user_id<>uid OR prior.session_id<>sid THEN RETURN jsonb_build_object('status','rejected'); END IF;
   RETURN jsonb_build_object('status','local_revoked','operationId',oid,'userId',uid,'sessionId',sid,
     'generation',prior.generation::text,'upstreamLogout','not_required');
 END IF;
 INSERT INTO tll_bridge_private.account_generations(user_id) VALUES(uid) ON CONFLICT DO NOTHING;
 SELECT * INTO STRICT gen FROM tll_bridge_private.account_generations WHERE user_id=uid FOR UPDATE;
 IF gen.logout_session_id=sid THEN
   INSERT INTO tll_bridge_private.account_logouts(operation_id,user_id,session_id,generation,upstream_hint)
    VALUES(oid,uid,sid,gen.generation,false);
   RETURN jsonb_build_object('status','local_revoked','operationId',oid,'userId',uid,'sessionId',sid,
     'generation',gen.generation::text,'upstreamLogout','not_required');
 END IF;

 SELECT * INTO final FROM tll_bridge_private.finalizations WHERE user_id=uid AND state='reconciled'
  ORDER BY reconciled_at DESC,transaction_id DESC LIMIT 1 FOR UPDATE;
 IF FOUND THEN source:=tll_customer_private.account_logout_token_source(final.transaction_id,final.proof_receipt_id); END IF;
 next_generation:=gen.generation+1;
 UPDATE tll_bridge_private.account_generations SET generation=next_generation,logout_session_id=sid,updated_at=ts WHERE user_id=uid;
 UPDATE tll_bridge_private.account_operations SET state='held',completed_at=COALESCE(completed_at,ts)
  WHERE user_id=uid AND state IN ('claimed','completed');

 FOR rid IN
   SELECT transaction_id FROM tll_bridge_private.finalizations WHERE user_id=uid
   UNION SELECT id FROM tll_bridge_private.grants WHERE source_snapshot->'metadata'->'original'->>'userId'=uid::text
 LOOP PERFORM tll_bridge_private.terminal(rid,'cancelled'); END LOOP;
 UPDATE tll_bridge_private.finalizations SET state='held',generation=generation+1,
   fence=nextval('tll_bridge_private.final_fences'),user_id=NULL,identity_id=NULL,authenticated_at=NULL,
   checked_at=NULL,session_expires_at=NULL,session_material=NULL,reconciled_at=NULL WHERE user_id=uid;
 UPDATE tll_bridge_private.grants SET state='cancelled',release_hash=NULL
  WHERE source_snapshot->'metadata'->'original'->>'userId'=uid::text AND state NOT IN ('held','cancelled');
 PERFORM tll_broker_private.account_logout(uid); PERFORM tll_provisional_private.account_logout(uid);

 INSERT INTO tll_bridge_private.account_logouts(operation_id,user_id,session_id,generation,transaction_id,receipt_id,upstream_hint,created_at)
  VALUES(oid,uid,sid,next_generation,final.transaction_id,final.proof_receipt_id,source IS NOT NULL,ts);
 RETURN jsonb_build_object('status','local_revoked','operationId',oid,'userId',uid,'sessionId',sid,
   'generation',next_generation::text,'upstreamLogout',CASE WHEN source IS NULL THEN 'not_required' ELSE 'pending' END,
   'tokenSource',source);
END $repository$;

DO $secure$
DECLARE installer name:=current_user; role_name text;
BEGIN
 ALTER TABLE tll_bridge_private.account_logouts OWNER TO tll_bridge_owner;
 ALTER TABLE tll_bridge_private.account_logouts ENABLE ROW LEVEL SECURITY;
 ALTER FUNCTION tll_customer_private.account_logout_token_source(uuid,uuid) OWNER TO tll_customer_owner;
 ALTER FUNCTION tll_broker_private.account_logout(uuid) OWNER TO tll_broker_owner;
 ALTER FUNCTION tll_provisional_private.account_logout(uuid) OWNER TO tll_provisional_owner;
 ALTER FUNCTION tll_bridge_private.account_logout_repository(text,jsonb) OWNER TO tll_bridge_owner;
 REVOKE ALL ON TABLE tll_bridge_private.account_logouts FROM PUBLIC;
 REVOKE ALL ON FUNCTION tll_customer_private.account_logout_token_source(uuid,uuid),tll_broker_private.account_logout(uuid),
   tll_provisional_private.account_logout(uuid),tll_bridge_private.account_logout_repository(text,jsonb) FROM PUBLIC;
 GRANT EXECUTE ON FUNCTION tll_customer_private.account_logout_token_source(uuid,uuid),tll_broker_private.account_logout(uuid),
   tll_provisional_private.account_logout(uuid) TO tll_bridge_owner;
 GRANT EXECUTE ON FUNCTION tll_bridge_private.account_logout_repository(text,jsonb) TO tll_bridge_executor;
 FOREACH role_name IN ARRAY ARRAY['tll_bridge_owner','tll_customer_owner','tll_broker_owner','tll_provisional_owner'] LOOP
   IF (SELECT rolsuper FROM pg_roles WHERE rolname=current_user) THEN
     EXECUTE format('GRANT %I TO %I WITH ADMIN TRUE, INHERIT FALSE, SET FALSE',role_name,installer);
   ELSE EXECUTE format('REVOKE %I FROM %I GRANTED BY %I',role_name,installer,installer); END IF;
 END LOOP;
END $secure$;

DO $postflight$
DECLARE role_name text;
BEGIN
 IF tll_bridge_private.operator_status()->'enabled'<>'false'::jsonb OR tll_customer_private.operator_status()->'enabled'<>'false'::jsonb
   OR tll_broker_private.operator_status()->'enabled'<>'false'::jsonb OR tll_provisional_private.operator_status()->'enabled'<>'false'::jsonb THEN
   RAISE EXCEPTION 'Unexpected account logout activation'; END IF;
 FOREACH role_name IN ARRAY ARRAY['anon','authenticated','service_role','tll_customer_executor','tll_broker_executor','tll_provisional_executor','tll_bridge_executor'] LOOP
   IF has_table_privilege(role_name,'tll_bridge_private.account_logouts','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN')
     OR has_any_column_privilege(role_name,'tll_bridge_private.account_logouts','SELECT,INSERT,UPDATE,REFERENCES') THEN
     RAISE EXCEPTION 'Unexpected account logout data authority'; END IF;
 END LOOP;
 IF NOT has_function_privilege('tll_bridge_executor','tll_bridge_private.account_logout_repository(text,jsonb)','EXECUTE')
   OR has_function_privilege('service_role','tll_bridge_private.account_logout_repository(text,jsonb)','EXECUTE')
   OR has_function_privilege('tll_bridge_executor','tll_customer_private.account_logout_token_source(uuid,uuid)','EXECUTE')
   OR has_function_privilege('tll_bridge_executor','tll_broker_private.account_logout(uuid)','EXECUTE')
   OR has_function_privilege('tll_bridge_executor','tll_provisional_private.account_logout(uuid)','EXECUTE') THEN
   RAISE EXCEPTION 'Unexpected account logout function authority'; END IF;
END $postflight$;
INSERT INTO tll_staging_private.applied_migrations(version,source_sha256) VALUES ('202609180012_customer_shopify_proof_repository','c0b105293f01b79329c050a16702ad98123b744b63c85a63dbce8c1a2b7b6e61'),('202609180013_customer_final_reconciliation','4dc438d016fbe2f4e1a5cac7c76aa9f48f0bde369488702661f516fdd88841a6'),('202609180014_staging_cart_account_transition','99b3737bcffe7957e5eeb64d46566953ad2a9e8b4d045fdaf9e995a223a29061'),('202609180015_customer_account_operations','dfaafaa6ee121c5f33e7f1aff6a83f14d972455ef5fdd0ed2a49411f8b15c0ee'),('202609180016_customer_account_logout','b512d9d18599b60a18ea20d94b3502d94c5735c1ac20bbb76321efd46dea8349');
DO $tll_install_postflight$
DECLARE installed integer;
BEGIN
 SELECT count(*) INTO installed FROM tll_staging_private.applied_migrations WHERE (version,source_sha256) IN (VALUES ('202609180012_customer_shopify_proof_repository','c0b105293f01b79329c050a16702ad98123b744b63c85a63dbce8c1a2b7b6e61'),('202609180013_customer_final_reconciliation','4dc438d016fbe2f4e1a5cac7c76aa9f48f0bde369488702661f516fdd88841a6'),('202609180014_staging_cart_account_transition','99b3737bcffe7957e5eeb64d46566953ad2a9e8b4d045fdaf9e995a223a29061'),('202609180015_customer_account_operations','dfaafaa6ee121c5f33e7f1aff6a83f14d972455ef5fdd0ed2a49411f8b15c0ee'),('202609180016_customer_account_logout','b512d9d18599b60a18ea20d94b3502d94c5735c1ac20bbb76321efd46dea8349'));
 IF installed<>5 OR (SELECT count(*) FROM tll_staging_private.applied_migrations)<>15
   OR tll_customer_private.operator_status()->'enabled'<>'false'::jsonb OR coalesce((SELECT enabled FROM tll_cart_private.control WHERE singleton),true)
   OR tll_broker_private.operator_status()->'enabled'<>'false'::jsonb OR tll_provisional_private.operator_status()->'enabled'<>'false'::jsonb OR tll_bridge_private.operator_status()->'enabled'<>'false'::jsonb
   OR to_regclass('tll_customer_private.shopify_proofs') IS NULL OR to_regclass('tll_bridge_private.finalizations') IS NULL OR to_regclass('tll_cart_private.transitions') IS NULL OR to_regclass('tll_bridge_private.account_generations') IS NULL OR to_regclass('tll_bridge_private.account_logouts') IS NULL
   OR EXISTS(SELECT 1 FROM tll_customer_private.shopify_proofs) OR EXISTS(SELECT 1 FROM tll_bridge_private.finalizations) OR EXISTS(SELECT 1 FROM tll_cart_private.transitions) OR EXISTS(SELECT 1 FROM tll_bridge_private.account_generations) OR EXISTS(SELECT 1 FROM tll_bridge_private.account_operations) OR EXISTS(SELECT 1 FROM tll_bridge_private.account_logouts)
   OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tll_customer_private.shopify_proofs'::regclass) OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tll_bridge_private.finalizations'::regclass) OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tll_cart_private.transitions'::regclass) OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tll_bridge_private.account_generations'::regclass) OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tll_bridge_private.account_logouts'::regclass)
   OR EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member WHERE granted.rolname IN ('tll_customer_owner','tll_cart_owner','tll_broker_owner','tll_provisional_owner','tll_bridge_owner') AND member.rolname=current_user AND (NOT e.admin_option OR e.inherit_option OR e.set_option)) THEN RAISE EXCEPTION 'Disabled migration postflight mismatch'; END IF;
END $tll_install_postflight$;
SELECT jsonb_build_object('installId','tll-staging-disabled-migrations-012-016/v1','projectRef','qdmvngjwkcsilzmqksme','status','PASS','migrationCount',5,'controlsDisabled',true,'objectsPresent',true) AS tll_disabled_migration_postflight;
COMMIT;
