-- GENERATED by scripts/staging-generation-21-recovery.mjs from the pinned generation-6 recovery; do not edit.
-- TLL staging recovery after migrations 012--016 only. Confirm project
-- qdmvngjwkcsilzmqksme outside this file; production wrhgscovsgsudtedbljr is excluded.
-- This transaction preserves rows/journals, does not DROP objects or touch auth.users,
-- and uses temporary, per-schema SET grants derived only from pre-existing exact
-- ADMIN TRUE / INHERIT FALSE / SET FALSE operator edges.
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';

DO $preflight$
DECLARE r text; operator_name name:=session_user;
BEGIN
  IF current_database()<>'postgres' OR current_user<>'postgres' OR session_user<>'postgres'
    OR current_user<>session_user OR current_setting('server_version_num')::int<170000
    OR (SELECT rolsuper OR NOT rolcreaterole FROM pg_roles WHERE rolname=operator_name) THEN
    RAISE EXCEPTION 'Recovery requires exact managed non-superuser staging postgres operator session';
  END IF;
  IF to_regclass('tll_staging_private.environment') IS NULL
    OR (SELECT count(*) FROM tll_staging_private.environment)<>1
    OR NOT EXISTS(SELECT 1 FROM tll_staging_private.environment WHERE singleton
      AND environment='tll-hosted-staging-v1'
      AND operator_project_ref='qdmvngjwkcsilzmqksme'
      AND operator_context='supabase-dashboard:qdmvngjwkcsilzmqksme:staging-bootstrap:reviewed'
      AND identity_basis='explicit-operator-dashboard-binding'
      AND bootstrap_version='2026-09-15-v2'
      AND source_commit='a50e37ff05d8e731dc8ffceea1e96492079e5ff3'
      AND integrity_sha256='2d5175eb47a891ca626d635281fbb28237b16bec0d89eebe168455935117922c')
    OR EXISTS(SELECT 1 FROM tll_staging_private.environment WHERE operator_project_ref='wrhgscovsgsudtedbljr') THEN
    RAISE EXCEPTION 'Staging binding or reviewed bootstrap v2 mismatch';
  END IF;
  FOREACH r IN ARRAY ARRAY[
    'tll_customer_private.control','tll_cart_private.control','tll_broker_private.control','tll_provisional_private.control','tll_bridge_private.control',
    'tll_customer_private.shopify_proofs','tll_cart_private.sessions','tll_cart_private.operations','tll_cart_private.transitions',
    'tll_broker_private.flows','tll_provisional_private.intents','tll_bridge_private.grants','tll_bridge_private.finalizations',
    'tll_bridge_private.account_generations','tll_bridge_private.account_operations','tll_bridge_private.account_logouts'
  ] LOOP
    -- to_regclass resolves through schema privileges, which the deliberately
    -- unprivileged operator lacks before the temporary owner SET edge exists.
    IF NOT EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
      WHERE n.nspname=split_part(r,'.',1) AND c.relname=split_part(r,'.',2)) THEN
      RAISE EXCEPTION 'Recovery requires reviewed 012--016 relation: %',r;
    END IF;
  END LOOP;
  FOREACH r IN ARRAY ARRAY['tll_customer_owner','tll_cart_owner','tll_broker_owner','tll_provisional_owner','tll_bridge_owner',
    'tll_customer_executor','tll_cart_gateway','tll_broker_executor','tll_provisional_executor','tll_bridge_executor',
    'tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
    IF NOT EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid
      WHERE granted.rolname=r AND e.member=operator_name::regrole AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option) THEN
      RAISE EXCEPTION 'Missing exact ADMIN-only operator edge: %',r;
    END IF;
  END LOOP;
  FOREACH r IN ARRAY ARRAY['tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
    IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r) THEN RAISE EXCEPTION 'Runtime role is absent: %',r; END IF;
  END LOOP;
  IF EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member
    WHERE member.rolname IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime')
      AND NOT ((granted.rolname,member.rolname) IN (('tll_customer_executor','tll_customer_runtime'),('tll_cart_gateway','tll_cart_runtime'),
        ('tll_broker_executor','tll_broker_runtime'),('tll_provisional_executor','tll_provisional_runtime'),('tll_bridge_executor','tll_bridge_runtime')))) THEN
    RAISE EXCEPTION 'Unexpected runtime membership; refuse broad role recovery';
  END IF;
  IF EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member
    WHERE (granted.rolname,member.rolname) IN (('tll_customer_executor','tll_customer_runtime'),('tll_cart_gateway','tll_cart_runtime'),
      ('tll_broker_executor','tll_broker_runtime'),('tll_provisional_executor','tll_provisional_runtime'),('tll_bridge_executor','tll_bridge_runtime'))
      AND e.grantor<>operator_name::regrole) THEN
    RAISE EXCEPTION 'Runtime execution edge was not granted by this recovery operator';
  END IF;
  IF has_table_privilege(operator_name,(SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='tll_customer_private' AND c.relname='control'),'UPDATE')
    OR has_table_privilege(operator_name,(SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='tll_broker_private' AND c.relname='control'),'UPDATE')
    OR has_table_privilege(operator_name,(SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='tll_provisional_private' AND c.relname='control'),'UPDATE')
    OR has_table_privilege(operator_name,(SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='tll_bridge_private' AND c.relname='control'),'UPDATE') THEN
    RAISE EXCEPTION 'Operator has unreviewed direct private write authority';
  END IF;
  -- Cart is intentionally owned by its recorded installation operator. Its
  -- NOLOGIN cart owner is denied control UPDATE by the reviewed RLS policy.
  IF (SELECT operator_oid FROM tll_cart_private.control WHERE singleton)<>operator_name::regrole::oid
    OR (SELECT pg_get_userbyid(relowner) FROM pg_class WHERE oid='tll_cart_private.control'::regclass)<>operator_name THEN
    RAISE EXCEPTION 'Cart recovery requires the original recorded cart table owner';
  END IF;
  IF NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='tll_bridge_private' AND p.proname='account_logout_repository' AND pg_get_function_identity_arguments(p.oid)='op text, p jsonb') THEN
    RAISE EXCEPTION 'Recovery requires migration 016';
  END IF;
END $preflight$;

DO $runtime_window_preflight$
DECLARE r text; marker text; parsed jsonb; first_marker text; expires_text text; expires_at timestamptz;
  active_count integer:=0; retired_count integer:=0; operator_name name:=session_user; idempotent boolean;
BEGIN
  FOREACH r IN ARRAY ARRAY['tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
    SELECT shobj_description(oid,'pg_authid') INTO marker FROM pg_roles WHERE rolname=r;
    IF marker IS NULL OR marker !~ '^tll-runtime-window/v1 [{].*[}]$' THEN
      RAISE EXCEPTION 'Runtime role lacks parseable tll-runtime-window/v1 marker: %',r;
    END IF;
    BEGIN parsed:=substring(marker FROM '^tll-runtime-window/v1 ([{].*[}])$')::jsonb; EXCEPTION WHEN others THEN
      RAISE EXCEPTION 'Runtime marker JSON is invalid: %',r;
    END;
    IF jsonb_typeof(parsed) IS DISTINCT FROM 'object' OR (SELECT count(*) FROM jsonb_object_keys(parsed)) IS DISTINCT FROM 5
      OR NOT (parsed ?& ARRAY['projectRef','generation','windowId','expiresAt','state'])
      OR jsonb_typeof(parsed->'projectRef') IS DISTINCT FROM 'string' OR parsed->>'projectRef' IS DISTINCT FROM 'qdmvngjwkcsilzmqksme'
      OR jsonb_typeof(parsed->'generation') IS DISTINCT FROM 'number' OR parsed->>'generation' IS DISTINCT FROM '21'
      OR jsonb_typeof(parsed->'windowId') IS DISTINCT FROM 'string' OR parsed->>'windowId' IS DISTINCT FROM 'a5511645-77af-4fc9-9e4c-f5c8a474d5fa'
      OR jsonb_typeof(parsed->'expiresAt') IS DISTINCT FROM 'string'
      OR jsonb_typeof(parsed->'state') IS DISTINCT FROM 'string'
      OR (parsed->>'state' IS DISTINCT FROM 'active' AND parsed->>'state' IS DISTINCT FROM 'retired') THEN
      RAISE EXCEPTION 'Runtime marker target, generation or window mismatch: %',r;
    END IF;
    BEGIN expires_at:=(parsed->>'expiresAt')::timestamptz; EXCEPTION WHEN others THEN
      RAISE EXCEPTION 'Runtime marker expiry is invalid: %',r;
    END;
    IF parsed->>'state'='active' AND ('UNSET_REQUIRES_REVIEWED_ARMING_DIFF'='UNSET_REQUIRES_REVIEWED_ARMING_DIFF'
      OR parsed->>'expiresAt' IS DISTINCT FROM 'UNSET_REQUIRES_REVIEWED_ARMING_DIFF'
      OR NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r AND rolcanlogin AND rolvaliduntil=expires_at)
      OR NOT EXISTS(SELECT 1 FROM pg_authid WHERE rolname=r AND rolpassword IS NOT NULL)) THEN
      RAISE EXCEPTION 'Active Gen21 credential drift shape mismatch: %',r;
    ELSIF parsed->>'state'='retired' AND (EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r AND (rolcanlogin OR rolvaliduntil IS DISTINCT FROM 'infinity'::timestamptz))
      OR EXISTS(SELECT 1 FROM pg_authid WHERE rolname=r AND rolpassword IS NOT NULL)) THEN
      RAISE EXCEPTION 'Retired Gen21 credential state is not inert: %',r;
    END IF;
    IF first_marker IS NULL THEN first_marker:=marker; expires_text:=parsed->>'expiresAt';
    ELSIF marker IS DISTINCT FROM first_marker OR parsed->>'expiresAt' IS DISTINCT FROM expires_text THEN RAISE EXCEPTION 'Runtime markers are partial or mixed'; END IF;
    IF parsed->>'state'='active' THEN active_count:=active_count+1; ELSE retired_count:=retired_count+1; END IF;
  END LOOP;
  IF active_count=5 THEN
    idempotent:=false;
  ELSIF retired_count=5 THEN
    idempotent:=true;
    IF NOT pg_has_role(operator_name,'pg_read_all_stats','MEMBER') THEN RAISE EXCEPTION 'Already-retired recovery requires existing pg_read_all_stats session visibility'; END IF;
    IF EXISTS(SELECT 1 FROM pg_stat_activity WHERE backend_type='client backend' AND usename IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime')) THEN
      RAISE EXCEPTION 'Already-retired recovery refuses remaining runtime sessions';
    END IF;
  ELSE RAISE EXCEPTION 'Runtime markers are partial or mixed'; END IF;
  PERFORM set_config('tll.recovery_idempotent',CASE WHEN idempotent THEN 'true' ELSE 'false' END,true);
  PERFORM set_config('tll.recovery_expires_at',expires_text,true);
END $runtime_window_preflight$;

DO $acquire_set_edges$
DECLARE operator_name name:=session_user; r text; marker text; parsed jsonb; first_marker text;
BEGIN
  FOREACH r IN ARRAY ARRAY['tll_customer_owner','tll_cart_owner','tll_broker_owner','tll_provisional_owner','tll_bridge_owner'] LOOP
    EXECUTE format('GRANT %I TO %I WITH INHERIT TRUE, SET TRUE',r,operator_name);
  END LOOP;
END $acquire_set_edges$;

SET LOCAL ROLE tll_customer_owner;
LOCK TABLE tll_customer_private.control,tll_customer_private.shopify_proofs IN SHARE ROW EXCLUSIVE MODE;
UPDATE tll_customer_private.control SET enabled=false,changed_at=clock_timestamp(),reason_code='recovery_retired' WHERE current_setting('tll.recovery_idempotent',true)<>'true';
UPDATE tll_customer_private.shopify_proofs SET state='held',fence=nextval('tll_customer_private.shopify_proof_fences'),attempt_material=NULL,
  receipt_id=NULL,shop_id=NULL,issuer=NULL,subject=NULL,verified_at=NULL,proof_expires_at=NULL,access_expires_at=NULL,tokens=NULL WHERE state<>'held' AND current_setting('tll.recovery_idempotent',true)<>'true';
DO $verify_customer_drain$ BEGIN
  IF EXISTS(SELECT 1 FROM tll_customer_private.control WHERE enabled) OR EXISTS(SELECT 1 FROM tll_customer_private.shopify_proofs WHERE state<>'held') THEN
    RAISE EXCEPTION 'Customer recovery drain failed';
  END IF;
END $verify_customer_drain$;
RESET ROLE;

LOCK TABLE tll_cart_private.control,tll_cart_private.sessions,tll_cart_private.operations,tll_cart_private.transitions IN SHARE ROW EXCLUSIVE MODE;
UPDATE tll_cart_private.control SET enabled=false WHERE current_setting('tll.recovery_idempotent',true)<>'true';
UPDATE tll_cart_private.sessions SET phase='held',lease_until=NULL WHERE phase='working' AND current_setting('tll.recovery_idempotent',true)<>'true';
UPDATE tll_cart_private.operations SET state='held' WHERE state='working' AND current_setting('tll.recovery_idempotent',true)<>'true';
UPDATE tll_cart_private.transitions SET state='held',lease_until=NULL WHERE state='claimed' AND current_setting('tll.recovery_idempotent',true)<>'true';
DO $verify_cart_drain$ BEGIN
  IF EXISTS(SELECT 1 FROM tll_cart_private.control WHERE enabled) OR EXISTS(SELECT 1 FROM tll_cart_private.sessions WHERE phase='working')
    OR EXISTS(SELECT 1 FROM tll_cart_private.operations WHERE state='working') OR EXISTS(SELECT 1 FROM tll_cart_private.transitions WHERE state='claimed') THEN
    RAISE EXCEPTION 'Cart recovery drain failed';
  END IF;
END $verify_cart_drain$;

SET LOCAL ROLE tll_broker_owner;
LOCK TABLE tll_broker_private.control,tll_broker_private.flows IN SHARE ROW EXCLUSIVE MODE;
UPDATE tll_broker_private.control SET enabled=false,changed_at=clock_timestamp(),reason_code='recovery_retired' WHERE current_setting('tll.recovery_idempotent',true)<>'true';
UPDATE tll_broker_private.flows SET status='cancelled',generation=generation+1,fence=nextval('tll_broker_private.fences') WHERE status NOT IN ('held','cancelled') AND current_setting('tll.recovery_idempotent',true)<>'true';
DO $verify_broker_drain$ BEGIN
  IF EXISTS(SELECT 1 FROM tll_broker_private.control WHERE enabled) OR EXISTS(SELECT 1 FROM tll_broker_private.flows WHERE status NOT IN ('held','cancelled')) THEN
    RAISE EXCEPTION 'Broker recovery drain failed';
  END IF;
END $verify_broker_drain$;
RESET ROLE;

SET LOCAL ROLE tll_provisional_owner;
LOCK TABLE tll_provisional_private.control,tll_provisional_private.intents IN SHARE ROW EXCLUSIVE MODE;
UPDATE tll_provisional_private.control SET enabled=false,changed_at=clock_timestamp(),reason_code='recovery_retired' WHERE current_setting('tll.recovery_idempotent',true)<>'true';
UPDATE tll_provisional_private.intents SET state='cancelled',material=NULL,generation=generation+1,fence=nextval('tll_provisional_private.fences') WHERE state NOT IN ('held','cancelled') AND current_setting('tll.recovery_idempotent',true)<>'true';
DO $verify_provisional_drain$ BEGIN
  IF EXISTS(SELECT 1 FROM tll_provisional_private.control WHERE enabled) OR EXISTS(SELECT 1 FROM tll_provisional_private.intents WHERE state NOT IN ('held','cancelled')) THEN
    RAISE EXCEPTION 'Provisional recovery drain failed';
  END IF;
END $verify_provisional_drain$;
RESET ROLE;

SET LOCAL ROLE tll_bridge_owner;
LOCK TABLE tll_bridge_private.control,tll_bridge_private.grants,tll_bridge_private.finalizations,tll_bridge_private.account_generations,tll_bridge_private.account_operations IN SHARE ROW EXCLUSIVE MODE;
UPDATE tll_bridge_private.control SET enabled=false,epoch=epoch+1,changed_at=clock_timestamp(),reason_code='recovery_retired' WHERE current_setting('tll.recovery_idempotent',true)<>'true';
UPDATE tll_bridge_private.grants SET state='cancelled',release_hash=NULL WHERE state NOT IN ('held','cancelled') AND current_setting('tll.recovery_idempotent',true)<>'true';
UPDATE tll_bridge_private.finalizations SET state='held',generation=generation+1,fence=nextval('tll_bridge_private.final_fences'),callback_material=NULL,
  provisional_material=NULL,user_id=NULL,identity_id=NULL,authenticated_at=NULL,checked_at=NULL,session_expires_at=NULL,session_material=NULL,reconciled_at=NULL WHERE state<>'held' AND current_setting('tll.recovery_idempotent',true)<>'true';
UPDATE tll_bridge_private.account_operations SET state='held',completed_at=COALESCE(completed_at,clock_timestamp()) WHERE state IN ('claimed','completed') AND current_setting('tll.recovery_idempotent',true)<>'true';
UPDATE tll_bridge_private.account_generations SET generation=generation+1,logout_session_id=NULL,updated_at=clock_timestamp() WHERE current_setting('tll.recovery_idempotent',true)<>'true';
DO $verify_bridge_drain$ BEGIN
  IF EXISTS(SELECT 1 FROM tll_bridge_private.control WHERE enabled) OR EXISTS(SELECT 1 FROM tll_bridge_private.grants WHERE state NOT IN ('held','cancelled'))
    OR EXISTS(SELECT 1 FROM tll_bridge_private.finalizations WHERE state<>'held') OR EXISTS(SELECT 1 FROM tll_bridge_private.account_operations WHERE state IN ('claimed','completed')) THEN
    RAISE EXCEPTION 'Bridge recovery drain failed';
  END IF;
END $verify_bridge_drain$;
RESET ROLE;

DO $retire_runtime_roles$
DECLARE r text; marker text;
BEGIN
  IF current_setting('tll.recovery_idempotent',true)<>'true' THEN
    FOREACH r IN ARRAY ARRAY['tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
      EXECUTE format('ALTER ROLE %I NOLOGIN PASSWORD NULL VALID UNTIL %L',r,'infinity');
    END LOOP;
    REVOKE tll_customer_executor FROM tll_customer_runtime;
    REVOKE tll_cart_gateway FROM tll_cart_runtime;
    REVOKE tll_broker_executor FROM tll_broker_runtime;
    REVOKE tll_provisional_executor FROM tll_provisional_runtime;
    REVOKE tll_bridge_executor FROM tll_bridge_runtime;
    marker:='tll-runtime-window/v1 '||jsonb_build_object('expiresAt',current_setting('tll.recovery_expires_at',true),'generation',21,'projectRef','qdmvngjwkcsilzmqksme','state','retired','windowId','a5511645-77af-4fc9-9e4c-f5c8a474d5fa')::text;
    FOREACH r IN ARRAY ARRAY['tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
      EXECUTE format('COMMENT ON ROLE %I IS %L',r,marker);
    END LOOP;
  END IF;
END $retire_runtime_roles$;

DO $restore_edges_and_postflight$
DECLARE operator_name name:=session_user; r text; marker text; parsed jsonb; first_marker text;
BEGIN
  FOREACH r IN ARRAY ARRAY['tll_customer_owner','tll_cart_owner','tll_broker_owner','tll_provisional_owner','tll_bridge_owner'] LOOP
    EXECUTE format('REVOKE %I FROM %I GRANTED BY %I',r,operator_name,operator_name);
    IF NOT EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid
      WHERE granted.rolname=r AND e.member=operator_name::regrole AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option)
      OR pg_has_role(operator_name,r,'USAGE') OR pg_has_role(operator_name,r,'SET') THEN RAISE EXCEPTION 'Owner edge was not restored to ADMIN-only: %',r; END IF;
  END LOOP;
  FOREACH r IN ARRAY ARRAY['tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
    SELECT shobj_description(oid,'pg_authid') INTO marker FROM pg_roles WHERE rolname=r;
    IF marker IS NULL OR marker !~ '^tll-runtime-window/v1 [{].*[}]$' THEN RAISE EXCEPTION 'Retired runtime marker is absent or malformed: %',r; END IF;
    BEGIN parsed:=substring(marker FROM '^tll-runtime-window/v1 ([{].*[}])$')::jsonb; EXCEPTION WHEN others THEN RAISE EXCEPTION 'Retired runtime marker JSON invalid: %',r; END;
    IF jsonb_typeof(parsed) IS DISTINCT FROM 'object' OR (SELECT count(*) FROM jsonb_object_keys(parsed)) IS DISTINCT FROM 5
      OR NOT (parsed ?& ARRAY['projectRef','generation','windowId','expiresAt','state'])
      OR jsonb_typeof(parsed->'projectRef') IS DISTINCT FROM 'string' OR parsed->>'projectRef' IS DISTINCT FROM 'qdmvngjwkcsilzmqksme'
      OR jsonb_typeof(parsed->'generation') IS DISTINCT FROM 'number' OR parsed->>'generation' IS DISTINCT FROM '21'
      OR jsonb_typeof(parsed->'windowId') IS DISTINCT FROM 'string' OR parsed->>'windowId' IS DISTINCT FROM 'a5511645-77af-4fc9-9e4c-f5c8a474d5fa'
      OR jsonb_typeof(parsed->'expiresAt') IS DISTINCT FROM 'string'
      OR jsonb_typeof(parsed->'state') IS DISTINCT FROM 'string' OR parsed->>'state' IS DISTINCT FROM 'retired' THEN RAISE EXCEPTION 'Retired runtime marker target, generation or window mismatch: %',r; END IF;
    BEGIN PERFORM (parsed->>'expiresAt')::timestamptz; EXCEPTION WHEN others THEN RAISE EXCEPTION 'Retired runtime marker expiry invalid: %',r; END;
    IF first_marker IS NULL THEN first_marker:=marker; ELSIF marker IS DISTINCT FROM first_marker THEN RAISE EXCEPTION 'Retired runtime markers are partial or mixed'; END IF;
    IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r AND (rolcanlogin OR rolvaliduntil IS DISTINCT FROM 'infinity'::timestamptz)) OR EXISTS(SELECT 1 FROM pg_authid WHERE rolname=r AND rolpassword IS NOT NULL) THEN RAISE EXCEPTION 'Runtime credential survives retirement: %',r; END IF;
    IF NOT EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member WHERE granted.rolname=r AND member.rolname=operator_name AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option) THEN RAISE EXCEPTION 'Missing retired runtime ADMIN-only operator edge: %',r; END IF;
    IF EXISTS(
      SELECT 1 FROM pg_namespace n CROSS JOIN LATERAL aclexplode(n.nspacl) a WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND a.grantee=0 AND a.privilege_type='USAGE'
      UNION ALL SELECT 1 FROM pg_namespace n CROSS JOIN LATERAL aclexplode(n.nspacl) a JOIN pg_roles g ON g.oid=a.grantee WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND g.rolname=r
      UNION ALL SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL aclexplode(c.relacl) a JOIN pg_roles g ON g.oid=a.grantee WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND g.rolname=r
      UNION ALL SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace CROSS JOIN LATERAL aclexplode(p.proacl) a JOIN pg_roles g ON g.oid=a.grantee WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND g.rolname=r) THEN RAISE EXCEPTION 'Direct private authority survives retirement: %',r; END IF;
    IF EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid
      JOIN pg_roles member ON member.oid=e.member WHERE (granted.rolname=r OR member.rolname=r)
        AND NOT (granted.rolname=r AND member.rolname=operator_name AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option)) THEN
      RAISE EXCEPTION 'Runtime login or executable membership survives retirement: %',r;
    END IF;
  END LOOP;
END $restore_edges_and_postflight$;
COMMIT;
