-- GENERATED by scripts/staging-account-activation-recovery.mjs; do not edit.
-- TLL staging recovery after migrations 012--016 only. Confirm project
-- qdmvngjwkcsilzmqksme outside this file; production wrhgscovsgsudtedbljr is excluded.
-- This transaction preserves rows/journals, does not DROP objects or touch auth.users,
-- and uses temporary, per-schema SET grants derived only from pre-existing exact
-- ADMIN TRUE / INHERIT FALSE / SET FALSE operator edges.
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';

DO $preflight$
DECLARE r text; operator_name name:=session_user;
BEGIN
  IF current_user<>session_user OR current_setting('server_version_num')::int<170000
    OR (SELECT rolsuper OR rolbypassrls OR NOT rolcreaterole FROM pg_roles WHERE rolname=operator_name) THEN
    RAISE EXCEPTION 'Recovery requires the reviewed non-superuser operator with CREATEROLE';
  END IF;
  FOREACH r IN ARRAY ARRAY[
    'tll_customer_private.control','tll_cart_private.control','tll_broker_private.control','tll_provisional_private.control','tll_bridge_private.control',
    'tll_customer_private.shopify_proofs','tll_cart_private.sessions','tll_cart_private.operations','tll_cart_private.transitions',
    'tll_broker_private.flows','tll_provisional_private.intents','tll_bridge_private.grants','tll_bridge_private.finalizations',
    'tll_bridge_private.account_generations','tll_bridge_private.account_operations','tll_bridge_private.account_logouts'
  ] LOOP
    -- to_regclass resolves through schema privileges, which the deliberately
    -- unprivileged operator lacks before the temporary owner SET edge exists.
    IF NOT EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
      WHERE n.nspname=split_part(r,'.',1) AND c.relname=split_part(r,'.',2)) THEN
      RAISE EXCEPTION 'Recovery requires reviewed 012--016 relation: %',r;
    END IF;
  END LOOP;
  FOREACH r IN ARRAY ARRAY['tll_customer_owner','tll_cart_owner','tll_broker_owner','tll_provisional_owner','tll_bridge_owner',
    'tll_customer_executor','tll_cart_gateway','tll_broker_executor','tll_provisional_executor','tll_bridge_executor',
    'tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
    IF NOT EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid
      WHERE granted.rolname=r AND e.member=operator_name::regrole AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option) THEN
      RAISE EXCEPTION 'Missing exact ADMIN-only operator edge: %',r;
    END IF;
  END LOOP;
  FOREACH r IN ARRAY ARRAY['tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
    IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r) THEN RAISE EXCEPTION 'Runtime role is absent: %',r; END IF;
  END LOOP;
  IF EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member
    WHERE member.rolname IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime')
      AND NOT ((granted.rolname,member.rolname) IN (('tll_customer_executor','tll_customer_runtime'),('tll_cart_gateway','tll_cart_runtime'),
        ('tll_broker_executor','tll_broker_runtime'),('tll_provisional_executor','tll_provisional_runtime'),('tll_bridge_executor','tll_bridge_runtime')))) THEN
    RAISE EXCEPTION 'Unexpected runtime membership; refuse broad role recovery';
  END IF;
  IF EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member
    WHERE (granted.rolname,member.rolname) IN (('tll_customer_executor','tll_customer_runtime'),('tll_cart_gateway','tll_cart_runtime'),
      ('tll_broker_executor','tll_broker_runtime'),('tll_provisional_executor','tll_provisional_runtime'),('tll_bridge_executor','tll_bridge_runtime'))
      AND e.grantor<>operator_name::regrole) THEN
    RAISE EXCEPTION 'Runtime execution edge was not granted by this recovery operator';
  END IF;
  IF has_table_privilege(operator_name,(SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='tll_customer_private' AND c.relname='control'),'UPDATE')
    OR has_table_privilege(operator_name,(SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='tll_broker_private' AND c.relname='control'),'UPDATE')
    OR has_table_privilege(operator_name,(SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='tll_provisional_private' AND c.relname='control'),'UPDATE')
    OR has_table_privilege(operator_name,(SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='tll_bridge_private' AND c.relname='control'),'UPDATE') THEN
    RAISE EXCEPTION 'Operator has unreviewed direct private write authority';
  END IF;
  -- Cart is intentionally owned by its recorded installation operator. Its
  -- NOLOGIN cart owner is denied control UPDATE by the reviewed RLS policy.
  IF (SELECT operator_oid FROM tll_cart_private.control WHERE singleton)<>operator_name::regrole::oid
    OR (SELECT pg_get_userbyid(relowner) FROM pg_class WHERE oid='tll_cart_private.control'::regclass)<>operator_name THEN
    RAISE EXCEPTION 'Cart recovery requires the original recorded cart table owner';
  END IF;
  IF NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='tll_bridge_private' AND p.proname='account_logout_repository' AND pg_get_function_identity_arguments(p.oid)='op text, p jsonb') THEN
    RAISE EXCEPTION 'Recovery requires migration 016';
  END IF;
END $preflight$;

DO $acquire_set_edges$
DECLARE operator_name name:=session_user; r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['tll_customer_owner','tll_cart_owner','tll_broker_owner','tll_provisional_owner','tll_bridge_owner'] LOOP
    EXECUTE format('GRANT %I TO %I WITH INHERIT TRUE, SET TRUE',r,operator_name);
  END LOOP;
END $acquire_set_edges$;

SET LOCAL ROLE tll_customer_owner;
LOCK TABLE tll_customer_private.control,tll_customer_private.shopify_proofs IN SHARE ROW EXCLUSIVE MODE;
UPDATE tll_customer_private.control SET enabled=false,changed_at=clock_timestamp(),reason_code='recovery_retired';
UPDATE tll_customer_private.shopify_proofs SET state='held',fence=nextval('tll_customer_private.shopify_proof_fences'),attempt_material=NULL,
  receipt_id=NULL,shop_id=NULL,issuer=NULL,subject=NULL,verified_at=NULL,proof_expires_at=NULL,access_expires_at=NULL,tokens=NULL WHERE state<>'held';
DO $verify_customer_drain$ BEGIN
  IF EXISTS(SELECT 1 FROM tll_customer_private.control WHERE enabled) OR EXISTS(SELECT 1 FROM tll_customer_private.shopify_proofs WHERE state<>'held') THEN
    RAISE EXCEPTION 'Customer recovery drain failed';
  END IF;
END $verify_customer_drain$;
RESET ROLE;

LOCK TABLE tll_cart_private.control,tll_cart_private.sessions,tll_cart_private.operations,tll_cart_private.transitions IN SHARE ROW EXCLUSIVE MODE;
UPDATE tll_cart_private.control SET enabled=false;
UPDATE tll_cart_private.sessions SET phase='held',lease_until=NULL WHERE phase='working';
UPDATE tll_cart_private.operations SET state='held' WHERE state='working';
UPDATE tll_cart_private.transitions SET state='held',lease_until=NULL WHERE state='claimed';
DO $verify_cart_drain$ BEGIN
  IF EXISTS(SELECT 1 FROM tll_cart_private.control WHERE enabled) OR EXISTS(SELECT 1 FROM tll_cart_private.sessions WHERE phase='working')
    OR EXISTS(SELECT 1 FROM tll_cart_private.operations WHERE state='working') OR EXISTS(SELECT 1 FROM tll_cart_private.transitions WHERE state='claimed') THEN
    RAISE EXCEPTION 'Cart recovery drain failed';
  END IF;
END $verify_cart_drain$;

SET LOCAL ROLE tll_broker_owner;
LOCK TABLE tll_broker_private.control,tll_broker_private.flows IN SHARE ROW EXCLUSIVE MODE;
UPDATE tll_broker_private.control SET enabled=false,changed_at=clock_timestamp(),reason_code='recovery_retired';
UPDATE tll_broker_private.flows SET status='cancelled',generation=generation+1,fence=nextval('tll_broker_private.fences') WHERE status NOT IN ('held','cancelled');
DO $verify_broker_drain$ BEGIN
  IF EXISTS(SELECT 1 FROM tll_broker_private.control WHERE enabled) OR EXISTS(SELECT 1 FROM tll_broker_private.flows WHERE status NOT IN ('held','cancelled')) THEN
    RAISE EXCEPTION 'Broker recovery drain failed';
  END IF;
END $verify_broker_drain$;
RESET ROLE;

SET LOCAL ROLE tll_provisional_owner;
LOCK TABLE tll_provisional_private.control,tll_provisional_private.intents IN SHARE ROW EXCLUSIVE MODE;
UPDATE tll_provisional_private.control SET enabled=false,changed_at=clock_timestamp(),reason_code='recovery_retired';
UPDATE tll_provisional_private.intents SET state='cancelled',material=NULL,generation=generation+1,fence=nextval('tll_provisional_private.fences') WHERE state NOT IN ('held','cancelled');
DO $verify_provisional_drain$ BEGIN
  IF EXISTS(SELECT 1 FROM tll_provisional_private.control WHERE enabled) OR EXISTS(SELECT 1 FROM tll_provisional_private.intents WHERE state NOT IN ('held','cancelled')) THEN
    RAISE EXCEPTION 'Provisional recovery drain failed';
  END IF;
END $verify_provisional_drain$;
RESET ROLE;

SET LOCAL ROLE tll_bridge_owner;
LOCK TABLE tll_bridge_private.control,tll_bridge_private.grants,tll_bridge_private.finalizations,tll_bridge_private.account_generations,tll_bridge_private.account_operations IN SHARE ROW EXCLUSIVE MODE;
UPDATE tll_bridge_private.control SET enabled=false,epoch=epoch+1,changed_at=clock_timestamp(),reason_code='recovery_retired';
UPDATE tll_bridge_private.grants SET state='cancelled',release_hash=NULL WHERE state NOT IN ('held','cancelled');
UPDATE tll_bridge_private.finalizations SET state='held',generation=generation+1,fence=nextval('tll_bridge_private.final_fences'),callback_material=NULL,
  provisional_material=NULL,user_id=NULL,identity_id=NULL,authenticated_at=NULL,checked_at=NULL,session_expires_at=NULL,session_material=NULL,reconciled_at=NULL WHERE state<>'held';
UPDATE tll_bridge_private.account_operations SET state='held',completed_at=COALESCE(completed_at,clock_timestamp()) WHERE state IN ('claimed','completed');
UPDATE tll_bridge_private.account_generations SET generation=generation+1,logout_session_id=NULL,updated_at=clock_timestamp();
DO $verify_bridge_drain$ BEGIN
  IF EXISTS(SELECT 1 FROM tll_bridge_private.control WHERE enabled) OR EXISTS(SELECT 1 FROM tll_bridge_private.grants WHERE state NOT IN ('held','cancelled'))
    OR EXISTS(SELECT 1 FROM tll_bridge_private.finalizations WHERE state<>'held') OR EXISTS(SELECT 1 FROM tll_bridge_private.account_operations WHERE state IN ('claimed','completed')) THEN
    RAISE EXCEPTION 'Bridge recovery drain failed';
  END IF;
END $verify_bridge_drain$;
RESET ROLE;

DO $retire_runtime_roles$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
    EXECUTE format('ALTER ROLE %I NOLOGIN PASSWORD NULL',r);
  END LOOP;
  REVOKE tll_customer_executor FROM tll_customer_runtime;
  REVOKE tll_cart_gateway FROM tll_cart_runtime;
  REVOKE tll_broker_executor FROM tll_broker_runtime;
  REVOKE tll_provisional_executor FROM tll_provisional_runtime;
  REVOKE tll_bridge_executor FROM tll_bridge_runtime;
END $retire_runtime_roles$;

DO $restore_edges_and_postflight$
DECLARE operator_name name:=session_user; r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['tll_customer_owner','tll_cart_owner','tll_broker_owner','tll_provisional_owner','tll_bridge_owner'] LOOP
    EXECUTE format('REVOKE %I FROM %I GRANTED BY %I',r,operator_name,operator_name);
    IF NOT EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid
      WHERE granted.rolname=r AND e.member=operator_name::regrole AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option)
      OR pg_has_role(operator_name,r,'USAGE') OR pg_has_role(operator_name,r,'SET') THEN RAISE EXCEPTION 'Owner edge was not restored to ADMIN-only: %',r; END IF;
  END LOOP;
  FOREACH r IN ARRAY ARRAY['tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
    IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r AND rolcanlogin) OR EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid
      JOIN pg_roles member ON member.oid=e.member WHERE (granted.rolname=r OR member.rolname=r)
        AND NOT (granted.rolname=r AND member.rolname=operator_name AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option)) THEN
      RAISE EXCEPTION 'Runtime login or executable membership survives retirement: %',r;
    END IF;
  END LOOP;
END $restore_edges_and_postflight$;
COMMIT;
