-- GENERATED by scripts/staging-account-activation-recovery.mjs; do not edit.
-- Run after recovery in a fresh session as the same reviewed staging operator.
-- This grants nothing and never signals a backend. Existing pg_read_all_stats is
-- required so session visibility is real; without it this gate fails closed.
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='25s';
DO $zero_runtime_sessions$
DECLARE deadline timestamptz:=clock_timestamp()+interval '20 seconds'; remaining integer; r text;
BEGIN
  IF current_user<>session_user OR NOT pg_has_role(session_user,'pg_read_all_stats','MEMBER') THEN
    RAISE EXCEPTION 'Post-commit runtime-session proof requires existing pg_read_all_stats authority';
  END IF;
  LOOP
    SELECT count(*) INTO remaining FROM pg_stat_activity WHERE backend_type='client backend'
      AND usename IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime');
    EXIT WHEN remaining=0;
    IF clock_timestamp()>=deadline THEN RAISE EXCEPTION 'Runtime sessions did not drain within bounded recovery window: %',remaining; END IF;
    PERFORM pg_sleep(1);
  END LOOP;
  FOREACH r IN ARRAY ARRAY['tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
    IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r AND rolcanlogin) OR EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid
      JOIN pg_roles member ON member.oid=e.member WHERE (granted.rolname=r OR member.rolname=r)
        AND NOT (granted.rolname=r AND member.rolname=session_user AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option)) THEN
      RAISE EXCEPTION 'Runtime identity recovered executable authority after retirement: %',r;
    END IF;
  END LOOP;
END $zero_runtime_sessions$;
COMMIT;
