-- GENERATED by scripts/staging-generation-21-recovery.mjs from the pinned generation-6 recovery; do not edit.
-- Run after recovery in a fresh session as the same reviewed staging operator.
-- This grants nothing and never signals a backend. Existing pg_read_all_stats is
-- required so session visibility is real; without it this gate fails closed.
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='25s';
DO $zero_runtime_sessions$
DECLARE deadline timestamptz:=clock_timestamp()+interval '20 seconds'; remaining integer; r text; marker text; parsed jsonb; first_marker text;
BEGIN
  IF current_database()<>'postgres' OR current_user<>'postgres' OR session_user<>'postgres' OR current_user<>session_user
    OR NOT pg_has_role(session_user,'pg_read_all_stats','MEMBER') THEN
    RAISE EXCEPTION 'Post-commit runtime-session proof requires exact staged postgres operator with existing pg_read_all_stats authority';
  END IF;
  IF to_regclass('tll_staging_private.environment') IS NULL OR (SELECT count(*) FROM tll_staging_private.environment)<>1
    OR NOT EXISTS(SELECT 1 FROM tll_staging_private.environment WHERE singleton AND environment='tll-hosted-staging-v1'
      AND operator_project_ref='qdmvngjwkcsilzmqksme' AND operator_context='supabase-dashboard:qdmvngjwkcsilzmqksme:staging-bootstrap:reviewed'
      AND identity_basis='explicit-operator-dashboard-binding' AND bootstrap_version='2026-09-15-v2'
      AND source_commit='a50e37ff05d8e731dc8ffceea1e96492079e5ff3' AND integrity_sha256='2d5175eb47a891ca626d635281fbb28237b16bec0d89eebe168455935117922c')
    OR EXISTS(SELECT 1 FROM tll_staging_private.environment WHERE operator_project_ref='wrhgscovsgsudtedbljr') THEN
    RAISE EXCEPTION 'Post-commit staging binding or reviewed bootstrap v2 mismatch';
  END IF;
  LOOP
    SELECT count(*) INTO remaining FROM pg_stat_activity WHERE backend_type='client backend'
      AND usename IN ('tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime');
    EXIT WHEN remaining=0;
    IF clock_timestamp()>=deadline THEN RAISE EXCEPTION 'Runtime sessions did not drain within bounded recovery window: %',remaining; END IF;
    PERFORM pg_sleep(1);
  END LOOP;
  FOREACH r IN ARRAY ARRAY['tll_customer_runtime','tll_cart_runtime','tll_broker_runtime','tll_provisional_runtime','tll_bridge_runtime'] LOOP
    SELECT shobj_description(oid,'pg_authid') INTO marker FROM pg_roles WHERE rolname=r;
    IF marker IS NULL OR marker !~ '^tll-runtime-window/v1 [{].*[}]$' THEN RAISE EXCEPTION 'Retired runtime marker is absent or malformed: %',r; END IF;
    BEGIN parsed:=substring(marker FROM '^tll-runtime-window/v1 ([{].*[}])$')::jsonb; EXCEPTION WHEN others THEN RAISE EXCEPTION 'Retired runtime marker JSON invalid: %',r; END;
    IF jsonb_typeof(parsed) IS DISTINCT FROM 'object' OR (SELECT count(*) FROM jsonb_object_keys(parsed)) IS DISTINCT FROM 5
      OR NOT (parsed ?& ARRAY['projectRef','generation','windowId','expiresAt','state'])
      OR jsonb_typeof(parsed->'projectRef') IS DISTINCT FROM 'string' OR parsed->>'projectRef' IS DISTINCT FROM 'qdmvngjwkcsilzmqksme'
      OR jsonb_typeof(parsed->'generation') IS DISTINCT FROM 'number' OR parsed->>'generation' IS DISTINCT FROM '21'
      OR jsonb_typeof(parsed->'windowId') IS DISTINCT FROM 'string' OR parsed->>'windowId' IS DISTINCT FROM 'a5511645-77af-4fc9-9e4c-f5c8a474d5fa'
      OR jsonb_typeof(parsed->'expiresAt') IS DISTINCT FROM 'string'
      OR jsonb_typeof(parsed->'state') IS DISTINCT FROM 'string' OR parsed->>'state' IS DISTINCT FROM 'retired' THEN RAISE EXCEPTION 'Retired runtime marker target, generation or window mismatch: %',r; END IF;
    BEGIN PERFORM (parsed->>'expiresAt')::timestamptz; EXCEPTION WHEN others THEN RAISE EXCEPTION 'Retired runtime marker expiry invalid: %',r; END;
    IF first_marker IS NULL THEN first_marker:=marker; ELSIF marker IS DISTINCT FROM first_marker THEN RAISE EXCEPTION 'Retired runtime markers are partial or mixed'; END IF;
    IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r AND (rolcanlogin OR rolvaliduntil IS DISTINCT FROM 'infinity'::timestamptz)) OR EXISTS(SELECT 1 FROM pg_authid WHERE rolname=r AND rolpassword IS NOT NULL) THEN RAISE EXCEPTION 'Runtime credential survives retirement: %',r; END IF;
    IF NOT EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member WHERE granted.rolname=r AND member.rolname=session_user AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option) THEN RAISE EXCEPTION 'Missing retired runtime ADMIN-only operator edge: %',r; END IF;
    IF EXISTS(
      SELECT 1 FROM pg_namespace n CROSS JOIN LATERAL aclexplode(n.nspacl) a WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND a.grantee=0 AND a.privilege_type='USAGE'
      UNION ALL SELECT 1 FROM pg_namespace n CROSS JOIN LATERAL aclexplode(n.nspacl) a JOIN pg_roles g ON g.oid=a.grantee WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND g.rolname=r
      UNION ALL SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL aclexplode(c.relacl) a JOIN pg_roles g ON g.oid=a.grantee WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND g.rolname=r
      UNION ALL SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace CROSS JOIN LATERAL aclexplode(p.proacl) a JOIN pg_roles g ON g.oid=a.grantee WHERE n.nspname LIKE 'tll\_%\_private' ESCAPE '\' AND g.rolname=r) THEN RAISE EXCEPTION 'Direct private authority survives retirement: %',r; END IF;
    IF EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid
      JOIN pg_roles member ON member.oid=e.member WHERE (granted.rolname=r OR member.rolname=r)
        AND NOT (granted.rolname=r AND member.rolname=session_user AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option)) THEN
      RAISE EXCEPTION 'Runtime identity recovered executable authority after retirement: %',r;
    END IF;
  END LOOP;
  IF (SELECT count(*) FROM tll_customer_private.control)<>1 OR EXISTS(SELECT 1 FROM tll_customer_private.control WHERE NOT singleton OR enabled)
    OR (SELECT count(*) FROM tll_cart_private.control)<>1 OR EXISTS(SELECT 1 FROM tll_cart_private.control WHERE NOT singleton OR enabled)
    OR (SELECT count(*) FROM tll_broker_private.control)<>1 OR EXISTS(SELECT 1 FROM tll_broker_private.control WHERE NOT singleton OR enabled)
    OR (SELECT count(*) FROM tll_provisional_private.control)<>1 OR EXISTS(SELECT 1 FROM tll_provisional_private.control WHERE NOT singleton OR enabled)
    OR (SELECT count(*) FROM tll_bridge_private.control)<>1 OR EXISTS(SELECT 1 FROM tll_bridge_private.control WHERE NOT singleton OR enabled) THEN
    RAISE EXCEPTION 'Post-commit controls are not exact-singleton disabled';
  END IF;
END $zero_runtime_sessions$;
COMMIT;
SELECT jsonb_build_object('queryId','tll-staging-generation-21-retirement-postcommit/v1','projectRef','qdmvngjwkcsilzmqksme','generation',21,'windowId','a5511645-77af-4fc9-9e4c-f5c8a474d5fa','status','PASS_RETIRED','runtimeRoles',5,'runtimeSessions',0,'controlsEnabled',0,'passwordsConfigured',0,'validUntilInfinity',5,'executionEdges',0,'operatorEdges',5) AS tll_gen21_retirement_postcommit;
