-- populate-buy-urls.sql
-- GENERATED by scripts/gen-buy-urls.mjs — do not edit by hand.
-- Sets products.buy_url to a verified DIRECT product page (deep-link).
-- Source: Path A webapp/data.js prices[0].url. Match on brand+name (the live
-- table was seeded verbatim from the same data, so these match exactly).
-- Idempotent. Run AFTER add-buy-url.sql in the Supabase SQL Editor.

UPDATE public.products SET buy_url = 'https://www.gymstop.co.uk/products/applied-nutrition-abe-all-black-everything' WHERE brand = 'Applied Nutrition' AND name = 'ABE (All Black Everything)';
UPDATE public.products SET buy_url = 'https://stromsports.com/products/strom-presents-stimumaxpro-v2' WHERE brand = 'Strom Sports Nutrition' AND name = 'StimuMAX PRO';
UPDATE public.products SET buy_url = 'https://ghostlifestyle.co.uk/products/ghost-legend-v4-blue-raspberry' WHERE brand = 'Ghost Lifestyle' AND name = 'Ghost Legend';
UPDATE public.products SET buy_url = 'https://hr-labs.co.uk/products/defib-v3-limited-edition' WHERE brand = 'HR Labs' AND name = 'Defib V3';
UPDATE public.products SET buy_url = 'https://darkstims.com/products/darkstimspre' WHERE brand = 'Darkstims' AND name = 'PRE V4';
UPDATE public.products SET buy_url = 'https://darkstims.com/products/darkstims-black-death-pre-workout' WHERE brand = 'Darkstims' AND name = 'Ultra Pre Workout';
UPDATE public.products SET buy_url = 'https://reflexnutrition.com/products/pre-workout' WHERE brand = 'Reflex Nutrition' AND name = 'Pre-Workout';
UPDATE public.products SET buy_url = 'https://www.nutritiongeeks.co/products/pure-creatine-monohydrate' WHERE brand = 'Nutrition Geeks' AND name = 'Pure Creatine Monohydrate Powder';
UPDATE public.products SET buy_url = 'https://www.myprotein.com/p/sports-nutrition/creatine-monohydrate-powder/10530050/' WHERE brand = 'MyProtein' AND name = 'Impact Creatine';
UPDATE public.products SET buy_url = 'https://www.bulk.com/uk/products/creatine-monohydrate/bpb-cmon-0000' WHERE brand = 'Bulk' AND name = 'Creatine Monohydrate';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-creatine-monohydrate-500g' WHERE brand = 'Supplement Needs' AND name = 'Creatine Monohydrate';
UPDATE public.products SET buy_url = 'https://appliednutrition.uk/products/creatine-monohydrate' WHERE brand = 'Applied Nutrition' AND name = 'Creatine Monohydrate';
UPDATE public.products SET buy_url = 'https://darkstims.com/products/darkstims-creatine' WHERE brand = 'Darkstims' AND name = 'Creatine Monohydrate';
UPDATE public.products SET buy_url = 'https://teamwarrior.com/products/warrior-creatine-monohydrate-powder-500g' WHERE brand = 'Warrior' AND name = 'Creatine Monohydrate';
UPDATE public.products SET buy_url = 'https://reflexnutrition.com/products/creapure-creatine-powder' WHERE brand = 'Reflex Nutrition' AND name = 'Creatine Powder (Creapure®)';
UPDATE public.products SET buy_url = 'https://appliednutrition.uk/products/amino-fuel-390g' WHERE brand = 'Applied Nutrition' AND name = 'Amino Fuel EAA';
UPDATE public.products SET buy_url = 'https://stromsports.com/products/essentialmax-eaa' WHERE brand = 'Strom Sports Nutrition' AND name = 'EssentialMax';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-intra-eaa-30-servings' WHERE brand = 'Supplement Needs' AND name = 'Intra EAA+';
UPDATE public.products SET buy_url = 'https://cnpprofessional.co.uk/products/loaded-eaa-fantasy-series-orange' WHERE brand = 'CNP Professional' AND name = 'CNP EAA';
UPDATE public.products SET buy_url = 'https://mutantnation.com/products/geaar-recover-now' WHERE brand = 'Mutant' AND name = 'GEAAR';
UPDATE public.products SET buy_url = 'https://grenade.com/products/strawberry-mango-bcaa-390g' WHERE brand = 'Grenade' AND name = 'Strawberry Mango BCAA';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-intra-eaa-30-servings' WHERE brand = 'Supplement Needs' AND name = 'Intra EAA+';
UPDATE public.products SET buy_url = 'https://hr-labs.co.uk/products/level-up-v2' WHERE brand = 'HR Labs' AND name = 'Level Up';
UPDATE public.products SET buy_url = 'https://contehsports.com/products/essential-gains-eaa' WHERE brand = 'Conteh Sports' AND name = 'Essential Amino';
UPDATE public.products SET buy_url = 'https://stromsports.com/products/essentialmax-eaa' WHERE brand = 'Strom Sports Nutrition' AND name = 'EssentialMAX';
UPDATE public.products SET buy_url = 'https://appliednutrition.uk/products/velocity-fuel-recovery-post-exercise-recovery-drink' WHERE brand = 'Applied Nutrition' AND name = 'Endurance Recovery';
UPDATE public.products SET buy_url = 'https://reflexnutrition.com/products/one-stop®-xtreme-short-dated' WHERE brand = 'Reflex Nutrition' AND name = 'One Stop Xtreme';
UPDATE public.products SET buy_url = 'https://cnpprofessional.co.uk/products/recover-1-28kg-16-servings-strawberry' WHERE brand = 'CNP Professional' AND name = 'Pro Recover';
UPDATE public.products SET buy_url = 'https://appliednutrition.uk/products/bodyfuel-mass-gainer' WHERE brand = 'Applied Nutrition' AND name = 'Mass';
UPDATE public.products SET buy_url = 'https://reflexnutrition.com/products/instant-mass-heavyweight' WHERE brand = 'Reflex Nutrition' AND name = 'Instant Mass® Heavyweight';
UPDATE public.products SET buy_url = 'https://stromsports.com/products/hydramax' WHERE brand = 'Strom Sports Nutrition' AND name = 'Hydramax';
UPDATE public.products SET buy_url = 'https://darkstims.com/products/darkstims-electrolytes' WHERE brand = 'Darkstims' AND name = 'Electrolytes';
UPDATE public.products SET buy_url = 'https://www.amazon.co.uk/dp/B00EZTKZDE?tag=theliftinglab-21' WHERE brand = 'MyProtein' AND name = 'Impact Whey Protein';
UPDATE public.products SET buy_url = 'https://www.amazon.co.uk/dp/B000QSNYGI?tag=theliftinglab-21' WHERE brand = 'Optimum Nutrition' AND name = 'Gold Standard 100% Whey';
UPDATE public.products SET buy_url = 'https://appliednutrition.uk/products/critical-whey' WHERE brand = 'Applied Nutrition' AND name = 'Critical Whey';
UPDATE public.products SET buy_url = 'https://reflexnutrition.com/products/100-whey' WHERE brand = 'Reflex Nutrition' AND name = '100% Whey';
UPDATE public.products SET buy_url = 'https://sci-mx.co.uk/products/ultra-whey-protein-1' WHERE brand = 'Sci-MX' AND name = 'Ultra Whey';
UPDATE public.products SET buy_url = 'https://cnpprofessional.co.uk/products/isolate-pouches-900g-chocolate' WHERE brand = 'CNP Professional' AND name = 'CNP Isolate';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-whey-iso-plus-1kg' WHERE brand = 'Supplement Needs' AND name = 'Whey Isolate';
UPDATE public.products SET buy_url = 'https://www.bulk.com/uk/products/pure-whey-isolate-90/bpb-wpi9-0000' WHERE brand = 'Bulk' AND name = 'Pure Whey Isolate';
UPDATE public.products SET buy_url = 'https://gymstop.co.uk/products/copy-of-applied-nutrition-iso-xp-1-8kg' WHERE brand = 'Applied Nutrition' AND name = 'ISO-XP';
UPDATE public.products SET buy_url = 'https://stromsports.com/products/whey-max-v-1-2kg-2-4g-velocitol-per-serving-80-whey-20-casein-blend' WHERE brand = 'Strom Sports Nutrition' AND name = 'VelosiWHEY Isolate';
UPDATE public.products SET buy_url = 'https://reflexnutrition.com/products/isolate-pro' WHERE brand = 'Reflex Nutrition' AND name = 'Isolate Pro';
UPDATE public.products SET buy_url = 'https://appliednutrition.uk/products/micellar-casein-protein' WHERE brand = 'Applied Nutrition' AND name = '100% Casein Protein';
UPDATE public.products SET buy_url = 'https://usn.co.uk/products/casein-pro' WHERE brand = 'USN' AND name = '100% Premium Micellar Casein';
UPDATE public.products SET buy_url = 'https://appliednutrition.uk/products/protein-crunch-bar-62grams' WHERE brand = 'Applied Nutrition' AND name = 'Protein Crunch Bar (Chocolate Caramel)';
UPDATE public.products SET buy_url = 'https://usn.co.uk/products/trust-crunch-bar-raspberry-cheese-cake-flavour-low-calorie-high-protein-snack-12-x-60g' WHERE brand = 'USN' AND name = 'Trust Crunch (Chocolate Peanut)';
UPDATE public.products SET buy_url = 'https://nutritiongeeks.co/products/vitamin-d3-4000iu-k2' WHERE brand = 'Nutrition Geeks' AND name = 'Vitamin D3 4000iu + K2';
UPDATE public.products SET buy_url = 'https://nutritiongeeks.co/products/vitamin-d-4000iu-max-strength-immune-support' WHERE brand = 'Nutrition Geeks' AND name = 'Vitamin D 4000iu Max Strength';
UPDATE public.products SET buy_url = 'https://nutritiongeeks.co/products/zinc-picolinate-3-in-1' WHERE brand = 'Nutrition Geeks' AND name = 'Zinc Picolinate 3-in-1';
UPDATE public.products SET buy_url = 'https://nutritiongeeks.co/products/vitamin-b12-dual-power-1-year-supply' WHERE brand = 'Nutrition Geeks' AND name = 'Vitamin B12 Dual Power';
UPDATE public.products SET buy_url = 'https://nutritiongeeks.co/products/magnesium-glycinate-3-in-1' WHERE brand = 'Nutrition Geeks' AND name = 'Magnesium Glycinate 3-in-1';
UPDATE public.products SET buy_url = 'https://nutritiongeeks.co/products/ashwagandha-calm' WHERE brand = 'Nutrition Geeks' AND name = 'Ashwagandha Calm+';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-vitamin-d3-and-k2-mk-7-120-tabs' WHERE brand = 'Supplement Needs' AND name = 'Vitamin D3 and K2 (MK-7)';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-vitamin-d3-120-tablets' WHERE brand = 'Supplement Needs' AND name = 'Vitamin D3';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-magnesium-bisglycinate-120-capsules' WHERE brand = 'Supplement Needs' AND name = 'Magnesium Bisglycinate';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-ashwagandha-ksm-66-60-capsules' WHERE brand = 'Supplement Needs' AND name = 'Ashwagandha Organic Vegan KSM-66';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-advanced-vitamin-b-complex-60-capsules' WHERE brand = 'Supplement Needs' AND name = 'Advanced Vitamin B Complex';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-multi-vitamin-and-mineral-pro' WHERE brand = 'Supplement Needs' AND name = 'Multi Vitamin and Mineral PRO';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-omega-3-high-strength-90-softgels' WHERE brand = 'Supplement Needs' AND name = 'Omega 3 High Strength';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-greens-330g' WHERE brand = 'Supplement Needs' AND name = 'Greens+';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-vitamin-c-powder-300g' WHERE brand = 'Supplement Needs' AND name = 'Vitamin C Powder';
UPDATE public.products SET buy_url = 'https://supplementneeds.co.uk/products/supplement-needs-vitamin-k2-mk-4-120-tablets' WHERE brand = 'Supplement Needs' AND name = 'Vitamin K2 (MK-4)';
UPDATE public.products SET buy_url = 'https://stromsports.com/products/strom-zmax-45-servings' WHERE brand = 'Strom Sports Nutrition' AND name = 'ZMAX';
UPDATE public.products SET buy_url = 'https://nutritiongeeks.co/products/apple-cider-vinegar' WHERE brand = 'Nutrition Geeks' AND name = 'Apple Cider Vinegar+';
UPDATE public.products SET buy_url = 'https://nutritiongeeks.co/products/turmeric-tablets-with-ginger-and-black-pepper' WHERE brand = 'Nutrition Geeks' AND name = 'Turmeric, Ginger & Black Pepper';
UPDATE public.products SET buy_url = 'https://appliednutrition.uk/products/digestive-enzymes-capsules' WHERE brand = 'Applied Nutrition' AND name = 'Digestive Enzyme Capsules';

-- 67 direct URLs emitted.
