/**
 * Canonical, deterministic construction for the disabled 012--016 staging
 * upgrade. This is intentionally a file-to-file compiler, not a SQL runner.
 */
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

export const PROJECT_REF = 'qdmvngjwkcsilzmqksme'
export const PRODUCTION_PROJECT_REF = 'wrhgscovsgsudtedbljr'
export const INSTALL_ID = 'tll-staging-disabled-migrations-012-016/v1'
export const MIGRATIONS = Object.freeze([
  ['202609180012_customer_shopify_proof_repository', 'supabase/migrations/202609180012_customer_shopify_proof_repository.sql', 'c0b105293f01b79329c050a16702ad98123b744b63c85a63dbce8c1a2b7b6e61'],
  ['202609180013_customer_final_reconciliation', 'supabase/migrations/202609180013_customer_final_reconciliation.sql', '4dc438d016fbe2f4e1a5cac7c76aa9f48f0bde369488702661f516fdd88841a6'],
  ['202609180014_staging_cart_account_transition', 'supabase/migrations/202609180014_staging_cart_account_transition.sql', '99b3737bcffe7957e5eeb64d46566953ad2a9e8b4d045fdaf9e995a223a29061'],
  ['202609180015_customer_account_operations', 'supabase/migrations/202609180015_customer_account_operations.sql', 'dfaafaa6ee121c5f33e7f1aff6a83f14d972455ef5fdd0ed2a49411f8b15c0ee'],
  ['202609180016_customer_account_logout', 'supabase/migrations/202609180016_customer_account_logout.sql', 'b512d9d18599b60a18ea20d94b3502d94c5735c1ac20bbb76321efd46dea8349'],
])
const BASELINE = Object.freeze([
  ['202609150002_public_submission_gateway', 'c82f9afb10c7ee7e46549033d4076046568557226a7864f8c2b8c8117ecd4bca'],
  ['202609150003_active_stack_integrity', '05cac500b24262975a773b2db284bc3fb95b62dc25fc6d47670eefbc86f15a60'],
  ['202609150004_inventory_operation_ledger', '030ccb26228aca6665147eced447815f8a290abd74b8003b0f32bfb2a05e5a76'],
  ['202609150005_customer_connection_repository', 'f0f49edca9a0938b8e40b4d87ba7ee1eaee02dbc5082fc019a58ca949b263d0b'],
  ['202609150006_staging_cart_sessions', '17d039a6d1f343f35d1551c259a3f8c0e8643fe669b8230170a235bbc941155c'],
  ['202609150007_customer_subject_broker_repository', '85a118335d91d896b707dcdff1570f6c2df22a9b2037e9a569b587b89ad41c21'],
  ['202609170008_customer_provisional_admission_repository', '038b2bfc9d236f39c0cb5ae9b657a5a54b572fc304e6da318b00a07cf0d201e2'],
  ['202609170009_inventory_maintenance_authority', '4f054b145466a6ef2136ec79a0e1c17e8aa252e5bc02fa8c27deb23664eb153f'],
  ['202609170010_customer_admission_bridge', '711b92ef8a6e5760a126e340396f68cc372e361ee3e6bf66f3e6f3370be5f7aa'],
  ['202609170011_customer_browser_admission_once', '12bf5b5916d2f266f218bcd39c38098aea3225acef1cb0f67b47fe76bc29f58f'],
])
const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
const sha256 = value => createHash('sha256').update(value).digest('hex')
const sqlValues = pairs => pairs.map(([version, hash]) => `('${version}','${hash}')`).join(',')
const quoteList = values => values.map(value => `'${value}'`).join(',')

function canonicalBody (source, path) {
  const begin = source.indexOf('\nBEGIN;\n')
  if (begin < 0 || !source.endsWith('COMMIT;\n') || source.indexOf('\nBEGIN;\n', begin + 1) >= 0) throw new Error(`Unexpected migration transaction wrapper: ${path}`)
  // Preserve every byte apart from exactly one outer BEGIN and trailing COMMIT.
  return source.slice(0, begin + 1) + source.slice(begin + '\nBEGIN;\n'.length, -'COMMIT;\n'.length)
}

export function buildPackage () {
  const sources = MIGRATIONS.map(([version, path, expected]) => {
    const source = readFileSync(resolve(root, path), 'utf8')
    const actual = sha256(source)
    if (actual !== expected) throw new Error(`Reviewed migration source drift: ${version}`)
    return { version, path, sha256: actual, body: canonicalBody(source, path) }
  })
  const predecessor = sqlValues(BASELINE)
  const additions = sqlValues(sources.map(source => [source.version, source.sha256]))
  const versions = quoteList(sources.map(source => source.version))
  const outerPreflight = `-- GENERATED by scripts/staging-disabled-migrations-012-016.prepare.mjs; do not edit.\n-- The only generated transformation removes each canonical migration's outer\n-- BEGIN/COMMIT wrapper so all five sources commit or roll back together.\nBEGIN;\nSET LOCAL lock_timeout='5s';\nSET LOCAL statement_timeout='60s';\nDO $tll_install_guard$\nDECLARE expected_count integer:=${BASELINE.length}; actual_count integer; matched_count integer; r text;\nBEGIN\n IF current_database()<>'postgres' OR current_user<>'postgres' OR session_user<>'postgres' OR current_user<>session_user\n   OR coalesce((SELECT rolsuper FROM pg_roles WHERE rolname=current_user),true)\n   OR NOT coalesce((SELECT rolcreaterole FROM pg_roles WHERE rolname=current_user),false)\n   OR NOT pg_has_role(current_user,'pg_read_all_data','USAGE') OR pg_has_role(current_user,'pg_write_all_data','USAGE')\n   OR NOT pg_has_role(current_user,'pg_read_all_stats','USAGE') THEN RAISE EXCEPTION 'Exact managed non-superuser staging postgres operator authority required'; END IF;\n IF to_regclass('tll_staging_private.environment') IS NULL OR (SELECT count(*) FROM tll_staging_private.environment)<>1\n   OR NOT EXISTS(SELECT 1 FROM tll_staging_private.environment WHERE singleton AND environment='tll-hosted-staging-v1' AND operator_project_ref='${PROJECT_REF}' AND operator_context='supabase-dashboard:${PROJECT_REF}:staging-bootstrap:reviewed' AND identity_basis='explicit-operator-dashboard-binding' AND bootstrap_version='2026-09-15-v2')\n   OR EXISTS(SELECT 1 FROM tll_staging_private.environment WHERE operator_project_ref='${PRODUCTION_PROJECT_REF}') THEN RAISE EXCEPTION 'Exact staging environment binding required; production is excluded'; END IF;\n SELECT count(*),count(*) FILTER (WHERE (version,source_sha256) IN (VALUES ${predecessor})) INTO actual_count,matched_count FROM tll_staging_private.applied_migrations;\n IF actual_count<>expected_count OR matched_count<>expected_count OR EXISTS(SELECT 1 FROM tll_staging_private.applied_migrations WHERE version IN (${versions})) THEN RAISE EXCEPTION 'Exact 002--011 predecessor ledger required'; END IF;\n IF tll_customer_private.operator_status()->'enabled'<>'false'::jsonb OR coalesce((SELECT enabled FROM tll_cart_private.control WHERE singleton),true)\n   OR tll_broker_private.operator_status()->'enabled'<>'false'::jsonb OR tll_provisional_private.operator_status()->'enabled'<>'false'::jsonb OR tll_bridge_private.operator_status()->'enabled'<>'false'::jsonb THEN RAISE EXCEPTION 'All controls must remain disabled'; END IF;\n IF to_regclass('tll_customer_private.shopify_proofs') IS NOT NULL OR to_regclass('tll_bridge_private.finalizations') IS NOT NULL OR to_regclass('tll_cart_private.transitions') IS NOT NULL OR to_regclass('tll_bridge_private.account_generations') IS NOT NULL OR to_regclass('tll_bridge_private.account_logouts') IS NOT NULL THEN RAISE EXCEPTION 'Expected empty migration destination required'; END IF;\n FOREACH r IN ARRAY ARRAY['tll_customer_owner','tll_cart_owner','tll_broker_owner','tll_provisional_owner','tll_bridge_owner'] LOOP\n   IF NOT EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member WHERE granted.rolname=r AND member.rolname=current_user AND e.admin_option AND NOT e.inherit_option AND NOT e.set_option) THEN RAISE EXCEPTION 'Exact reviewed ADMIN-only owner authority required: %',r; END IF;\n END LOOP;\nEND $tll_install_guard$;\n`
  const ledger = `INSERT INTO tll_staging_private.applied_migrations(version,source_sha256) VALUES ${additions};\nDO $tll_install_postflight$\nDECLARE installed integer;\nBEGIN\n SELECT count(*) INTO installed FROM tll_staging_private.applied_migrations WHERE (version,source_sha256) IN (VALUES ${additions});\n IF installed<>${sources.length} OR (SELECT count(*) FROM tll_staging_private.applied_migrations)<>${BASELINE.length + sources.length}\n   OR tll_customer_private.operator_status()->'enabled'<>'false'::jsonb OR coalesce((SELECT enabled FROM tll_cart_private.control WHERE singleton),true)\n   OR tll_broker_private.operator_status()->'enabled'<>'false'::jsonb OR tll_provisional_private.operator_status()->'enabled'<>'false'::jsonb OR tll_bridge_private.operator_status()->'enabled'<>'false'::jsonb\n   OR to_regclass('tll_customer_private.shopify_proofs') IS NULL OR to_regclass('tll_bridge_private.finalizations') IS NULL OR to_regclass('tll_cart_private.transitions') IS NULL OR to_regclass('tll_bridge_private.account_generations') IS NULL OR to_regclass('tll_bridge_private.account_logouts') IS NULL\n   OR EXISTS(SELECT 1 FROM tll_customer_private.shopify_proofs) OR EXISTS(SELECT 1 FROM tll_bridge_private.finalizations) OR EXISTS(SELECT 1 FROM tll_cart_private.transitions) OR EXISTS(SELECT 1 FROM tll_bridge_private.account_generations) OR EXISTS(SELECT 1 FROM tll_bridge_private.account_operations) OR EXISTS(SELECT 1 FROM tll_bridge_private.account_logouts)\n   OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tll_customer_private.shopify_proofs'::regclass) OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tll_bridge_private.finalizations'::regclass) OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tll_cart_private.transitions'::regclass) OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tll_bridge_private.account_generations'::regclass) OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tll_bridge_private.account_logouts'::regclass)\n   OR EXISTS(SELECT 1 FROM pg_auth_members e JOIN pg_roles granted ON granted.oid=e.roleid JOIN pg_roles member ON member.oid=e.member WHERE granted.rolname IN ('tll_customer_owner','tll_cart_owner','tll_broker_owner','tll_provisional_owner','tll_bridge_owner') AND member.rolname=current_user AND (NOT e.admin_option OR e.inherit_option OR e.set_option)) THEN RAISE EXCEPTION 'Disabled migration postflight mismatch'; END IF;\nEND $tll_install_postflight$;\nSELECT jsonb_build_object('installId','${INSTALL_ID}','projectRef','${PROJECT_REF}','status','PASS','migrationCount',${sources.length},'controlsDisabled',true,'objectsPresent',true) AS tll_disabled_migration_postflight;\nCOMMIT;\n`
  const sql = outerPreflight + sources.map(source => source.body).join('\n') + ledger
  return Object.freeze({ installId: INSTALL_ID, target: PROJECT_REF, productionExcluded: PRODUCTION_PROJECT_REF, sources: sources.map(({ version, path, sha256: sourceHash }) => ({ version, path, sha256: sourceHash })), sql, sqlSha256: sha256(sql) })
}

function artifacts () {
  const pkg = buildPackage()
  const nodeSource = readFileSync(resolve(root, 'scripts/staging-disabled-migrations-012-016.mjs'), 'utf8')
  const helperSource = readFileSync(resolve(root, 'scripts/staging-disabled-migrations-012-016-keychain.py'), 'utf8')
  const nodeApproved = /^export const NATIVE_ACCESS_APPROVED = (true|false)$/m.exec(nodeSource)?.[1]
  const helperApproved = /^APPROVED_NATIVE_READ = (True|False)$/m.exec(helperSource)?.[1]
  if (nodeApproved === undefined || helperApproved === undefined || (nodeApproved === 'true') !== (helperApproved === 'True')) throw new Error('native access flags disagree')
  return { pkg, sql: pkg.sql, manifest: JSON.stringify({ schema: `${INSTALL_ID}/manifest`, target: pkg.target, productionExcluded: pkg.productionExcluded, nativeAccessApproved: nodeApproved === 'true', sourcePins: pkg.sources, transactionSha256: pkg.sqlSha256, sourcePinsForTransport: [{ path: 'scripts/staging-disabled-migrations-012-016.mjs', sha256: sha256(nodeSource) }, { path: 'scripts/staging-disabled-migrations-012-016-keychain.py', sha256: sha256(helperSource) }], transport: { hostname: 'api.supabase.com', path: `/v1/projects/${PROJECT_REF}/database/query`, method: 'POST', redirects: false, maxAgeMs: 60000, maxRequests: 1 } }, null, 2) + '\n' }
}
function writeArtifacts () {
  const output = artifacts()
  writeFileSync(resolve(root, 'config/staging-disabled-migrations-012-016.sql'), output.sql, { mode: 0o644 })
  writeFileSync(resolve(root, 'config/staging-disabled-migrations-012-016.json'), output.manifest, { mode: 0o644 })
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (process.argv.length === 2) writeArtifacts()
  else if (process.argv.length === 3 && process.argv[2] === '--check') {
    const output = artifacts()
    if (readFileSync(resolve(root, 'config/staging-disabled-migrations-012-016.sql'), 'utf8') !== output.sql || readFileSync(resolve(root, 'config/staging-disabled-migrations-012-016.json'), 'utf8') !== output.manifest) throw new Error('disabled staging migration artifacts are stale')
  } else throw new Error('Only --check is accepted')
}
