import test,{beforeEach}from'node:test'
import assert from'node:assert/strict'
import{execFileSync,spawn}from'node:child_process'
import{randomUUID}from'node:crypto'
const C='tll-stage0-postgres',D='tll_cart_account_v2',G='tll_ca2_gateway'
const run=(input,role)=>{try{return execFileSync('docker',['exec','-i',C,'psql','-XqAt','-U','postgres','-d',D,'-v','ON_ERROR_STOP=1'],{input:(role?`SET ROLE ${role};`:'')+input,encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim()}catch{throw Error('Cart account SQL failed')}}
const q=v=>"'"+String(v).replaceAll("'","''")+"'",env={v:1,alg:'A256GCM',kid:'k',iv:'a'.repeat(16),tag:'b'.repeat(22),ciphertext:'cipher'}
const rpc=(name,args)=>JSON.parse(run(`SELECT public.tll_cart_transition_${name}(${args.join(',')})`,G))
const h=n=>String(n).repeat(64),source=h(1),guest=h(2),target=h(3),account=h(4)
assert.equal(run("SELECT current_database()||':'||shobj_description(oid,'pg_database') FROM pg_database WHERE datname=current_database()"),D+':tll-cart-account-synthetic-v2')
beforeEach(()=>run(`TRUNCATE tll_cart_private.transitions,tll_cart_private.operations,tll_cart_private.sessions CASCADE;UPDATE tll_cart_private.control SET enabled=true;`))
const open=(s=source,a=guest)=>JSON.parse(run(`SELECT public.tll_cart_open(${q(s)},${q(a)})`,G))
const claim=(id=randomUUID(),revision=0)=>rpc('claim',[q(source),q(guest),q(target),q(account),q(id),revision])

test('migration installs disabled with exact function-only authority',()=>{run('UPDATE tll_cart_private.control SET enabled=false');assert.equal(run('SELECT enabled FROM tll_cart_private.control'),'f');assert.equal(run("SELECT relrowsecurity FROM pg_class WHERE oid='tll_cart_private.transitions'::regclass"),'t');assert.equal(run("SELECT has_table_privilege('tll_ca2_gateway','tll_cart_private.transitions','SELECT,INSERT,UPDATE,DELETE')"),'f');assert.equal(run("SELECT has_function_privilege('tll_ca2_gateway','public.tll_cart_transition_claim(text,text,text,text,uuid,bigint)','EXECUTE')::text||':'||has_function_privilege('authenticated','public.tll_cart_transition_claim(text,text,text,text,uuid,bigint)','EXECUTE')::text"),'true:false')})
test('one-use claim and finish move encrypted custody to the account session',()=>{open();run(`UPDATE tll_cart_private.sessions SET envelope=${q(JSON.stringify(env))}::jsonb,quantity=2,unit_price_pence=1200,subtotal_pence=2400 WHERE session_hash=${q(source)}`);const id=randomUUID(),c=claim(id);assert.equal(c.status,'claimed');const out=rpc('finish',[q(source),q(guest),q(target),q(account),q(id),q(JSON.stringify({...env,ciphertext:'rewrapped'}))+'::jsonb',2,1200,2400]);assert.equal(out.status,'reconciled');assert.equal(out.target.actorHash,account);assert.equal(run(`SELECT phase||':'||quantity||':'||(envelope IS NULL) FROM tll_cart_private.sessions WHERE session_hash=${q(source)}`),'held:0:true');assert.equal(claim(id).status,'reconciled');assert.equal(claim(randomUUID()).status,'conflict')})
test('an existing account cart or stale revision cannot be merged or replaced',()=>{open();open(target,account);assert.equal(claim().status,'conflict');run(`DELETE FROM tll_cart_private.sessions WHERE session_hash=${q(target)}`);assert.equal(claim(randomUUID(),1).status,'conflict');assert.equal(run('SELECT count(*) FROM tll_cart_private.transitions'),'0')})
test('expired transition becomes held and cannot be finished',()=>{open();const id=randomUUID();assert.equal(claim(id).status,'claimed');run(`UPDATE tll_cart_private.transitions SET lease_until=clock_timestamp()-interval '1 second' WHERE source_session=${q(source)}`);const inspected=rpc('read',[q(source),q(guest),q(target),q(account)]);assert.equal(inspected.status,'held');assert.equal(run(`SELECT phase FROM tll_cart_private.sessions WHERE session_hash=${q(source)}`),'held');assert.equal(rpc('finish',[q(source),q(guest),q(target),q(account),q(id),'null',0,'null','null']).status,'rejected')})
test('concurrent claims admit exactly one transfer',async()=>{open();const call=id=>new Promise((resolve,reject)=>{const child=spawn('docker',['exec','-i',C,'psql','-XqAt','-U','postgres','-d',D,'-v','ON_ERROR_STOP=1'],{stdio:['pipe','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',v=>stdout+=v);child.stderr.on('data',v=>stderr+=v);child.once('close',code=>code===0?resolve(JSON.parse(stdout.trim())):reject(Error(stderr)));child.stdin.end(`SET ROLE ${G};SELECT public.tll_cart_transition_claim(${q(source)},${q(guest)},${q(target)},${q(account)},${q(id)},0)`)});const values=await Promise.all([call(randomUUID()),call(randomUUID())]);assert.deepEqual(values.map(v=>v.status).sort(),['claimed','conflict'])})
test('disabled control rejects every transition entrypoint',()=>{open();run('UPDATE tll_cart_private.control SET enabled=false');for(const [name,args]of[['read',[q(source),q(guest),q(target),q(account)]],['claim',[q(source),q(guest),q(target),q(account),q(randomUUID()),0]]])assert.throws(()=>rpc(name,args),/Cart account SQL failed/)})
